(function(){
'use strict';
var KEY='nursetrack_admin_center_v291', STORE='nursetrack_clinical_v21', AUTH='nursetrack_clinical_auth_v21';
function readJSON(k,fb){try{var v=localStorage.getItem(k);return v?JSON.parse(v):fb}catch(e){return fb}}
function writeJSON(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){alert('No se pudo guardar la información en este dispositivo.');return false}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function auth(){return readJSON(AUTH,null)}
function isAdmin(){var a=auth();if(!a)return false;var r=String(a.role||'').toLowerCase();return !r||r.indexOf('admin')>=0||r.indexOf('super')>=0}
function ensure(){var x=readJSON(KEY,{});x.organization=x.organization||{name:'',code:'',status:'Activa'};x.subscription=x.subscription||{plan:'Prueba',status:'Prueba',start:'',renewal:''};x.modules=x.modules||{clinical:true,templates:true,medications:true,reports:true,cloud:true,billing:false};x.users=Array.isArray(x.users)?x.users:[];x.companies=Array.isArray(x.companies)?x.companies:[];if(x.organization.name&&!x.companies.some(function(c){return c.name===x.organization.name}))x.companies.unshift({id:'c-main',name:x.organization.name,code:x.organization.code||'',status:x.organization.status||'Activa'});return x}
function writeAdmin(x){return writeJSON(KEY,x)}
function state(){var s=readJSON(STORE,{patients:[]});s.patients=Array.isArray(s.patients)?s.patients:[];return s}
function writeState(s){return writeJSON(STORE,s)}
function companyNames(x){var a=(x.companies||[]).filter(function(c){return c.status!=='Inactiva'}).map(function(c){return c.name}).filter(Boolean);if(x.organization.name&&a.indexOf(x.organization.name)<0)a.unshift(x.organization.name);return a}
function style(){if(document.getElementById('ntAdminCenterStyle'))return;var s=document.createElement('style');s.id='ntAdminCenterStyle';s.textContent='#admincenterPage .nt-admin-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}#admincenterPage .nt-admin-span2{grid-column:span 2}#admincenterPage .nt-admin-note{background:#fff8e9;border:1px solid #eadcb8;color:#6b5924;border-radius:12px;padding:12px;margin:12px 0}#admincenterPage .nt-admin-summary{display:flex;justify-content:space-between;gap:12px;align-items:center;background:#eef7f7;border:1px solid #d5e8e9;border-radius:14px;padding:14px}#ntUserTable td,#ntUserTable th,#ntPatientCompanyTable td,#ntPatientCompanyTable th{vertical-align:middle}.nt-user-off{opacity:.55}.nt-company-pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef6f7;border:1px solid #d6e7e9;font-size:11px;font-weight:800}@media(max-width:620px){#admincenterPage .nt-admin-grid{grid-template-columns:1fr}#admincenterPage .nt-admin-span2{grid-column:span 1}}';document.head.appendChild(s)}
function addCompanyToNewPatientForm(){var f=document.getElementById('newPatientForm');if(!f||f.querySelector('[name="company"]'))return;var x=ensure(),names=companyNames(x),statusField=f.querySelector('[name="status"]');var div=document.createElement('div');div.className='field';div.innerHTML='<label>Compañía *</label><select name="company" required><option value="">Seleccione</option>'+names.map(function(n){return '<option>'+esc(n)+'</option>'}).join('')+'</select>';if(statusField&&statusField.parentNode)f.insertBefore(div,statusField.parentNode);else f.appendChild(div)}
function add(){if(document.getElementById('admincenterPage'))return;style();addCompanyToNewPatientForm();var auditBtn=document.querySelector('.navbtn[data-page="audit"]'),side=document.querySelector('.side');if(!side)return;var b=document.createElement('button');b.className='navbtn admin-only';b.dataset.page='admincenter';b.textContent='🛠️ Administración';if(auditBtn)side.insertBefore(b,auditBtn);else side.appendChild(b);var main=document.querySelector('main.main');if(!main)return;var sec=document.createElement('section');sec.id='admincenterPage';sec.className='hidden';sec.innerHTML='<div class="pagehead"><div><h2>Centro de Administración <span class="admin-lock-note">🔒 Solo Superadministrador</span></h2><div class="muted">Compañías, pacientes, usuarios, permisos, membresía y módulos.</div></div></div><div class="card">'+
'<h3>Compañías / Organizaciones</h3><div class="nt-admin-grid"><div class="field"><label>Nombre</label><input id="ntCompanyName" placeholder="Nombre de la compañía"></div><div class="field"><label>Código</label><input id="ntCompanyCode" placeholder="Ej. NT-001"></div><div class="field"><label>Estado</label><select id="ntCompanyStatus"><option>Activa</option><option>Prueba</option><option>Suspendida</option><option>Inactiva</option></select></div></div><div class="row" style="justify-content:flex-end;margin-top:12px"><button class="btn primary" id="ntAddCompany">Añadir compañía</button></div><div class="tablewrap" style="margin-top:12px"><table id="ntCompanyTable"><thead><tr><th>Compañía</th><th>Código</th><th>Estado</th><th></th></tr></thead><tbody></tbody></table></div><hr>'+
'<h3>Pacientes asignados por compañía</h3><div class="nt-admin-note"><strong>Regla:</strong> cada paciente pertenece a una compañía. El Superadministrador puede ver y reasignar todos los pacientes. La asignación queda guardada dentro del expediente del paciente.</div><div class="row"><input id="ntPatientCompanySearch" placeholder="Buscar paciente por nombre o MRN" style="flex:1;min-width:220px"><select id="ntPatientCompanyFilter" style="max-width:260px"><option value="">Todas las compañías</option></select></div><div class="tablewrap" style="margin-top:12px"><table id="ntPatientCompanyTable"><thead><tr><th>Paciente</th><th>MRN</th><th>Compañía asignada</th><th>Acción</th></tr></thead><tbody></tbody></table></div><hr>'+
'<h3>Usuarios por compañía y permisos</h3><div class="nt-admin-grid"><div class="field"><label>Nombre del usuario</label><input id="ntUserName"></div><div class="field"><label>Usuario de acceso</label><input id="ntUserLogin"></div><div class="field"><label>Compañía</label><select id="ntUserCompany"></select></div><div class="field"><label>Rol</label><select id="ntUserRole"><option>Administrador de Compañía</option><option>Enfermería</option><option>Clínico</option><option>Solo lectura</option></select></div><div class="field"><label>Passcode temporero</label><input id="ntUserTempPass" type="password"></div><div class="field"><label>Estado</label><select id="ntUserStatus"><option>Activo</option><option>Inactivo</option></select></div></div><div class="row" style="justify-content:flex-end;margin-top:12px"><button class="btn primary" id="ntAddUser">Añadir usuario</button></div><div class="tablewrap" style="margin-top:12px"><table id="ntUserTable"><thead><tr><th>Usuario</th><th>Compañía</th><th>Rol</th><th>Estado</th><th></th></tr></thead><tbody></tbody></table></div><hr>'+
'<h3>Membresía / Suscripción</h3><div class="nt-admin-grid"><div class="field"><label>Plan</label><select id="ntAdminPlan"><option>Prueba</option><option>Individual</option><option>Professional</option><option>Clinic</option><option>Enterprise</option></select></div><div class="field"><label>Estado</label><select id="ntAdminSubStatus"><option>Activa</option><option>Prueba</option><option>Vencida</option><option>Suspendida</option></select></div><div class="field"><label>Fecha de inicio</label><input type="date" id="ntAdminSubStart"></div><div class="field"><label>Próxima renovación</label><input type="date" id="ntAdminSubRenewal"></div></div><div class="row" style="justify-content:flex-end;margin-top:12px"><button class="btn primary" id="ntAdminSaveSub">Guardar membresía</button></div><hr>'+
'<h3>Módulos habilitados</h3><div class="checkgrid" id="ntAdminModules"><label class="checkitem"><input type="checkbox" data-module="clinical"> Expediente clínico</label><label class="checkitem"><input type="checkbox" data-module="templates"> Plantillas clínicas</label><label class="checkitem"><input type="checkbox" data-module="medications"> Alertas de medicamentos</label><label class="checkitem"><input type="checkbox" data-module="reports"> Reportes y analítica</label><label class="checkitem"><input type="checkbox" data-module="cloud"> Sincronización / nube</label><label class="checkitem"><input type="checkbox" data-module="billing"> Membresía / facturación</label></div><div class="row" style="justify-content:flex-end;margin-top:12px"><button class="btn secondary" id="ntAdminSaveModules">Guardar módulos</button></div><hr><div id="ntAdminSummary" class="nt-admin-summary"></div></div>';main.appendChild(sec);
function show(){if(!isAdmin()){alert('Acceso exclusivo del Superadministrador.');return}document.querySelectorAll('main.main > section').forEach(function(x){x.classList.add('hidden')});sec.classList.remove('hidden');document.querySelectorAll('.navbtn').forEach(function(x){x.classList.toggle('active',x===b)});render()}
b.onclick=show;document.querySelectorAll('.navbtn:not([data-page="admincenter"])').forEach(function(x){x.addEventListener('click',function(){sec.classList.add('hidden');addCompanyToNewPatientForm()})});
document.getElementById('ntAddCompany').onclick=function(){var x=ensure(),name=document.getElementById('ntCompanyName').value.trim(),code=document.getElementById('ntCompanyCode').value.trim(),status=document.getElementById('ntCompanyStatus').value;if(!name){alert('Escriba el nombre de la compañía.');return}if(x.companies.some(function(c){return c.name.toLowerCase()===name.toLowerCase()})){alert('Esa compañía ya existe.');return}x.companies.push({id:'c'+Date.now(),name:name,code:code,status:status});if(!x.organization.name)x.organization={name:name,code:code,status:status};if(writeAdmin(x)){document.getElementById('ntCompanyName').value='';document.getElementById('ntCompanyCode').value='';render();addCompanyToNewPatientForm()}};
document.getElementById('ntCompanyTable').onclick=function(e){var btn=e.target.closest('button[data-company-action]');if(!btn)return;var x=ensure(),id=btn.dataset.id,c=x.companies.find(function(z){return z.id===id});if(!c)return;if(btn.dataset.companyAction==='toggle')c.status=c.status==='Activa'?'Inactiva':'Activa';if(btn.dataset.companyAction==='delete'){var st=state(),used=st.patients.some(function(p){return p.company===c.name})||x.users.some(function(u){return u.company===c.name});if(used){alert('No puede eliminar una compañía con pacientes o usuarios asignados. Reasigne primero.');return}if(!confirm('¿Eliminar esta compañía?'))return;x.companies=x.companies.filter(function(z){return z.id!==id})}writeAdmin(x);render()};
document.getElementById('ntPatientCompanySearch').oninput=renderPatients;document.getElementById('ntPatientCompanyFilter').onchange=renderPatients;
document.getElementById('ntPatientCompanyTable').onchange=function(e){var sel=e.target.closest('select[data-patient-id]');if(!sel)return;sel.dataset.dirty='1'};
document.getElementById('ntPatientCompanyTable').onclick=function(e){var btn=e.target.closest('button[data-patient-save]');if(!btn)return;var s=state(),p=s.patients.find(function(z){return z.id===btn.dataset.patientSave}),sel=document.querySelector('select[data-patient-id="'+CSS.escape(btn.dataset.patientSave)+'"]');if(!p||!sel)return;p.company=sel.value;if(writeState(s)){btn.textContent='Guardado ✓';setTimeout(function(){btn.textContent='Guardar'},1200);renderPatients();alert('Compañía asignada. La asignación se aplicará completamente al recargar NurseTrack.')}};
document.getElementById('ntAddUser').onclick=function(){var x=ensure(),name=document.getElementById('ntUserName').value.trim(),login=document.getElementById('ntUserLogin').value.trim(),company=document.getElementById('ntUserCompany').value,role=document.getElementById('ntUserRole').value,temp=document.getElementById('ntUserTempPass').value,status=document.getElementById('ntUserStatus').value;if(!name||!login||!company){alert('Complete nombre, usuario y compañía.');return}if(x.users.some(function(u){return String(u.login).toLowerCase()===login.toLowerCase()})){alert('Ese usuario ya existe.');return}x.users.push({id:'u'+Date.now(),name:name,login:login,company:company,role:role,status:status,mustChangePassword:true,tempPassSet:!!temp,permissions:role==='Administrador de Compañía'?['Usuarios de su compañía','Pacientes de su compañía','Datos clínicos','Reportes de su compañía']:role==='Solo lectura'?['Ver pacientes','Ver datos clínicos']:['Pacientes de su compañía','Documentación clínica','Visitas']});if(writeAdmin(x)){['ntUserName','ntUserLogin','ntUserTempPass'].forEach(function(id){document.getElementById(id).value=''});render();alert('Usuario añadido.')}};
document.getElementById('ntUserTable').onclick=function(e){var btn=e.target.closest('button[data-user-action]');if(!btn)return;var x=ensure(),u=x.users.find(function(z){return z.id===btn.dataset.id});if(!u)return;if(btn.dataset.userAction==='toggle')u.status=u.status==='Activo'?'Inactivo':'Activo';if(btn.dataset.userAction==='delete'){if(!confirm('¿Eliminar este usuario?'))return;x.users=x.users.filter(function(z){return z.id!==u.id})}writeAdmin(x);render()};
document.getElementById('ntAdminSaveSub').onclick=function(){var x=ensure();x.subscription={plan:document.getElementById('ntAdminPlan').value,status:document.getElementById('ntAdminSubStatus').value,start:document.getElementById('ntAdminSubStart').value,renewal:document.getElementById('ntAdminSubRenewal').value};if(writeAdmin(x)){render();alert('Membresía guardada.')}};
document.getElementById('ntAdminSaveModules').onclick=function(){var x=ensure();document.querySelectorAll('#ntAdminModules input[data-module]').forEach(function(cb){x.modules[cb.dataset.module]=cb.checked});if(writeAdmin(x)){render();alert('Módulos guardados.')}};render()}
function renderCompanies(){var x=ensure(),tb=document.querySelector('#ntCompanyTable tbody');if(tb)tb.innerHTML=x.companies.length?x.companies.map(function(c){return '<tr><td><strong>'+esc(c.name)+'</strong></td><td>'+esc(c.code||'—')+'</td><td>'+esc(c.status)+'</td><td><button class="btn small secondary" data-company-action="toggle" data-id="'+esc(c.id)+'">'+(c.status==='Activa'?'Desactivar':'Activar')+'</button> <button class="btn small danger" data-company-action="delete" data-id="'+esc(c.id)+'">Eliminar</button></td></tr>'}).join(''):'<tr><td colspan="4" class="muted">No hay compañías creadas.</td></tr>';var names=companyNames(x),us=document.getElementById('ntUserCompany'),pf=document.getElementById('ntPatientCompanyFilter');if(us)us.innerHTML='<option value="">Seleccione</option>'+names.map(function(n){return '<option>'+esc(n)+'</option>'}).join('');if(pf){var cur=pf.value;pf.innerHTML='<option value="">Todas las compañías</option>'+names.map(function(n){return '<option>'+esc(n)+'</option>'}).join('');pf.value=cur}}
function renderPatients(){var x=ensure(),s=state(),names=companyNames(x),q=(document.getElementById('ntPatientCompanySearch')||{}).value||'',f=(document.getElementById('ntPatientCompanyFilter')||{}).value||'';q=q.toLowerCase();var rows=s.patients.filter(function(p){var hit=((p.firstName||'')+' '+(p.lastName||'')+' '+(p.mrn||'')).toLowerCase().indexOf(q)>=0;return hit&&(!f||(p.company||'')===f)}),tb=document.querySelector('#ntPatientCompanyTable tbody');if(!tb)return;tb.innerHTML=rows.length?rows.map(function(p){var opts='<option value="">Sin asignar</option>'+names.map(function(n){return '<option '+((p.company||'')===n?'selected':'')+'>'+esc(n)+'</option>'}).join('');return '<tr><td><strong>'+esc(((p.firstName||'')+' '+(p.lastName||'')).trim()||'—')+'</strong></td><td>'+esc(p.mrn||'—')+'</td><td><select data-patient-id="'+esc(p.id)+'">'+opts+'</select></td><td><button class="btn small primary" data-patient-save="'+esc(p.id)+'">Guardar</button></td></tr>'}).join(''):'<tr><td colspan="4" class="muted">No se encontraron pacientes.</td></tr>'}
function render(){var x=ensure(),s=x.subscription,m=x.modules;renderCompanies();renderPatients();var tb=document.querySelector('#ntUserTable tbody');if(tb)tb.innerHTML=x.users.length?x.users.map(function(u){return '<tr class="'+(u.status==='Activo'?'':'nt-user-off')+'"><td><strong>'+esc(u.name)+'</strong><br><small>'+esc(u.login)+'</small></td><td>'+esc(u.company)+'</td><td><strong>'+esc(u.role)+'</strong></td><td>'+esc(u.status)+'</td><td><button class="btn small secondary" data-user-action="toggle" data-id="'+esc(u.id)+'">'+(u.status==='Activo'?'Desactivar':'Activar')+'</button> <button class="btn small danger" data-user-action="delete" data-id="'+esc(u.id)+'">Eliminar</button></td></tr>'}).join(''):'<tr><td colspan="5" class="muted">No hay usuarios creados todavía.</td></tr>';var set=function(id,v){var e=document.getElementById(id);if(e)e.value=v||''};set('ntAdminPlan',s.plan||'Prueba');set('ntAdminSubStatus',s.status||'Prueba');set('ntAdminSubStart',s.start);set('ntAdminSubRenewal',s.renewal);document.querySelectorAll('#ntAdminModules input[data-module]').forEach(function(cb){cb.checked=m[cb.dataset.module]!==false});var q=document.getElementById('ntAdminSummary'),st=state(),assigned=st.patients.filter(function(p){return !!p.company}).length;if(q)q.innerHTML='<div><strong>NurseTrack Clinical</strong><div class="muted" style="margin-top:4px">Compañías: '+x.companies.length+' · Usuarios: '+x.users.length+' · Pacientes asignados: '+assigned+'/'+st.patients.length+'</div></div><span class="pill closed">Superadministrador</span>';addCompanyToNewPatientForm()}
function init(){addCompanyToNewPatientForm();if(!isAdmin())return;add()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
