(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const client=()=>window.NURSETRACK_CLOUD_CLIENT;
const perms=()=>window.NurseTrackPermissions;
function can(k){const p=perms();return !p||!p.ready||p.isSuper||p.can(k)}
function companyId(){return window.NURSETRACK_COMPANY_CONTEXT&&window.NURSETRACK_COMPANY_CONTEXT.companyId||localStorage.getItem('nursetrack_company_id')||null}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]))}
function fmt(v){if(!v)return'—';try{return new Intl.DateTimeFormat('es-PR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch(_){return String(v)}}
function localInput(v){const d=v?new Date(v):new Date();const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)}
let dialog,rows=[],patients=[];
function style(){if($('#ntAppointmentsStyle'))return;const s=document.createElement('style');s.id='ntAppointmentsStyle';s.textContent=`#ntAppointmentsDialog{width:min(1080px,calc(100% - 20px));max-height:calc(100vh - 20px)}.ntApptGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.ntApptCard{border:1px solid #dbe6ea;border-radius:14px;padding:12px;background:#fff}.ntApptCard h4{margin:0 0 6px}.ntApptMeta{font-size:12px;color:#6b7d85;line-height:1.45}.ntApptActions{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.ntApptForm{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.ntApptForm .span2{grid-column:span 2}@media(max-width:760px){.ntApptGrid,.ntApptForm{grid-template-columns:1fr}.ntApptForm .span2{grid-column:span 1}}`;document.head.appendChild(s)}
function shell(){if(dialog)return;style();dialog=document.createElement('dialog');dialog.id='ntAppointmentsDialog';dialog.innerHTML=`<div class="dialogbody"><div class="dialoghead"><div><h2>📅 Citas y recordatorios</h2><div class="muted">Agenda por compañía · llegada · atendido · no-show · SMS/email</div></div><button class="btn secondary" data-close>✕</button></div><div class="row"><input id="ntApptDate" type="date" style="max-width:180px"><button class="btn secondary" id="ntApptRefresh">Actualizar</button><button class="btn primary" id="ntApptNew">+ Nueva cita</button></div><div id="ntApptList" style="margin-top:14px"></div><hr><form id="ntApptForm" class="ntApptForm hidden"><div class="field"><label>Paciente</label><select name="patient_id"><option value="">— Seleccionar —</option></select></div><div class="field"><label>Fecha y hora *</label><input name="appointment_at" type="datetime-local" required></div><div class="field"><label>Tipo de visita</label><input name="visit_type" placeholder="Seguimiento, laboratorio, médico..."></div><div class="field"><label>Proveedor</label><input name="provider_name"></div><div class="field"><label>Lugar</label><input name="location_name"></div><div class="field"><label>Duración (min)</label><input name="duration_minutes" type="number" min="5" step="5" value="30"></div><label class="checkitem"><input name="reminder_sms" type="checkbox"> SMS</label><label class="checkitem"><input name="reminder_email" type="checkbox"> Email</label><div class="field span2"><label>Notas</label><textarea name="notes" rows="2"></textarea></div><div class="span2 row" style="justify-content:flex-end"><button type="button" class="btn secondary" id="ntApptCancel">Cancelar</button><button class="btn primary">Guardar cita</button></div></form></div>`;document.body.appendChild(dialog);dialog.querySelector('[data-close]').onclick=()=>dialog.close();$('#ntApptRefresh').onclick=load;$('#ntApptNew').onclick=()=>edit();$('#ntApptCancel').onclick=()=>$('#ntApptForm').classList.add('hidden');$('#ntApptDate').value=new Date().toISOString().slice(0,10);$('#ntApptForm').onsubmit=save;}
async function loadPatients(){const c=client(),cid=companyId();if(!c||!cid)return;const {data,error}=await c.from('nursetrack_patients_v2').select('id,mrn,first_name,last_name,phone,email,status').eq('company_id',cid).is('deleted_at',null).order('last_name').limit(5000);if(error)throw error;patients=data||[];const sel=$('#ntApptForm [name="patient_id"]');if(sel)sel.innerHTML='<option value="">— Seleccionar —</option>'+patients.map(p=>`<option value="${p.id}">${esc((p.last_name||'')+', '+(p.first_name||''))} · ${esc(p.mrn||'sin MRN')}</option>`).join('')}
async function load(){shell();const c=client(),cid=companyId();if(!c||!cid){$('#ntApptList').innerHTML='<div class="notice">No hay compañía activa.</div>';return}try{await loadPatients();const day=$('#ntApptDate').value||new Date().toISOString().slice(0,10),start=day+'T00:00:00',end=day+'T23:59:59';const {data,error}=await c.from('nursetrack_appointments').select('*').eq('company_id',cid).gte('appointment_at',start).lte('appointment_at',end).order('appointment_at');if(error)throw error;rows=data||[];render()}catch(e){$('#ntApptList').innerHTML='<div class="notice">'+esc(e.message||e)+'</div>'}}
function patientName(id){const p=patients.find(x=>x.id===id);return p?((p.first_name||'')+' '+(p.last_name||'')).trim():'Paciente no vinculado'}
function label(s){return ({scheduled:'Programada',confirmed:'Confirmada',checked_in:'Llegó / registrado',in_progress:'En atención',completed:'Atendido',no_show:'No-show',cancelled:'Cancelada'}[s]||s||'—')}
function render(){const host=$('#ntApptList');if(!rows.length){host.innerHTML='<div class="empty">No hay citas para esta fecha.</div>';return}host.innerHTML='<div class="ntApptGrid">'+rows.map(a=>`<article class="ntApptCard" data-id="${a.id}"><h4>${esc(patientName(a.patient_id))}</h4><div class="ntApptMeta"><strong>${esc(fmt(a.appointment_at))}</strong><br>${esc(a.visit_type||'Cita')} · ${esc(a.provider_name||'Sin proveedor')}<br>Estado: <strong>${esc(label(a.status))}</strong><br>Recordatorio: ${esc(a.reminder_status||'not_sent')}${a.reminder_sms?' · SMS':''}${a.reminder_email?' · Email':''}</div><div class="ntApptActions">${can('appointments.edit')?`<button class="btn small secondary" data-edit>Editar</button><button class="btn small secondary" data-status="checked_in">Llegó</button><button class="btn small secondary" data-status="completed">Atendido</button><button class="btn small secondary" data-status="no_show">No-show</button><button class="btn small secondary" data-queue>Encolar recordatorio</button>`:''}</div></article>`).join('')+'</div>';host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(rows.find(x=>x.id===b.closest('[data-id]').dataset.id)));host.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>setStatus(b.closest('[data-id]').dataset.id,b.dataset.status));host.querySelectorAll('[data-queue]').forEach(b=>b.onclick=()=>queueReminder(b.closest('[data-id]').dataset.id))}
function edit(a){if(!can('appointments.edit'))return;const f=$('#ntApptForm');f.reset();f.dataset.id=a&&a.id||'';f.classList.remove('hidden');f.elements.patient_id.value=a&&a.patient_id||'';f.elements.appointment_at.value=localInput(a&&a.appointment_at);f.elements.visit_type.value=a&&a.visit_type||'';f.elements.provider_name.value=a&&a.provider_name||'';f.elements.location_name.value=a&&a.location_name||'';f.elements.duration_minutes.value=a&&a.duration_minutes||30;f.elements.reminder_sms.checked=!!(a&&a.reminder_sms);f.elements.reminder_email.checked=!!(a&&a.reminder_email);f.elements.notes.value=a&&a.notes||'';f.scrollIntoView({behavior:'smooth',block:'center'})}
async function save(e){e.preventDefault();if(!can('appointments.edit'))return;const c=client(),cid=companyId(),f=e.target,fd=new FormData(f),payload={company_id:cid,patient_id:fd.get('patient_id')||null,appointment_at:new Date(fd.get('appointment_at')).toISOString(),duration_minutes:Number(fd.get('duration_minutes')||30),visit_type:fd.get('visit_type')||null,provider_name:fd.get('provider_name')||null,location_name:fd.get('location_name')||null,reminder_sms:f.elements.reminder_sms.checked,reminder_email:f.elements.reminder_email.checked,notes:fd.get('notes')||null,updated_at:new Date().toISOString()};try{let q=f.dataset.id?c.from('nursetrack_appointments').update(payload).eq('id',f.dataset.id).eq('company_id',cid):c.from('nursetrack_appointments').insert(payload);const {error}=await q;if(error)throw error;f.classList.add('hidden');await load()}catch(err){alert(err.message||String(err))}}
async function setStatus(id,status){const c=client(),cid=companyId();const {error}=await c.from('nursetrack_appointments').update({status,updated_at:new Date().toISOString()}).eq('id',id).eq('company_id',cid);if(error)return alert(error.message);load()}
async function queueReminder(id){const a=rows.find(x=>x.id===id);if(!a)return;if(!a.reminder_sms&&!a.reminder_email)return alert('Active SMS y/o email en la cita antes de encolar el recordatorio.');const c=client(),cid=companyId();const {error}=await c.from('nursetrack_appointments').update({reminder_status:'queued',updated_at:new Date().toISOString()}).eq('id',id).eq('company_id',cid);if(error)return alert(error.message);document.dispatchEvent(new CustomEvent('nursetrack:appointment-reminder-queued',{detail:{appointmentId:id}}));load()}
async function open(){shell();dialog.showModal();await load()}
window.NURSETRACK_APPOINTMENTS={open,load};
})();