(function(){'use strict';
var BILL='nursetrack_billing_v1',STORE='nursetrack_clinical_v21';
function read(k,fb){try{var v=localStorage.getItem(k);return v?JSON.parse(v):fb}catch(e){return fb}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v));try{window.dispatchEvent(new StorageEvent('storage',{key:k,newValue:JSON.stringify(v)}))}catch(e){}return true}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function lang(){return (document.documentElement.lang||'es').toLowerCase().indexOf('en')===0?'en':'es'}
function T(es,en){return lang()==='en'?en:es}
function patientName(p){return [p.firstName,p.middleName,p.lastName,p.secondLastName].filter(Boolean).join(' ')||p.name||p.fullName||''}
function getPatients(){return (read(STORE,{patients:[]}).patients||[])}
function getBill(){var d=read(BILL,{claims:[]});d.claims=Array.isArray(d.claims)?d.claims:[];return d}
function claimFor(d,pid,dos){return d.claims.find(function(c){return c.patientId===pid&&c.dos===dos&&['draft','ready'].indexOf(c.status)>=0})||null}
function addLabLine(x){var d=getBill(),c=claimFor(d,x.patientId,x.dos),p=getPatients().find(function(q){return q.id===x.patientId});if(!c){c={id:'clm'+Date.now(),patientId:x.patientId,patient:p?patientName(p):'',payer:x.payer||'',memberId:x.memberId||'',group:x.group||'',provider:x.orderingProvider||'',npi:x.orderingNpi||'',dos:x.dos,pos:x.pos||'11',icd10:x.icd10||'',cpt:'',modifier:'',units:1,charge:0,authorization:x.authorization||'',status:'draft',payment:0,adjustment:0,createdAt:new Date().toISOString(),lines:[]};d.claims.push(c)}
 c.lines=Array.isArray(c.lines)?c.lines:[];c.lines.push({id:'ln'+Date.now(),source:'laboratory',service:T('Laboratorio / toma de muestra','Laboratory / specimen collection'),cpt:x.cpt||'',hcpcs:x.hcpcs||'',loinc:x.loinc||'',description:x.description||'',units:Number(x.units)||1,charge:Number(x.charge)||0,specimen:x.specimen||'',collectedAt:x.collectedAt||new Date().toISOString(),performedBy:x.performedBy||''});
 c.charge=(Number(c.charge)||0)+(Number(x.charge)||0);c.updatedAt=new Date().toISOString();c.status='draft';write(BILL,d);if(typeof window.ntBillingRender==='function')try{window.ntBillingRender()}catch(e){};return c}
window.ntAddLabCharge=addLabLine;
function install(){if(document.getElementById('labBillingPage'))return;var side=document.querySelector('.side'),main=document.querySelector('main.main');if(!side||!main)return setTimeout(install,250);var nav=document.createElement('button');nav.className='navbtn';nav.textContent=T('🧪 Laboratorio','🧪 Laboratory');side.appendChild(nav);var sec=document.createElement('section');sec.id='labBillingPage';sec.className='hidden';sec.innerHTML='<div class="pagehead"><div><h2>'+T('Laboratorio y facturación integrada','Laboratory & integrated billing')+'</h2><div class="muted">'+T('Registrar la toma de muestra y añadirla a la misma reclamación del encuentro.','Register specimen collection and add it to the same encounter claim.')+'</div></div></div><div class="card"><div class="formgrid"><div class="field"><label>'+T('Paciente','Patient')+' *</label><select id="lbPat"><option value="">—</option></select></div><div class="field"><label>'+T('Fecha de servicio','Date of service')+' *</label><input id="lbDos" type="date"></div><div class="field"><label>'+T('Código CPT','CPT code')+'</label><input id="lbCpt" placeholder="CPT"></div><div class="field"><label>'+T('Código HCPCS','HCPCS code')+'</label><input id="lbHcpcs" placeholder="HCPCS"></div><div class="field"><label>LOINC</label><input id="lbLoinc" placeholder="LOINC"></div><div class="field"><label>'+T('Descripción del laboratorio / toma','Lab / collection description')+' *</label><input id="lbDesc"></div><div class="field"><label>'+T('Tipo de muestra','Specimen type')+'</label><input id="lbSpec"></div><div class="field"><label>'+T('Unidades','Units')+'</label><input id="lbUnits" type="number" min="1" value="1"></div><div class="field"><label>'+T('Cargo','Charge')+' *</label><input id="lbCharge" type="number" step="0.01"></div><div class="field"><label>'+T('Personal que tomó la muestra','Collected by')+'</label><input id="lbBy"></div><div class="field"><label>'+T('ICD-10 relacionado','Related ICD-10')+'</label><input id="lbIcd"></div><div class="field"><label>'+T('Autorización','Authorization')+'</label><input id="lbAuth"></div></div><div class="dialogactions"><button class="btn primary" id="lbSave">'+T('Registrar muestra y añadir a factura','Register specimen & add to claim')+'</button></div><div id="lbMsg" class="muted" style="margin-top:10px"></div></div><div class="card"><strong>'+T('Catálogo de códigos','Code catalog')+'</strong><div class="muted" style="margin-top:6px">'+T('NurseTrack admite CPT, HCPCS y LOINC. El catálogo CPT completo requiere licencia de AMA para mostrarse dentro del sistema; HCPCS y LOINC pueden conectarse desde sus fuentes autorizadas.','NurseTrack supports CPT, HCPCS and LOINC. Displaying the complete CPT catalog inside the system requires an AMA license; HCPCS and LOINC can be connected from their authorized sources.')+'</div></div>';main.appendChild(sec);
 function fill(){var s=document.getElementById('lbPat');s.innerHTML='<option value="">—</option>'+getPatients().map(function(p){return '<option value="'+esc(p.id)+'">'+esc(patientName(p))+'</option>'}).join('');document.getElementById('lbDos').value=new Date().toISOString().slice(0,10)}
 nav.onclick=function(){document.querySelectorAll('main.main > section').forEach(function(x){x.classList.add('hidden')});sec.classList.remove('hidden');document.querySelectorAll('.navbtn').forEach(function(x){x.classList.toggle('active',x===nav)});fill()};
 document.getElementById('lbSave').onclick=function(){var pid=document.getElementById('lbPat').value,dos=document.getElementById('lbDos').value,desc=document.getElementById('lbDesc').value.trim(),charge=document.getElementById('lbCharge').value;if(!pid||!dos||!desc||charge===''){document.getElementById('lbMsg').textContent=T('Complete paciente, fecha, descripción y cargo.','Complete patient, date, description and charge.');return}var c=addLabLine({patientId:pid,dos:dos,cpt:document.getElementById('lbCpt').value.trim(),hcpcs:document.getElementById('lbHcpcs').value.trim(),loinc:document.getElementById('lbLoinc').value.trim(),description:desc,specimen:document.getElementById('lbSpec').value.trim(),units:document.getElementById('lbUnits').value,charge:charge,performedBy:document.getElementById('lbBy').value.trim(),icd10:document.getElementById('lbIcd').value.trim(),authorization:document.getElementById('lbAuth').value.trim()});document.getElementById('lbMsg').textContent=T('Muestra registrada. El cargo quedó unido a la reclamación del mismo encuentro.','Specimen registered. The charge was added to the same encounter claim.');document.getElementById('lbDesc').value='';document.getElementById('lbCharge').value='';};fill()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();