(function(){'use strict';
var KEY='nursetrack_medication_safety_v1',STORE='nursetrack_clinical_v21';
var I={es:{nav:'💊 Seguridad de Medicamentos',title:'Seguridad de Medicamentos',sub:'Reconciliación · duplicidad · sustancias controladas · historial de dispensación',patient:'Paciente',drug:'Medicamento / ingrediente activo',brand:'Marca',dose:'Dosis',qty:'Cantidad',pharmacy:'Farmacia',prescriber:'Prescriptor',date:'Fecha de dispensación',controlled:'Sustancia controlada',add:'Registrar dispensación',check:'Verificar nueva orden',history:'Historial registrado',result:'Resultado de verificación',clear:'Sin alerta de duplicidad en los datos disponibles.',dup:'⚠️ Posible duplicidad de medicamento',multiPharm:'⚠️ El mismo medicamento aparece en más de una farmacia.',multiRx:'⚠️ El mismo medicamento aparece con más de un prescriptor.',recent:'Dispensación reciente encontrada:',review:'Revisión requerida antes de continuar.',continue:'Continuar con justificación',cancel:'Cancelar orden',reason:'Justificación clínica',save:'Guardar decisión',external:'Consulta externa PDMP/HIE',notConnected:'Conector externo aún no configurado. La verificación actual usa los datos disponibles en NurseTrack.',audit:'Historial de decisiones',noPatient:'Seleccione un paciente.',required:'Complete medicamento, farmacia y fecha.'},en:{nav:'💊 Medication Safety',title:'Medication Safety',sub:'Reconciliation · duplication · controlled substances · dispensing history',patient:'Patient',drug:'Medication / active ingredient',brand:'Brand',dose:'Dose',qty:'Quantity',pharmacy:'Pharmacy',prescriber:'Prescriber',date:'Dispense date',controlled:'Controlled substance',add:'Record dispensing',check:'Check new order',history:'Recorded history',result:'Verification result',clear:'No duplication alert found in the available data.',dup:'⚠️ Possible medication duplication',multiPharm:'⚠️ The same medication appears at more than one pharmacy.',multiRx:'⚠️ The same medication appears with more than one prescriber.',recent:'Recent dispensing found:',review:'Review required before proceeding.',continue:'Continue with justification',cancel:'Cancel order',reason:'Clinical justification',save:'Save decision',external:'External PDMP/HIE lookup',notConnected:'External connector is not configured yet. Current verification uses data available in NurseTrack.',audit:'Decision history',noPatient:'Select a patient.',required:'Complete medication, pharmacy and date.'}};
function lang(){return (document.documentElement.lang||'es').toLowerCase().indexOf('en')===0?'en':'es'}function T(k){return I[lang()][k]||k}
function read(k,fb){try{var v=localStorage.getItem(k);return v?JSON.parse(v):fb}catch(e){return fb}}function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){return false}}
function db(){var d=read(KEY,{dispenses:[],decisions:[]});d.dispenses=Array.isArray(d.dispenses)?d.dispenses:[];d.decisions=Array.isArray(d.decisions)?d.decisions:[];return d}
function state(){return read(STORE,{patients:[]})}function pname(p){return [p.firstName,p.middleName,p.lastName,p.secondLastName].filter(Boolean).join(' ')||p.name||p.fullName||''}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function selectedPatient(){var id='';try{id=window.state&&window.state.selectedPatientId||''}catch(e){}if(!id){var a=document.querySelector('[data-patient-id].active,[data-id].active');if(a)id=a.dataset.patientId||a.dataset.id||''}return (state().patients||[]).find(function(p){return p.id===id})||null}
function daysBetween(a,b){var x=new Date(a),y=new Date(b);if(isNaN(x)||isNaN(y))return 9999;return Math.abs(Math.floor((y-x)/86400000))}
async function checkOrder(x){x=x||{};var d=db(),pid=x.patientId||'',drug=norm(x.activeIngredient||x.drug||x.medication||''),today=x.date||new Date().toISOString().slice(0,10);var matches=d.dispenses.filter(function(r){return r.patientId===pid&&norm(r.activeIngredient||r.drug)===drug});var recent=matches.filter(function(r){return daysBetween(r.date,today)<=45});var pharmacies=[...new Set(recent.map(function(r){return norm(r.pharmacy)}).filter(Boolean))],prescribers=[...new Set(recent.map(function(r){return norm(r.prescriber)}).filter(Boolean))];var result={ok:recent.length===0,alerts:[],matches:recent,external:null};if(recent.length)result.alerts.push(T('dup'));if(pharmacies.length>1)result.alerts.push(T('multiPharm'));if(prescribers.length>1)result.alerts.push(T('multiRx'));if(typeof window.ntMedicationExternalLookup==='function'){try{result.external=await window.ntMedicationExternalLookup(x);if(result.external&&result.external.alerts&&result.external.alerts.length){result.alerts=result.alerts.concat(result.external.alerts);result.ok=false}}catch(e){result.external={error:true}}}return result}
window.ntMedicationSafetyCheck=checkOrder;
window.ntMedicationRecordDispense=function(x){x=x||{};var d=db();x.id=x.id||'med'+Date.now();x.createdAt=x.createdAt||new Date().toISOString();d.dispenses.push(x);write(KEY,d);window.dispatchEvent(new Event('nursetrack:medication-safety-updated'));return x};
window.ntMedicationRecordDecision=function(x){x=x||{};var d=db();x.id=x.id||'dec'+Date.now();x.createdAt=x.createdAt||new Date().toISOString();d.decisions.push(x);write(KEY,d);window.dispatchEvent(new Event('nursetrack:medication-safety-updated'));return x};
function style(){if(document.getElementById('ntMedSafetyStyle'))return;var s=document.createElement('style');s.id='ntMedSafetyStyle';s.textContent='#medSafetyPage .grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.med-alert{padding:12px;border:1px solid #e0b96c;border-radius:10px;background:#fff8e8;margin:8px 0}.med-ok{padding:12px;border:1px solid #acd4b6;border-radius:10px;background:#f4fff7;margin:8px 0}.med-row{padding:8px 0;border-top:1px solid var(--line)}@media(max-width:800px){#medSafetyPage .grid{grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
function add(){if(document.getElementById('medSafetyPage'))return;style();var side=document.querySelector('.side'),main=document.querySelector('main.main');if(!side||!main)return;var nav=document.createElement('button');nav.className='navbtn';nav.textContent=T('nav');side.appendChild(nav);var sec=document.createElement('section');sec.id='medSafetyPage';sec.className='hidden';sec.innerHTML='<div class="pagehead"><div><h2>'+T('title')+'</h2><div class="muted">'+T('sub')+'</div></div></div><div class="card"><h3>'+T('add')+'</h3><div class="grid"><select id="msPatient"></select><input id="msDrug" placeholder="'+T('drug')+'"><input id="msBrand" placeholder="'+T('brand')+'"><input id="msDose" placeholder="'+T('dose')+'"><input id="msQty" placeholder="'+T('qty')+'"><input id="msPharmacy" placeholder="'+T('pharmacy')+'"><input id="msPrescriber" placeholder="'+T('prescriber')+'"><input type="date" id="msDate"><label><input type="checkbox" id="msControlled"> '+T('controlled')+'</label></div><div class="row"><button class="btn primary" id="msSave">'+T('add')+'</button></div></div><div class="card"><h3>'+T('check')+'</h3><div class="grid"><select id="msCheckPatient"></select><input id="msCheckDrug" placeholder="'+T('drug')+'"><input type="date" id="msCheckDate"></div><div class="row"><button class="btn primary" id="msCheck">'+T('check')+'</button></div><div id="msResult"></div><div class="muted" style="margin-top:8px">'+T('notConnected')+'</div></div><div class="card"><h3>'+T('history')+'</h3><div id="msHistory"></div></div><div class="card"><h3>'+T('audit')+'</h3><div id="msAudit"></div></div>';main.appendChild(sec);
function show(){document.querySelectorAll('main.main > section').forEach(function(x){x.classList.add('hidden')});sec.classList.remove('hidden');document.querySelectorAll('.navbtn').forEach(function(x){x.classList.toggle('active',x===nav)});render()}nav.onclick=show;
document.getElementById('msDate').value=new Date().toISOString().slice(0,10);document.getElementById('msCheckDate').value=new Date().toISOString().slice(0,10);
document.getElementById('msSave').onclick=function(){var pid=document.getElementById('msPatient').value,drug=document.getElementById('msDrug').value.trim(),ph=document.getElementById('msPharmacy').value.trim(),dt=document.getElementById('msDate').value;if(!pid){alert(T('noPatient'));return}if(!drug||!ph||!dt){alert(T('required'));return}window.ntMedicationRecordDispense({patientId:pid,drug:drug,activeIngredient:drug,brand:document.getElementById('msBrand').value.trim(),dose:document.getElementById('msDose').value.trim(),quantity:document.getElementById('msQty').value.trim(),pharmacy:ph,prescriber:document.getElementById('msPrescriber').value.trim(),date:dt,controlled:document.getElementById('msControlled').checked});render()};
document.getElementById('msCheck').onclick=async function(){var pid=document.getElementById('msCheckPatient').value,drug=document.getElementById('msCheckDrug').value.trim(),dt=document.getElementById('msCheckDate').value;if(!pid){alert(T('noPatient'));return}var res=await checkOrder({patientId:pid,drug:drug,date:dt});var box=document.getElementById('msResult');if(res.ok){box.className='med-ok';box.innerHTML=T('clear');return}box.className='med-alert';box.innerHTML='<strong>'+T('review')+'</strong><br>'+res.alerts.map(function(a){return '• '+a}).join('<br>')+(res.matches.length?'<div style="margin-top:8px">'+T('recent')+' '+res.matches.map(function(m){return (m.date||'')+' · '+(m.pharmacy||'')+' · '+(m.prescriber||'')}).join('<br>')+'</div>':'')+'<div class="grid" style="margin-top:10px"><input id="msReason" placeholder="'+T('reason')+'"><button class="btn secondary" id="msCancelDecision">'+T('cancel')+'</button><button class="btn primary" id="msContinueDecision">'+T('continue')+'</button></div>';document.getElementById('msCancelDecision').onclick=function(){window.ntMedicationRecordDecision({patientId:pid,drug:drug,date:dt,decision:'cancelled',reason:'',alerts:res.alerts});box.innerHTML=T('cancel')};document.getElementById('msContinueDecision').onclick=function(){var reason=(document.getElementById('msReason')||{}).value||'';if(!reason.trim()){alert(T('reason'));return}window.ntMedicationRecordDecision({patientId:pid,drug:drug,date:dt,decision:'continued',reason:reason.trim(),alerts:res.alerts});box.innerHTML=T('save')+' ✓'}};
function render(){var s=state(),opts='<option value="">'+T('patient')+'</option>'+(s.patients||[]).map(function(p){return '<option value="'+p.id+'">'+pname(p)+'</option>'}).join('');document.getElementById('msPatient').innerHTML=opts;document.getElementById('msCheckPatient').innerHTML=opts;var p=selectedPatient();if(p){document.getElementById('msPatient').value=p.id;document.getElementById('msCheckPatient').value=p.id}var d=db();document.getElementById('msHistory').innerHTML=d.dispenses.slice().reverse().map(function(x){var pp=(s.patients||[]).find(function(p){return p.id===x.patientId});return '<div class="med-row"><strong>'+pname(pp||{})+'</strong> · '+(x.drug||'')+' · '+(x.date||'')+' · '+(x.pharmacy||'')+(x.controlled?' · '+T('controlled'):'')+'</div>'}).join('')||'<div class="muted">—</div>';document.getElementById('msAudit').innerHTML=d.decisions.slice().reverse().map(function(x){var pp=(s.patients||[]).find(function(p){return p.id===x.patientId});return '<div class="med-row"><strong>'+pname(pp||{})+'</strong> · '+(x.drug||'')+' · '+(x.decision||'')+(x.reason?' · '+x.reason:'')+'</div>'}).join('')||'<div class="muted">—</div>'}
window.addEventListener('nursetrack:medication-safety-updated',render);render()}
function init(){add();var o=new MutationObserver(add);o.observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();