(function(){
'use strict';
if(window.__NT_REPORTS_RUNTIME)return;window.__NT_REPORTS_RUNTIME=1;
const client=window.NURSETRACK_CLOUD_CLIENT;if(!client)return;
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cid=()=>window.NURSETRACK_COMPANY_CONTEXT&&window.NURSETRACK_COMPANY_CONTEXT.companyId||'';
const can=()=>{const p=window.NurseTrackPermissions;return !p||!p.ready||p.isSuper||p.can('reports.view')};
const iso=d=>d.toISOString().slice(0,10);
function monthRange(){const n=new Date(),a=new Date(n.getFullYear(),n.getMonth(),1),b=new Date(n.getFullYear(),n.getMonth()+1,0);return[iso(a),iso(b)]}
async function count(table,build){let q=client.from(table).select('*',{count:'exact',head:true});q=build(q);const r=await q;if(r.error)throw r.error;return r.count||0}
async function metrics(from,to){const company=cid();if(!company)throw new Error('Seleccione una compañía.');const [patients,visits,completed,phq,phqPositive,abnormalPending,appointments,noShows,membersExpiring]=await Promise.all([
 count('nursetrack_patients_v2',q=>q.eq('company_id',company).is('deleted_at',null).eq('status','active')),
 count('nursetrack_visits',q=>q.eq('company_id',company).is('deleted_at',null).gte('visit_date',from).lte('visit_date',to)),
 count('nursetrack_visits',q=>q.eq('company_id',company).is('deleted_at',null).gte('visit_date',from).lte('visit_date',to).in('status',['provider_complete','closed'])),
 count('nursetrack_phq9',q=>q.eq('company_id',company).gte('screening_date',from).lte('screening_date',to)),
 count('nursetrack_phq9',q=>q.eq('company_id',company).gte('screening_date',from).lte('screening_date',to).gte('total_score',5)),
 count('nursetrack_labs',q=>q.eq('company_id',company).eq('abnormal',true).neq('review_status','reviewed')),
 count('nursetrack_appointments',q=>q.eq('company_id',company).gte('appointment_at',from+'T00:00:00').lte('appointment_at',to+'T23:59:59')),
 count('nursetrack_appointments',q=>q.eq('company_id',company).gte('appointment_at',from+'T00:00:00').lte('appointment_at',to+'T23:59:59').in('status',['no_show','absent','missed'])),
 count('nursetrack_membership_effective_status',q=>q.eq('company_id',company).in('effective_status',['expiring','expiring_soon','grace_period']))
]);return{patients,visits,completed,phq,phqPositive,abnormalPending,appointments,noShows,membersExpiring}}
function card(label,value,sub){return '<div class="ntRptCard"><div class="ntRptLabel">'+esc(label)+'</div><div class="ntRptValue">'+esc(value)+'</div>'+(sub?'<div class="ntRptSub">'+esc(sub)+'</div>':'')+'</div>'}
function styles(){if($('#ntRptStyle'))return;const s=document.createElement('style');s.id='ntRptStyle';s.textContent='#ntReportsDialog{width:min(1050px,96vw);max-width:1050px;border:0;border-radius:18px;padding:0;box-shadow:0 22px 70px rgba(0,0,0,.25)}.ntRptBody{padding:18px}.ntRptHead{display:flex;justify-content:space-between;gap:12px;align-items:center}.ntRptFilters{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}.ntRptFilters input{padding:8px;border:1px solid #ccdadd;border-radius:8px}.ntRptGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.ntRptCard{border:1px solid #dce8eb;border-radius:14px;padding:14px;background:#fff}.ntRptLabel{font-size:12px;color:#60737b}.ntRptValue{font-size:28px;font-weight:800;margin-top:4px}.ntRptSub{font-size:12px;color:#60737b;margin-top:4px}@media(max-width:760px){.ntRptGrid{grid-template-columns:1fr 1fr}}@media(max-width:480px){.ntRptGrid{grid-template-columns:1fr}}@media print{body>*:not(#ntReportsPrint){display:none!important}#ntReportsPrint{display:block!important}}';document.head.appendChild(s)}
async function open(){if(!can())return alert('No tiene permiso para ver reportes.');styles();let d=$('#ntReportsDialog');if(d)d.remove();d=document.createElement('dialog');d.id='ntReportsDialog';const [from,to]=monthRange();d.innerHTML='<div class="ntRptBody"><div class="ntRptHead"><div><h2 style="margin:0">📊 Reportes NurseTrack</h2><div class="muted">Datos de la compañía activa</div></div><button class="btn secondary ntRptClose">✕</button></div><div class="ntRptFilters"><label>Desde <input id="ntRptFrom" type="date" value="'+from+'"></label><label>Hasta <input id="ntRptTo" type="date" value="'+to+'"></label><button class="btn primary" id="ntRptRefresh">Actualizar</button><button class="btn secondary" id="ntRptPrint">Imprimir</button></div><div id="ntRptStatus" class="muted">Cargando…</div><div id="ntRptGrid" class="ntRptGrid" style="margin-top:12px"></div></div>';document.body.appendChild(d);d.querySelector('.ntRptClose').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.showModal();
 async function refresh(){const f=$('#ntRptFrom',d).value,t=$('#ntRptTo',d).value;if(!f||!t||f>t)return alert('Revise el rango de fechas.');$('#ntRptStatus',d).textContent='Actualizando…';try{const m=await metrics(f,t),pct=m.visits?Math.round(m.completed/m.visits*100):0;$('#ntRptGrid',d).innerHTML=card('Pacientes activos',m.patients,'Censo actual')+card('Visitas',m.visits,f+' → '+t)+card('Visitas completadas',m.completed,pct+'% del periodo')+card('PHQ-9 completados',m.phq,'Periodo seleccionado')+card('PHQ-9 ≥ 5',m.phqPositive,'Requieren seguimiento según flujo clínico')+card('Labs anormales pendientes',m.abnormalPending,'Pendientes de revisión')+card('Citas',m.appointments,'Periodo seleccionado')+card('Ausencias / no-show',m.noShows,'Según estado de cita')+card('Membresías por vencer/gracia',m.membersExpiring,'Estado efectivo actual');$('#ntRptStatus',d).textContent='Actualizado '+new Date().toLocaleString('es-PR')}catch(e){$('#ntRptStatus',d).textContent='Error: '+(e.message||String(e))}}
 $('#ntRptRefresh',d).onclick=refresh;$('#ntRptPrint',d).onclick=()=>{const host=document.createElement('div');host.id='ntReportsPrint';host.innerHTML='<h2>Reporte NurseTrack</h2><p>'+esc($('#ntRptFrom',d).value)+' → '+esc($('#ntRptTo',d).value)+'</p>'+$('#ntRptGrid',d).outerHTML;document.body.appendChild(host);window.print();setTimeout(()=>host.remove(),500)};refresh();
}
window.NURSETRACK_REPORTS={open,metrics};
})();