const NT_SW_VERSION='20260909-stable174';
const STATIC_CACHE='nursetrack-static-'+NT_SW_VERSION;
const CRITICAL=/\/(?:app-safe6\.html|login-safe6\.html|safe6-supabase-loader\.js|supabase-config\.js|nursetrack-version\.json|index\.html\.html)(?:$|[?#])/i;
self.addEventListener('install',event=>{self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const names=await caches.keys();await Promise.all(names.filter(n=>n.startsWith('nursetrack-')&&n!==STATIC_CACHE).map(n=>caches.delete(n)));await self.clients.claim()})())});
function isStatic(u){return /\.(?:js|css|svg|png|jpg|jpeg|webp|woff2?)(?:$|\?)/i.test(u.pathname+u.search)}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const u=new URL(req.url);if(u.origin!==self.location.origin)return;
if(CRITICAL.test(u.pathname+u.search)){event.respondWith(fetch(req,{cache:'no-store',headers:req.headers}).catch(()=>new Response('NurseTrack requiere conexión para cargar la versión actual.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}})));return}
if(isStatic(u)){event.respondWith((async()=>{const cache=await caches.open(STATIC_CACHE);try{const fresh=await fetch(req,{cache:'no-store'});if(fresh&&fresh.ok)event.waitUntil(cache.put(req,fresh.clone()));return fresh}catch(e){const hit=await cache.match(req);if(hit)return hit;return new Response('NurseTrack requiere conexión para descargar este módulo.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}})}})());return}
event.respondWith(fetch(req,{cache:'no-store'}).catch(async()=>{const cache=await caches.open(STATIC_CACHE),hit=await cache.match(req);return hit||new Response('NurseTrack requiere conexión para esta función.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}})}))});