(function(){
'use strict';
if(window.__NT_STATIONS_RUNTIME)return;window.__NT_STATIONS_RUNTIME=1;
const client=window.NURSETRACK_CLOUD_CLIENT;if(!client)return;
const $=(s,r=document)=>r.querySelector(s),esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cid=()=>window.NURSETRACK_COMPANY_CONTEXT&&window.NURSETRACK_COMPANY_CONTEXT.companyId||'';
const perms=()=>window.NurseTrackPermissions;
const can=k=>!perms()||!perms().ready||perms().isSuper||perms().can(k);
let users=[];
async function loadUsers(){const company=cid();if(!company)return[];const cu=await client.from('nursetrack_company_users').select('user_id').eq('company_id',company).eq('active',true);if(cu.error)throw cu.error;const ids=(cu.data||[]).map(x=>x.user_id);if(!ids.length)return[];const pr=await client.from('nursetrack_profiles').select('user_id,username,role,active').in('user_id',ids).eq('active',true);if(pr.error)throw pr.error;users=pr.data||[];return users}
function opts(selected){return '<option value="">— Sin asignar —</option>'+users.map(u=>'<option value="'+esc(u.user_id)+'" '+(u.user_id===selected?'selected':'')+'>'+esc(u.username||u.role||u.user_id)+'</option>').join('')}
async function rows(date){const r=await client.from('nursetrack_station_assignments').select('*').eq('company_id',cid()).eq('assignment_date',date).order('station_no');if(r.error)throw r.error;return r.data||[]}
async function saveRow(station,date,host){if(!can('stations.manage'))return alert('No tiene permiso para administrar estaciones.');const pu=$('[data-primary="'+station+'"]',host),bu=$('[data-backup="'+station+'"]',host),status=$('[data-status="'+station+'"]',host),reason=$('[data-reason="'+station+'"]',host),notes=$('[data-notes="'+station+'"]',host);const primary=users.find(x=>x.user_id===pu.value),backup=users.find(x=>x.user_id===bu.value);const payload={company_id:cid(),assignment_date:date,station_no:station,primary_user_id:pu.value||null,primary_name:primary&&primary.username||'',backup_user_id:bu.value||null,backup_name:backup&&backup.username||'',status:status.value,coverage_reason:reason.value.trim()||null,notes:notes.value.trim()||null,updated_at:new Date().toISOString()};const r=await client.from('nursetrack_station_assignments').upsert(payload,{onConflict:'company_id,assignment_date,station_no'});if(r.error)return alert(r.error.message);alert('Estación '+station+' guardada.');}
function stationCard(n,row,edit){return '<section class="sectionbox"><h3>Estación '+n+'</h3><div class="formgrid"><div class="field"><label>Enfermera titular</label><select data-primary="'+n+'" '+(edit?'':'disabled')+'>'+opts(row&&row.primary_user_id)+'</select></div><div class="field"><label>Respaldo</label><select data-backup="'+n+'" '+(edit?'':'disabled')+'>'+opts(row&&row.backup_user_id)+'</select></div><div class="field"><label>Estado</label><select data-status="'+n+'" '+(edit?'':'disabled')+'><option value="assigned" '+((row&&row.status)==='assigned'?'selected':'')+'>Asignada</option><option value="covered" '+((row&&row.status)==='covered'?'selected':'')+'>Cubierta por respaldo</option><option value="closed" '+((row&&row.status)==='closed'?'selected':'')+'>Cerrada</option></select></div><div class="field"><label>Motivo de cobertura</label><input data-reason="'+n+'" value="'+esc(row&&row.coverage_reason||'')+'" '+(edit?'':'disabled')+' placeholder="Ausencia, vacaciones, ajuste"></div><div class="field span2"><label>Notas</label><input data-notes="'+n+'" value="'+esc(row&&row.notes||'')+'" '+(edit?'':'disabled')+'></div></div>'+(edit?'<button class="btn primary ntStationSave" data-station="'+n+'" style="margin-top:10px">Guardar estación '+n+'</button>':'')+'</section>'}
async function open(){if(!can('stations.view')&&!can('stations.manage'))return alert('No tiene permiso para ver estaciones.');if(!cid())return alert('Seleccione una compañía.');const d=document.createElement('dialog');d.style.width='min(900px,96vw)';d.innerHTML='<div class="dialogbody"><div class="dialoghead"><div><h2>🩺 Cobertura de estaciones</h2><div class="muted">Tres estaciones operativas · titular y respaldo</div></div><button class="btn secondary x">✕</button></div><div class="row"><label>Fecha <input type="date" id="ntStationDate"></label><button class="btn secondary" id="ntStationReload">Cargar</button></div><div id="ntStationBody" style="margin-top:12px">Cargando…</div></div>';document.body.appendChild(d);d.querySelector('.x').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());const date=$('#ntStationDate',d);date.value=new Date().toISOString().slice(0,10);async function render(){const body=$('#ntStationBody',d);body.textContent='Cargando…';try{await loadUsers();const rr=await rows(date.value),m=new Map(rr.map(x=>[Number(x.station_no),x])),edit=can('stations.manage');body.innerHTML=[1,2,3].map(n=>stationCard(n,m.get(n),edit)).join('')+'<div class="notice" style="margin-top:12px">Si una titular falta, seleccione su respaldo y cambie el estado a <b>Cubierta por respaldo</b>. Registro puede consultar esta misma vista sin editar.</div>';body.querySelectorAll('.ntStationSave').forEach(b=>b.onclick=()=>saveRow(Number(b.dataset.station),date.value,d))}catch(e){body.innerHTML='<div class="notice">'+esc(e.message||String(e))+'</div>'}}$('#ntStationReload',d).onclick=render;date.onchange=render;d.showModal();render()}
window.NURSETRACK_STATIONS={open};
})();