(function(){'use strict';
if(window.__ntVisitAgendaLoaded)return;window.__ntVisitAgendaLoaded=true;
var KEY='nursetrack_visit_agenda_v295';
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return []}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function esc(v){return String(v||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function reminder(x){return 'Recordatorio de cita de NurseTrack Clinical: su cita está programada para '+x.date+' a las '+x.time+'. Tipo de visita: '+x.type+'. Si necesita cambiar su cita, comuníquese con la clínica.'}
function messageFor(x){return String(x.message||'').trim()||reminder(x)}
function E(t,a,h){var n=document.createElement(t);Object.keys(a||{}).forEach(function(k){if(k==='class')n.className=a[k];else n.setAttribute(k,a[k])});if(h!=null)n.innerHTML=h;return n}
function init(){
  if(document.getElementById('agendaPage'))return;
  var side=document.querySelector('.side'),main=document.querySelector('main.main');if(!side||!main)return;
  var s=E('section',{id:'agendaPage',class:'hidden'},'<div class="pagehead"><div><h2>📅 Agenda de visitas, estados y alertas</h2><div class="muted">Seguimiento operativo de visitas clínicas.</div></div><button class="btn primary" id="ntaNew">+ Nueva visita</button></div><div class="metrics"><div class="metric"><span>Programadas</span><strong id="ntaScheduled">0</strong></div><div class="metric"><span>En espera</span><strong id="ntaWaiting">0</strong></div><div class="metric"><span>En atención</span><strong id="ntaCare">0</strong></div><div class="metric"><span>Completadas</span><strong id="ntaDone">0</strong></div><div class="metric"><span>No Show</span><strong id="ntaNoShow">0</strong></div><div class="metric"><span>Alertas</span><strong id="ntaAlerts">0</strong></div></div><div class="card"><div class="row"><input id="ntaSearch" placeholder="Buscar paciente / MRN" style="flex:1"><select id="ntaFilter" style="max-width:220px"><option value="">Todos los estados</option><option>Programada</option><option>En espera</option><option>En atención</option><option>Completada</option><option>No Show</option><option>Cancelada</option></select></div><div class="muted" style="margin-top:10px;font-size:12px">Escriba o edite el mensaje antes de enviarlo. Si lo deja vacío, NurseTrack usará el recordatorio automático.</div><div class="tablewrap" style="margin-top:12px"><table><thead><tr><th>Fecha/hora</th><th>Paciente</th><th>Tipo</th><th>Estado</th><th>Alerta</th><th style="min-width:300px">Mensaje del recordatorio</th><th>Enviar</th><th></th></tr></thead><tbody id="ntaBody"></tbody></table></div></div>');
  main.appendChild(s);
  var b=E('button',{class:'navbtn','data-page':'agenda'},'📅 Agenda y Alertas');side.insertBefore(b,side.querySelector('h3')||null);
  function render(){
    var search=document.getElementById('ntaSearch'),filter=document.getElementById('ntaFilter');if(!search||!filter)return;
    var a=read(),q=search.value.toLowerCase(),f=filter.value,counts={Programada:0,'En espera':0,'En atención':0,Completada:0,'No Show':0},alerts=0,rows='';
    a.forEach(function(x,i){if(counts[x.status]!=null)counts[x.status]++;if(x.alert)alerts++;if((q&&!((String(x.patient||'')+' '+String(x.mrn||'')).toLowerCase().includes(q)))||(f&&x.status!==f))return;var draft=x.message!=null?x.message:reminder(x);rows+='<tr><td>'+esc(x.date)+' '+esc(x.time)+'</td><td><strong>'+esc(x.patient)+'</strong><br><small>'+esc(x.mrn)+'</small></td><td>'+esc(x.type)+'</td><td><select data-i="'+i+'" class="ntaStatus"><option'+(x.status==='Programada'?' selected':'')+'>Programada</option><option'+(x.status==='En espera'?' selected':'')+'>En espera</option><option'+(x.status==='En atención'?' selected':'')+'>En atención</option><option'+(x.status==='Completada'?' selected':'')+'>Completada</option><option'+(x.status==='No Show'?' selected':'')+'>No Show</option><option'+(x.status==='Cancelada'?' selected':'')+'>Cancelada</option></select></td><td>'+(x.alert?'⚠️ '+esc(x.alert):'—')+'</td><td><textarea class="ntaMessage" data-i="'+i+'" rows="4" style="min-width:280px;resize:vertical">'+esc(draft)+'</textarea></td><td><button class="btn small ntaSms" data-i="'+i+'">📱 Texto</button> <button class="btn small ntaEmail" data-i="'+i+'">✉️ Email</button></td><td><button class="btn danger small ntaDel" data-i="'+i+'">Eliminar</button></td></tr>'});
    document.getElementById('ntaBody').innerHTML=rows||'<tr><td colspan="8" class="empty">No hay visitas.</td></tr>';
    document.getElementById('ntaScheduled').textContent=counts.Programada;document.getElementById('ntaWaiting').textContent=counts['En espera'];document.getElementById('ntaCare').textContent=counts['En atención'];document.getElementById('ntaDone').textContent=counts.Completada;document.getElementById('ntaNoShow').textContent=counts['No Show'];document.getElementById('ntaAlerts').textContent=alerts;
    document.querySelectorAll('.ntaStatus').forEach(function(e){e.onchange=function(){var a=read();if(!a[this.dataset.i])return;a[this.dataset.i].status=this.value;save(a);render()}});
    document.querySelectorAll('.ntaMessage').forEach(function(e){e.onchange=function(){var a=read();if(!a[this.dataset.i])return;a[this.dataset.i].message=this.value;save(a)}});
    document.querySelectorAll('.ntaSms').forEach(function(e){e.onclick=function(){var a=read(),x=a[this.dataset.i];if(!x)return;var ta=document.querySelector('.ntaMessage[data-i="'+this.dataset.i+'"]');if(ta){x.message=ta.value;save(a)}var phone=x.phone||prompt('Teléfono móvil del paciente:')||'';if(!phone)return;if(!x.phone){x.phone=phone;save(a)}location.href='sms:'+phone+'?body='+encodeURIComponent(messageFor(x))}});
    document.querySelectorAll('.ntaEmail').forEach(function(e){e.onclick=function(){var a=read(),x=a[this.dataset.i];if(!x)return;var ta=document.querySelector('.ntaMessage[data-i="'+this.dataset.i+'"]');if(ta){x.message=ta.value;save(a)}var email=x.email||prompt('Correo electrónico del paciente:')||'';if(!email)return;if(!x.email){x.email=email;save(a)}location.href='mailto:'+encodeURIComponent(email)+'?subject='+encodeURIComponent('Recordatorio de cita')+'&body='+encodeURIComponent(messageFor(x))}});
    document.querySelectorAll('.ntaDel').forEach(function(e){e.onclick=function(){var a=read();a.splice(Number(this.dataset.i),1);save(a);render()}})
  }
  var old=window.showPage;
  window.showPage=function(n){document.querySelectorAll('main.main>section').forEach(function(x){x.classList.toggle('hidden',x.id!==n+'Page')});document.querySelectorAll('.navbtn').forEach(function(x){x.classList.toggle('active',x.dataset.page===n)});if(n!=='agenda'&&typeof old==='function')old(n);if(n==='agenda')render()};
  b.onclick=function(){window.showPage&&window.showPage('agenda')};
  document.getElementById('ntaSearch').oninput=render;document.getElementById('ntaFilter').onchange=render;
  document.getElementById('ntaNew').onclick=function(){var patient=prompt('Nombre del paciente:');if(!patient)return;var mrn=prompt('MRN / número de paciente:')||'',phone=prompt('Teléfono móvil (opcional):')||'',email=prompt('Email (opcional):')||'',date=prompt('Fecha (AAAA-MM-DD):',new Date().toISOString().slice(0,10))||'',time=prompt('Hora (ej. 09:00):')||'',type=prompt('Tipo de visita:','Enfermería')||'Enfermería',alertText=prompt('Alerta o seguimiento pendiente (opcional):')||'';var x={patient:patient,mrn:mrn,phone:phone,email:email,date:date,time:time,type:type,status:'Programada',alert:alertText};x.message=reminder(x);var a=read();a.push(x);save(a);render()};
  render()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();