(function(){
'use strict';
if(window.__NT_V4_ASSIGNMENTS__) return;
window.__NT_V4_ASSIGNMENTS__=true;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let sb=null,ctx=null,selectedPatient=null,busy=false;
function area(){return $('patientActionArea')}
function addStyles(){if($('ntV4AssignStyle'))return;const s=document.createElement('style');s.id='ntV4AssignStyle';s.textContent='.ntv4-assign-card{background:#fff;border:1px solid #d8e6e8;border-radius:14px;padding:16px;margin-top:12px}.ntv4-assign-grid{display:grid;grid-template-columns:1.2fr 1fr auto;gap:10px;align-items:end}.ntv4-assign-results{display:grid;gap:7px;margin-top:10px}.ntv4-assign-patient{width:100%;border:1px solid #d8e6e8;background:#fff;border-radius:10px;padding:10px;text-align:left}.ntv4-assign-patient.on{border-color:#397f88;background:#f2f9f9}.ntv4-assign-table{width:100%;border-collapse:collapse}.ntv4-assign-table th,.ntv4-assign-table td{padding:9px;border-bottom:1px solid #e5eeee;text-align:left;font-size:13px}.ntv4-assign-actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:760px){.ntv4-assign-grid{grid-template-columns:1fr}}';(document.head||document.documentElement).appendChild(s)}
async function client(){if(sb)return sb;if(typeof window.NT_loadSupabase!=='function')throw new Error('Supabase no disponible');const lib=await window.NT_loadSupabase(),cfg=window.NURSETRACK_SUPABASE||{};sb=lib.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
async function getCtx(){await client();const ses=await sb.auth.getSession(),u=ses?.data?.session?.user;if(!u)throw new Error('Sesión no disponible');let r=await sb.from('nursetrack_company_users').select('company_id').eq('user_id',u.id).eq('active',true).limit(1);let company=r.data?.[0]?.company_id||null;if(!company){let m=await sb.from('nursetrack_account_memberships').select('company_id').eq('user_id',u.id).eq('status','active').limit(1);company=m.data?.[0]?.company_id||null}if(!company)throw new Error('No hay compañía activa');ctx={user:u,company};return ctx}
async function rpc(name,args){await client();const r=await sb.rpc(name,args);if(r.error)throw r.error;return r.data}
async function loadUsers(){const c=ctx||await getCtx();return await rpc('nursetrack_assignment_users_v4',{p_company_id:c.company})||[]}
async function loadAssignments(){const c=ctx||await getCtx();return await rpc('nursetrack_list_patient_assignments_v4',{p_company_id:c.company})||[]}
async function searchPatients(q){const c=ctx||await getCtx();q=String(q||'').trim();if(!q)return[];let r=await sb.from('nursetrack_patients_v2').select('id,mrn,first_name,middle_name,last_name,date_of_birth').eq('company_id',c.company).is('deleted_at',null).or(`mrn.ilike.%${q.replace(/[%_,()]/g,'')}%,first_name.ilike.%${q.replace(/[%_,()]/g,'')}%,last_name.ilike.%${q.replace(/[%_,()]/g,'')}%`).order('last_name').limit(20);if(r.error)throw r.error;return r.data||[]}
function pname(p){return [p?.first_name,p?.middle_name,p?.last_name].filter(Boolean).join(' ')||'Paciente'}
function ensureModuleButton(){const grid=document.querySelector('#modulesPanel .module-grid');if(!grid||[...grid.querySelectorAll('.module strong')].some(x=>x.textContent.trim().toLowerCase()==='asignaciones'))return;const b=document.createElement('button');b.className='module';b.innerHTML='<strong>Asignaciones</strong><small>Asignar pacientes a usuarios de la compañía</small>';grid.appendChild(b)}
function renderAssignments(rows){if(!rows.length)return '<div class="notice">No hay pacientes asignados actualmente.</div>';return `<table class="ntv4-assign-table"><thead><tr><th>Paciente</th><th>Expediente</th><th>Asignado a</th><th>Fecha</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.patient_name||'')}</td><td>${esc(r.patient_mrn||'')}</td><td>${esc(r.assignee_name||'')}</td><td>${esc((r.assigned_at||'').slice(0,10))}</td><td><button class="btn light ntv4-unassign" data-patient="${esc(r.patient_uuid)}" data-user="${esc(r.user_id)}">Quitar</button></td></tr>`).join('')}</tbody></table>`}
async function open(){try{addStyles();selectedPatient=null;const c=await getCtx(),[users,rows]=await Promise.all([loadUsers(),loadAssignments()]);area().innerHTML=`<div class="ntv4-assign-card"><h3>👥 Asignación de pacientes</h3><p>Solo muestra usuarios activos de la compañía actual. La escritura se valida en el servidor.</p><div class="ntv4-assign-grid"><div><label>Buscar paciente</label><input id="ntv4AssignSearch" placeholder="Nombre o expediente"></div><div><label>Asignar a</label><select id="ntv4AssignUser"><option value="">Seleccione usuario</option>${users.map(u=>`<option value="${esc(u.user_id)}">${esc(u.full_name)}${u.role_code?` · ${esc(u.role_code)}`:''}</option>`).join('')}</select></div><button class="btn" id="ntv4AssignDo" disabled>Asignar</button></div><div id="ntv4AssignSearchStatus" class="status"></div><div id="ntv4AssignResults" class="ntv4-assign-results"></div><div id="ntv4AssignStatus" class="status"></div></div><div class="ntv4-assign-card"><h3>Asignaciones actuales</h3><div id="ntv4AssignTable">${renderAssignments(rows)}</div></div>`;const inp=$('ntv4AssignSearch');let timer=null;inp.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(runSearch,250)});$('ntv4AssignDo').onclick=assignSelected;document.querySelectorAll('.ntv4-unassign').forEach(b=>b.onclick=()=>unassign(b.dataset.patient,b.dataset.user));setTimeout(()=>inp.focus(),0)}catch(e){if(area())area().innerHTML=`<div class="ntv4-assign-card" style="color:#933">${esc(e.message||e)}</div>`}}
async function runSearch(){const q=$('ntv4AssignSearch')?.value||'',out=$('ntv4AssignResults'),st=$('ntv4AssignSearchStatus');selectedPatient=null;$('ntv4AssignDo').disabled=true;if(!q.trim()){out.innerHTML='';st.textContent='';return}try{st.textContent='Buscando…';const rows=await searchPatients(q);st.textContent=rows.length?`${rows.length} resultado(s)`:'Sin resultados';out.innerHTML=rows.map(p=>`<button class="ntv4-assign-patient" data-id="${esc(p.id)}" data-name="${esc(pname(p))}" data-mrn="${esc(p.mrn||'')}"><strong>${esc(pname(p))}</strong><div>Expediente ${esc(p.mrn||'')} ${p.date_of_birth?`· DOB ${esc(p.date_of_birth)}`:''}</div></button>`).join('');out.querySelectorAll('button').forEach(b=>b.onclick=()=>{out.querySelectorAll('button').forEach(x=>x.classList.remove('on'));b.classList.add('on');selectedPatient={id:b.dataset.id,name:b.dataset.name,mrn:b.dataset.mrn};$('ntv4AssignDo').disabled=false})}catch(e){st.textContent=e.message||String(e);st.style.color='#933'}}
async function assignSelected(){if(busy||!selectedPatient)return;const user=$('ntv4AssignUser')?.value,st=$('ntv4AssignStatus');if(!user){st.textContent='Seleccione un usuario.';st.style.color='#933';return}busy=true;try{st.textContent='Asignando…';await rpc('nursetrack_assign_patient_v4',{p_company_id:ctx.company,p_patient_id:selectedPatient.id,p_user_id:user});st.textContent='Paciente asignado.';st.style.color='#216b48';setTimeout(open,300)}catch(e){st.textContent=e.message||String(e);st.style.color='#933'}finally{busy=false}}
async function unassign(patientId,userId){if(busy)return;busy=true;try{await rpc('nursetrack_unassign_patient_v4',{p_company_id:ctx.company,p_patient_id:patientId,p_user_id:userId});setTimeout(open,100)}catch(e){const st=$('ntv4AssignStatus');if(st){st.textContent=e.message||String(e);st.style.color='#933'}}finally{busy=false}}
window.NT_V4_ASSIGNMENTS={open};
ensureModuleButton();let tries=0;const t=setInterval(()=>{ensureModuleButton();if(++tries>40)clearInterval(t)},250);
})();