(function(){
'use strict';
if(window.__NT_V4_AUDIT__) return;
window.__NT_V4_AUDIT__=true;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let sb=null,ctx=null;
function addStyles(){if($('ntV4AuditStyle'))return;const s=document.createElement('style');s.id='ntV4AuditStyle';s.textContent='.ntv4-audit-card{background:#fff;border:1px solid #d8e6e8;border-radius:14px;padding:16px;margin-top:12px}.ntv4-audit-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;align-items:end}.ntv4-audit-table{width:100%;border-collapse:collapse}.ntv4-audit-table th,.ntv4-audit-table td{padding:8px;border-bottom:1px solid #e5eeee;text-align:left;vertical-align:top;font-size:12px}.ntv4-audit-meta{max-width:420px;white-space:pre-wrap;word-break:break-word;color:#566}.ntv4-audit-scroll{overflow:auto;max-height:62vh}@media(max-width:800px){.ntv4-audit-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.ntv4-audit-grid{grid-template-columns:1fr}}';(document.head||document.documentElement).appendChild(s)}
async function client(){if(sb)return sb;if(typeof window.NT_loadSupabase!=='function')throw new Error('Supabase no disponible');const lib=await window.NT_loadSupabase(),cfg=window.NURSETRACK_SUPABASE||{};sb=lib.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
async function context(){await client();const ses=await sb.auth.getSession(),u=ses?.data?.session?.user;if(!u)throw new Error('Sesión no disponible');let r=await sb.from('nursetrack_company_users').select('company_id').eq('user_id',u.id).eq('active',true).limit(1);let company=r.data?.[0]?.company_id||null;if(!company){const m=await sb.from('nursetrack_account_memberships').select('company_id').eq('user_id',u.id).eq('status','active').limit(1);company=m.data?.[0]?.company_id||null}ctx={user:u,company};return ctx}
function globalShell(){['homePanel','modulesPanel','placeholderPanel'].forEach(id=>$(id)?.classList.add('hidden'));$('patientPanel')?.classList.remove('hidden');if($('patientName'))$('patientName').textContent='Auditoría';if($('patientMrn'))$('patientMrn').textContent='';if($('patientDemographics'))$('patientDemographics').innerHTML='';const a=document.querySelector('#patientPanel .actions');if(a)a.style.display='none';if($('newVisitBtn'))$('newVisitBtn').style.display='none';if($('pageTitle'))$('pageTitle').textContent='Auditoría';if($('patientActionArea'))$('patientActionArea').innerHTML=''}
function ensureButton(){const grid=document.querySelector('#modulesPanel .module-grid');if(!grid||[...grid.querySelectorAll('.module strong')].some(x=>x.textContent.trim().toLowerCase()==='auditoría'))return;const b=document.createElement('button');b.className='module';b.innerHTML='<strong>Auditoría</strong><small>Eventos del sistema y actividad administrativa</small>';b.onclick=open;grid.appendChild(b)}
function fmtMeta(v){try{return JSON.stringify(v||{},null,2)}catch{return String(v||'')}}
async function load(){const c=ctx||await context();let q=sb.from('nursetrack_audit_events').select('id,company_id,user_id,action,entity_type,entity_id,patient_id,metadata,occurred_at').order('occurred_at',{ascending:false}).limit(250);if(c.company)q=q.or(`company_id.eq.${c.company},company_id.is.null`);const from=$('ntv4AuditFrom')?.value,to=$('ntv4AuditTo')?.value,act=$('ntv4AuditAction')?.value.trim(),ent=$('ntv4AuditEntity')?.value.trim();if(from)q=q.gte('occurred_at',from+'T00:00:00');if(to)q=q.lte('occurred_at',to+'T23:59:59.999');if(act)q=q.ilike('action','%'+act.replace(/[%_,()]/g,'')+'%');if(ent)q=q.ilike('entity_type','%'+ent.replace(/[%_,()]/g,'')+'%');const r=await q;if(r.error)throw r.error;return r.data||[]}
function table(rows){if(!rows.length)return '<div class="notice">Sin eventos para los filtros seleccionados.</div>';return `<div class="ntv4-audit-scroll"><table class="ntv4-audit-table"><thead><tr><th>Fecha</th><th>Acción</th><th>Entidad</th><th>ID entidad</th><th>Usuario</th><th>Metadata</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(String(x.occurred_at||'').replace('T',' ').slice(0,19))}</td><td>${esc(x.action||'')}</td><td>${esc(x.entity_type||'')}</td><td>${esc(x.entity_id||'')}</td><td>${esc(x.user_id||'')}</td><td><pre class="ntv4-audit-meta">${esc(fmtMeta(x.metadata))}</pre></td></tr>`).join('')}</tbody></table></div>`}
async function refresh(){const st=$('ntv4AuditStatus'),out=$('ntv4AuditRows');try{st.textContent='Cargando…';const rows=await load();out.innerHTML=table(rows);st.textContent=`${rows.length} evento(s) mostrados · máximo 250`;st.style.color='#566'}catch(e){out.innerHTML='';st.textContent=e.message||String(e);st.style.color='#933'}}
async function open(){globalShell();addStyles();try{await context();$('patientActionArea').innerHTML=`<div class="ntv4-audit-card"><h3>🧾 Auditoría</h3><p>Solo lectura. NurseTrack no ofrece borrar eventos desde esta pantalla.</p><div class="ntv4-audit-grid"><div><label>Desde</label><input id="ntv4AuditFrom" type="date"></div><div><label>Hasta</label><input id="ntv4AuditTo" type="date"></div><div><label>Acción</label><input id="ntv4AuditAction" placeholder="save, login, publish..."></div><div><label>Entidad</label><input id="ntv4AuditEntity" placeholder="patient, template..."></div></div><div style="margin-top:10px"><button class="btn" id="ntv4AuditFilter">Aplicar filtros</button></div><div id="ntv4AuditStatus" class="status"></div></div><div class="ntv4-audit-card" id="ntv4AuditRows"></div>`;$('ntv4AuditFilter').onclick=refresh;await refresh()}catch(e){$('patientActionArea').innerHTML=`<div class="ntv4-audit-card" style="color:#933">${esc(e.message||e)}</div>`}}
window.NT_V4_AUDIT={open};
ensureButton();let tries=0;const t=setInterval(()=>{ensureButton();if(++tries>40)clearInterval(t)},250);
})();