(function(){
'use strict';
if(window.__NT_V4_BILLING_ADMIN__) return;
window.__NT_V4_BILLING_ADMIN__=true;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const $=id=>document.getElementById(id);
let sb=null,ctx=null,patient=null,busy=false,profile=null;
function addStyles(){if($('ntV4BAStyle'))return;const s=document.createElement('style');s.id='ntV4BAStyle';s.textContent='.ntv4-bacard{background:#fff;border:1px solid #d8e6e8;border-radius:14px;padding:16px;margin-top:12px}.ntv4-bagrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ntv4-bagrid .full{grid-column:1/-1}.ntv4-batabs,.ntv4-baactions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.ntv4-batabs button.on{background:#397f88;color:#fff}.ntv4-batable{width:100%;border-collapse:collapse}.ntv4-batable th,.ntv4-batable td{padding:8px;border-bottom:1px solid #e5eeee;text-align:left;vertical-align:top;font-size:12px}.ntv4-badge{display:inline-block;padding:3px 7px;border:1px solid #d8e6e8;border-radius:999px;background:#f8fbfb;font-size:11px}.ntv4-searchresults{display:grid;gap:5px;margin-top:6px}.ntv4-searchresults button{padding:8px;border:1px solid #d8e6e8;border-radius:8px;background:#fff;text-align:left}.ntv4-perms{display:grid;grid-template-columns:1fr 1fr;gap:7px}.ntv4-perms label{font-weight:500;margin:0;border:1px solid #e3eeee;border-radius:8px;padding:7px}@media(max-width:760px){.ntv4-bagrid,.ntv4-perms{grid-template-columns:1fr}.ntv4-bagrid .full{grid-column:auto}.ntv4-batable{display:block;overflow:auto}}';(document.head||document.documentElement).appendChild(s)}
async function client(){if(sb)return sb;if(typeof window.NT_loadSupabase!=='function')throw new Error('Supabase no disponible');const lib=await window.NT_loadSupabase(),cfg=window.NURSETRACK_SUPABASE||{};sb=lib.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
async function getCtx(){await client();const ses=await sb.auth.getSession(),u=ses?.data?.session?.user;if(!u)throw new Error('Sesión no disponible');let company=null;const cu=await sb.from('nursetrack_company_users').select('company_id').eq('user_id',u.id).eq('active',true).limit(1);if(cu.data?.[0])company=cu.data[0].company_id;if(!company){const m=await sb.from('nursetrack_account_memberships').select('company_id').eq('user_id',u.id).eq('status','active').limit(1);company=m.data?.[0]?.company_id||null}if(!company)throw new Error('No hay compañía activa');const pr=await sb.from('nursetrack_profiles').select('role,full_name,username,active').eq('user_id',u.id).maybeSingle();profile=pr.data||{};ctx={user:u,company};return ctx}
function mrn(){return ($('patientMrn')?.textContent||'').replace(/^(MRN|Expediente)\s*:?-?\s*/i,'').trim()}
async function getPatient(optional=false){const c=await getCtx(),m=mrn();if(!m){if(optional)return null;throw new Error('Abre un paciente primero')}const r=await sb.from('nursetrack_patients_v2').select('*').eq('company_id',c.company).ilike('mrn',m).is('deleted_at',null).limit(1);if(r.error)throw r.error;patient=r.data?.[0]||null;if(!patient&&!optional)throw new Error('Paciente activo no localizado');return patient}
function pname(p){return [p?.first_name,p?.middle_name,p?.last_name].filter(Boolean).join(' ')||'Paciente'}
function output(html){const a=$('patientActionArea');if(a){a.innerHTML=html;return a}let x=$('ntv4BAStandalone');if(!x){x=document.createElement('div');x.id='ntv4BAStandalone';$('modulesPanel')?.appendChild(x)}x.innerHTML=html;return x}
function today(){return new Date().toISOString().slice(0,10)}
function uuid(){return crypto.randomUUID?crypto.randomUUID():'v4-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
async function billingData(){const c=ctx||await getCtx(),p=patient||await getPatient();const [vis,charges,claims,responses]=await Promise.all([
 sb.from('nursetrack_visits').select('id,visit_date,visit_type,status').eq('company_id',c.company).eq('patient_id',p.id).is('deleted_at',null).order('visit_date',{ascending:false}).limit(30),
 sb.from('nursetrack_service_billing_codes').select('id,visit_id,service_date,status,charge_amount,diagnosis_links,payer_name,client_charge_key,billing_code_id,nursetrack_billing_codes(code,code_system,short_label)').eq('company_id',c.company).eq('patient_id',p.id).order('service_date',{ascending:false}).limit(100),
 sb.from('nursetrack_claims').select('*').eq('company_id',c.company).eq('patient_id',p.id).order('created_at',{ascending:false}).limit(50),
 sb.from('nursetrack_clearinghouse_responses').select('claim_id,transaction_type,response_type,status,code,message,external_reference,payer_claim_control_number,received_at').eq('company_id',c.company).order('received_at',{ascending:false}).limit(50)
 ]);for(const r of [vis,charges,claims,responses])if(r.error)throw r.error;return{visits:vis.data||[],charges:charges.data||[],claims:claims.data||[],responses:responses.data||[]}}
async function openBilling(tab='charges'){try{addStyles();const p=await getPatient(),d=await billingData();output(`<div class="ntv4-bacard"><h3>🧾 Facturación y Clearinghouse</h3><div>${esc(pname(p))} · Expediente ${esc(p.mrn||'')}</div><div class="ntv4-batabs"><button class="btn light ${tab==='charges'?'on':''}" data-btab="charges">Cargos</button><button class="btn light ${tab==='claims'?'on':''}" data-btab="claims">Reclamaciones</button><button class="btn light ${tab==='responses'?'on':''}" data-btab="responses">Clearinghouse</button></div><div id="ntv4BillingBody">${billingBody(tab,d)}</div><div id="ntv4BillingStatus" class="status"></div></div>`);document.querySelectorAll('[data-btab]').forEach(b=>b.onclick=()=>openBilling(b.dataset.btab));bindBilling(tab,d)}catch(e){output(`<div class="ntv4-bacard" style="color:#933">${esc(e.message||e)}</div>`)}}
function visitOptions(d){return d.visits.map(v=>`<option value="${v.id}">${esc(v.visit_date)} · ${esc(v.visit_type||'Visita')} · ${esc(v.status||'')}</option>`).join('')}
function billingBody(tab,d){if(tab==='charges')return `<div class="ntv4-bagrid"><div><label>Visita *</label><select id="ntv4ChargeVisit">${visitOptions(d)}</select></div><div><label>Fecha servicio</label><input id="ntv4ChargeDate" type="date" value="${today()}"></div><div><label>Código HCPCS/CPT *</label><div style="display:flex;gap:6px"><input id="ntv4ChargeCode" placeholder="Código"><button class="btn light" id="ntv4CodeSearch" type="button">Buscar</button></div><div id="ntv4CodeResults" class="ntv4-searchresults"></div></div><div><label>Diagnósticos ICD-10</label><div style="display:flex;gap:6px"><input id="ntv4ChargeDx" placeholder="Ej. B20, I10"><button class="btn light" id="ntv4DxSearch" type="button">Buscar</button></div><div id="ntv4DxResults" class="ntv4-searchresults"></div></div><div><label>Monto</label><input id="ntv4ChargeAmount" type="number" min="0" step="0.01"></div><div><label>Estado</label><select id="ntv4ChargeStatus"><option value="reviewed">Revisado</option><option value="ready_to_bill">Listo para facturar</option><option value="recorded">Registrado</option></select></div><div><label>Pagador</label><input id="ntv4ChargePayer"></div><div class="full"><label>Notas</label><textarea id="ntv4ChargeNotes"></textarea></div></div><div class="ntv4-baactions"><button class="btn" id="ntv4SaveCharge">Guardar cargo</button><button class="btn secondary" id="ntv4CreateClaim">Crear reclamación de la visita</button></div><div class="ntv4-bacard"><h4>Cargos del paciente</h4>${chargeTable(d.charges)}</div><div class="ntv4-bacard" id="ntv4ClaimForm" style="display:none"><h4>Crear reclamación</h4><div class="ntv4-bagrid"><div><label>Pagador</label><input id="ntv4ClaimPayer"></div><div><label>Payer ID</label><input id="ntv4ClaimPayerId"></div><div><label>Member ID</label><input id="ntv4ClaimMember"></div><div><label>Tipo</label><select id="ntv4ClaimType"><option>837P</option></select></div></div><div class="ntv4-baactions"><button class="btn" id="ntv4ConfirmClaim">Confirmar reclamación</button></div></div>`;
if(tab==='claims')return d.claims.length?`<table class="ntv4-batable"><thead><tr><th>Número</th><th>Fecha</th><th>Pagador</th><th>Total</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${d.claims.map(c=>`<tr><td>${esc(c.claim_number||c.id.slice(0,8))}</td><td>${esc(String(c.created_at||'').slice(0,10))}</td><td>${esc(c.payer_name||'')}</td><td>$${Number(c.total_charge||0).toFixed(2)}</td><td><span class="ntv4-badge">${esc(c.status)}</span>${c.denial_code?`<div style="color:#933">${esc(c.denial_code)} ${esc(c.denial_reason||'')}</div>`:''}</td><td><div class="ntv4-baactions">${c.status==='draft'?`<button class="btn light" data-claim-action="validate" data-id="${c.id}">Validar</button><button class="btn light" data-claim-action="ready" data-id="${c.id}">Marcar lista</button>`:''}${c.status==='ready'?`<button class="btn" data-claim-action="queue" data-id="${c.id}">Enviar a cola</button>`:''}</div></td></tr>`).join('')}</tbody></table>`:'<div>No hay reclamaciones.</div>';
return d.responses.length?`<table class="ntv4-batable"><thead><tr><th>Recibido</th><th>Claim</th><th>Transacción</th><th>Estado</th><th>Código / mensaje</th><th>Referencia</th></tr></thead><tbody>${d.responses.map(r=>`<tr><td>${esc(String(r.received_at||'').replace('T',' ').slice(0,16))}</td><td>${esc(String(r.claim_id||'').slice(0,8))}</td><td>${esc(r.transaction_type||r.response_type||'')}</td><td>${esc(r.status||'')}</td><td>${esc([r.code,r.message].filter(Boolean).join(' · '))}</td><td>${esc(r.payer_claim_control_number||r.external_reference||'')}</td></tr>`).join('')}</tbody></table>`:'<div>No hay respuestas de clearinghouse.</div>'}
function chargeTable(a){if(!a.length)return '<div>Sin cargos.</div>';return `<table class="ntv4-batable"><thead><tr><th>Fecha</th><th>Código</th><th>Diagnósticos</th><th>Monto</th><th>Estado</th><th>Pagador</th></tr></thead><tbody>${a.map(x=>`<tr><td>${esc(x.service_date||'')}</td><td>${esc(x.nursetrack_billing_codes?.code_system||'')} ${esc(x.nursetrack_billing_codes?.code||'')}<div>${esc(x.nursetrack_billing_codes?.short_label||'')}</div></td><td>${esc(Array.isArray(x.diagnosis_links)?x.diagnosis_links.map(v=>typeof v==='string'?v:v?.code).filter(Boolean).join(', '):'')}</td><td>$${Number(x.charge_amount||0).toFixed(2)}</td><td>${esc(x.status||'')}</td><td>${esc(x.payer_name||'')}</td></tr>`).join('')}</tbody></table>`}
function bindBilling(tab,d){if(tab==='charges'){$('ntv4CodeSearch').onclick=searchCodes;$('ntv4DxSearch').onclick=searchDx;$('ntv4SaveCharge').onclick=()=>saveCharge(d);$('ntv4CreateClaim').onclick=()=>{$('ntv4ClaimForm').style.display='block';$('ntv4ClaimPayer').value=$('ntv4ChargePayer').value};$('ntv4ConfirmClaim').onclick=()=>createClaim(d)}else if(tab==='claims'){document.querySelectorAll('[data-claim-action]').forEach(b=>b.onclick=()=>claimAction(b.dataset.claimAction,b.dataset.id))}}
async function searchCodes(){const q=$('ntv4ChargeCode').value.trim(),o=$('ntv4CodeResults');if(q.length<2){o.innerHTML='<div>Escribe al menos 2 caracteres.</div>';return}const r=await sb.from('nursetrack_billing_codes').select('code,code_system,short_label').eq('active',true).eq('validation_status','validated').or(`code.ilike.%${q.replace(/[%(),]/g,'')}%,short_label.ilike.%${q.replace(/[%(),]/g,'')}%`).limit(15);if(r.error){o.innerHTML='<div>No se pudo buscar.</div>';return}o.innerHTML=(r.data||[]).map(x=>`<button type="button" data-code="${esc(x.code)}">${esc(x.code_system)} ${esc(x.code)} · ${esc(x.short_label||'')}</button>`).join('')||'<div>Sin resultados.</div>';o.querySelectorAll('[data-code]').forEach(b=>b.onclick=()=>{$('ntv4ChargeCode').value=b.dataset.code;o.innerHTML=''})}
async function searchDx(){const q=$('ntv4ChargeDx').value.trim(),o=$('ntv4DxResults');if(q.length<2){o.innerHTML='<div>Escribe al menos 2 caracteres.</div>';return}const clean=q.split(',').pop().trim().replace(/[%(),]/g,''),r=await sb.from('nursetrack_diagnosis_codes').select('code,description').eq('active',true).eq('validation_status','validated').or(`code.ilike.%${clean}%,description.ilike.%${clean}%`).limit(15);if(r.error){o.innerHTML='<div>No se pudo buscar.</div>';return}o.innerHTML=(r.data||[]).map(x=>`<button type="button" data-dx="${esc(x.code)}">${esc(x.code)} · ${esc(x.description||'')}</button>`).join('')||'<div>Sin resultados.</div>';o.querySelectorAll('[data-dx]').forEach(b=>b.onclick=()=>{const old=$('ntv4ChargeDx').value.split(',').map(x=>x.trim()).filter(Boolean);old[old.length-1]=b.dataset.dx;$('ntv4ChargeDx').value=[...new Set(old)].join(', ');o.innerHTML=''})}
async function saveCharge(d){if(busy)return;busy=true;const st=$('ntv4BillingStatus');try{st.textContent='Guardando cargo…';const code=$('ntv4ChargeCode').value.trim().toUpperCase(),visit=$('ntv4ChargeVisit').value;if(!code||!visit)throw new Error('Selecciona visita y código.');let key=$('ntv4SaveCharge').dataset.key;if(!key){key='v4-charge:'+ctx.user.id+':'+patient.id+':'+uuid();$('ntv4SaveCharge').dataset.key=key}const dx=$('ntv4ChargeDx').value.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean),payload={company_id:ctx.company,patient_id:patient.id,visit_id:visit,client_charge_key:key,code,code_system:'',diagnosis_codes:dx,service_date:$('ntv4ChargeDate').value||today(),amount:$('ntv4ChargeAmount').value||'0',status:$('ntv4ChargeStatus').value,payer_name:$('ntv4ChargePayer').value.trim()||null,notes:$('ntv4ChargeNotes').value.trim()||null};const r=await sb.rpc('nursetrack_save_service_charge',{p_payload:payload});if(r.error)throw r.error;st.textContent=r.data?.[0]?.reused?'Cargo actualizado sin duplicar.':'Cargo guardado.';st.style.color='#216b48';$('ntv4SaveCharge').dataset.key='';setTimeout(()=>openBilling('charges'),500)}catch(e){st.textContent=e.message||String(e);st.style.color='#933'}finally{busy=false}}
async function createClaim(d){if(busy)return;busy=true;const st=$('ntv4BillingStatus');try{st.textContent='Creando reclamación…';const visit=$('ntv4ChargeVisit').value;if(!visit)throw new Error('Selecciona una visita.');const r=await sb.rpc('nursetrack_create_draft_claim_from_services',{p_company_id:ctx.company,p_patient_id:patient.id,p_visit_id:visit,p_payer_name:$('ntv4ClaimPayer').value.trim()||null,p_payer_id:$('ntv4ClaimPayerId').value.trim()||null,p_member_id:$('ntv4ClaimMember').value.trim()||null,p_claim_type:$('ntv4ClaimType').value});if(r.error)throw r.error;st.textContent='Reclamación borrador creada sin duplicar líneas.';st.style.color='#216b48';setTimeout(()=>openBilling('claims'),500)}catch(e){st.textContent=e.message||String(e);st.style.color='#933'}finally{busy=false}}
async function claimAction(action,id){if(busy)return;busy=true;try{let r;if(action==='validate')r=await sb.rpc('nursetrack_validate_claim',{p_claim_id:id});else if(action==='ready')r=await sb.rpc('nursetrack_mark_claim_ready',{p_claim_id:id});else if(action==='queue')r=await sb.rpc('nursetrack_queue_claim_transmission',{p_claim_id:id});if(r?.error)throw r.error;setTimeout(()=>openBilling('claims'),250)}catch(e){alert(e.message||String(e))}finally{busy=false}}
async function adminCall(payload){const c=ctx||await getCtx(),ses=await sb.auth.getSession(),token=ses?.data?.session?.access_token,cfg=window.NURSETRACK_SUPABASE||{};if(!token)throw new Error('Sesión no disponible');const r=await fetch(cfg.url+'/functions/v1/admin-users',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token,'apikey':cfg.publishableKey},body:JSON.stringify(payload)}),data=await r.json().catch(()=>({}));if(!r.ok||!data.ok)throw new Error(data.error||'No se pudo completar la acción.');return data}
async function openAdmin(view='list',id=null){try{addStyles();await getCtx();if(!['superadmin','superadministrator'].includes(String(profile?.role||'').toLowerCase()))throw new Error('Acceso restringido al Súper Administrador.');let data=null;if(view==='list')data=await adminCall({action:'list'});if(view==='details')data=await adminCall({action:'get-user-details',user_id:id});output(`<div class="ntv4-bacard"><h3>⚙️ Súper Administrador</h3><div class="ntv4-batabs"><button class="btn light ${view==='list'?'on':''}" id="ntv4AdminList">Usuarios</button><button class="btn light ${view==='create'?'on':''}" id="ntv4AdminCreate">Crear usuario</button></div><div id="ntv4AdminBody">${adminBody(view,data)}</div><div id="ntv4AdminStatus" class="status"></div></div>`);$('ntv4AdminList').onclick=()=>openAdmin('list');$('ntv4AdminCreate').onclick=()=>openAdmin('create');bindAdmin(view,data,id)}catch(e){output(`<div class="ntv4-bacard" style="color:#933">${esc(e.message||e)}</div>`)}}
function adminBody(view,d){if(view==='create')return `<div class="ntv4-bagrid"><div><label>Nombre completo *</label><input id="ntv4UserName"></div><div><label>Usuario *</label><input id="ntv4Username"></div><div><label>Email *</label><input id="ntv4UserEmail" type="email"></div><div><label>Contraseña temporal *</label><input id="ntv4UserPassword" type="password"></div><div><label>Rol</label><select id="ntv4UserRole"><option value="nurse">Enfermería</option><option value="social_worker">Trabajo Social</option><option value="provider">Proveedor / Médico</option><option value="admin">Administrador</option><option value="user">Usuario</option></select></div><div><label>Teléfono</label><input id="ntv4UserPhone"></div></div><div class="ntv4-baactions"><button class="btn" id="ntv4CreateUser">Crear usuario</button></div>`;
if(view==='details'){const u=d.user||{},assigned=new Map((d.permissions||[]).map(x=>[x.permission_key,!!x.allowed]));return `<div class="ntv4-bagrid"><div><label>Nombre</label><input id="ntv4DetailName" value="${esc(u.full_name||'')}"></div><div><label>Usuario</label><input value="${esc(u.username||'')}" disabled></div><div><label>Email</label><input value="${esc(u.email||'')}" disabled></div><div><label>Rol</label><input value="${esc(u.role||'')}" disabled></div><div><label>Teléfono</label><input id="ntv4DetailPhone" value="${esc(u.phone||'')}"></div><div><label>Recuperación email</label><input id="ntv4DetailRecoveryEmail" value="${esc(u.recovery_email||'')}"></div><div class="full"><label>Dirección</label><input id="ntv4DetailAddress" value="${esc(u.address||'')}"></div></div><div class="ntv4-baactions"><button class="btn" id="ntv4SaveProfile">Guardar ficha</button><button class="btn light" id="ntv4TempPassword">Contraseña temporal</button><button class="btn light" id="ntv4ToggleActive">${u.active?'Desactivar':'Activar'}</button></div><h4>Permisos</h4><div class="ntv4-perms">${(d.catalog||[]).map(p=>`<label><input type="checkbox" data-permission="${esc(p.permission_key)}" ${assigned.get(p.permission_key)?'checked':''}> ${esc(p.label||p.permission_key)} <small>${esc(p.module||'')}</small></label>`).join('')}</div><div class="ntv4-baactions"><button class="btn" id="ntv4SavePermissions">Guardar permisos</button></div>`}
return (d.users||[]).length?`<table class="ntv4-batable"><thead><tr><th>Usuario</th><th>Nombre</th><th>Rol</th><th>Activo</th><th>Último acceso</th><th></th></tr></thead><tbody>${d.users.map(u=>`<tr><td>${esc(u.username||'')}</td><td>${esc(u.full_name||'')}</td><td>${esc(u.role||'')}</td><td>${u.active?'Sí':'No'}</td><td>${esc(String(u.last_sign_in_at||'').replace('T',' ').slice(0,16))}</td><td><button class="btn light" data-user-details="${u.user_id}">Abrir</button></td></tr>`).join('')}</tbody></table>`:'<div>No hay usuarios.</div>'}
function bindAdmin(view,d,id){if(view==='list')document.querySelectorAll('[data-user-details]').forEach(b=>b.onclick=()=>openAdmin('details',b.dataset.userDetails));if(view==='create'&&$('ntv4CreateUser'))$('ntv4CreateUser').onclick=async()=>{if(busy)return;busy=true;const st=$('ntv4AdminStatus');try{st.textContent='Creando…';await adminCall({action:'create',full_name:$('ntv4UserName').value,username:$('ntv4Username').value,email:$('ntv4UserEmail').value,password:$('ntv4UserPassword').value,role:$('ntv4UserRole').value,phone:$('ntv4UserPhone').value,recovery_email:$('ntv4UserEmail').value});st.textContent='Usuario creado.';st.style.color='#216b48';setTimeout(()=>openAdmin('list'),400)}catch(e){st.textContent=e.message||String(e);st.style.color='#933'}finally{busy=false}};
if(view==='details'){const u=d.user||{};$('ntv4SaveProfile').onclick=async()=>{const st=$('ntv4AdminStatus');try{await adminCall({action:'update-profile',user_id:u.user_id,full_name:$('ntv4DetailName').value,phone:$('ntv4DetailPhone').value,address:$('ntv4DetailAddress').value,recovery_email:$('ntv4DetailRecoveryEmail').value,company:u.company||''});st.textContent='Ficha actualizada.';st.style.color='#216b48'}catch(e){st.textContent=e.message||String(e);st.style.color='#933'}};$('ntv4TempPassword').onclick=async()=>{const pw=prompt('Contraseña temporal (mínimo 8 caracteres):');if(!pw)return;try{await adminCall({action:'temporary-password',user_id:u.user_id,password:pw});alert('Contraseña temporal asignada.')}catch(e){alert(e.message||String(e))}};$('ntv4ToggleActive').onclick=async()=>{if(!confirm(`${u.active?'Desactivar':'Activar'} este usuario?`))return;try{await adminCall({action:'set-active',user_id:u.user_id,active:!u.active});openAdmin('details',u.user_id)}catch(e){alert(e.message||String(e))}};$('ntv4SavePermissions').onclick=async()=>{const permissions=Array.from(document.querySelectorAll('[data-permission]')).map(x=>({permission_key:x.dataset.permission,allowed:x.checked}));try{await adminCall({action:'set-permissions',user_id:u.user_id,permissions});alert('Permisos guardados.')}catch(e){alert(e.message||String(e))}}}}
function addPatientButton(){const bar=document.querySelector('#patientPanel .actions');if(!bar||$('ntv4BillingBtn'))return;const b=document.createElement('button');b.id='ntv4BillingBtn';b.className='btn light';b.textContent='Facturación';b.onclick=()=>openBilling('charges');bar.appendChild(b)}
async function hookAdmin(){try{await getCtx();if(!['superadmin','superadministrator'].includes(String(profile?.role||'').toLowerCase()))return;document.querySelectorAll('#modulesPanel .module').forEach(b=>{const t=(b.querySelector('strong')?.textContent||'').toLowerCase();if(t==='administración')b.onclick=()=>openAdmin('list')});const set=document.querySelector('.nav button[data-view="settings"]');if(set&&!set.dataset.ntv4AdminHook){set.dataset.ntv4AdminHook='1';set.addEventListener('click',()=>setTimeout(()=>openAdmin('list'),0))}}catch(_){}}
function hookBillingCard(){document.querySelectorAll('#modulesPanel .module').forEach(b=>{const t=(b.querySelector('strong')?.textContent||'').toLowerCase();if(t==='facturación')b.onclick=()=>openBilling('charges')})}
function init(){addStyles();addPatientButton();hookBillingCard();hookAdmin();new MutationObserver(()=>{addPatientButton();hookBillingCard();hookAdmin()}).observe(document.body,{childList:true,subtree:true});window.NT_V4_BILLING={open:()=>openBilling('charges')};window.NT_V4_ADMIN={open:()=>openAdmin('list')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();