(function(){
'use strict';if(window.__NT_V4_LABS__)return;window.__NT_V4_LABS__=true;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let sb=null,patient=null,ctx=null,selected=[],orderKey=null,busy=false;
function area(){return document.getElementById('patientActionArea')}function setArea(h){const a=area();if(a)a.innerHTML=h}
function styles(){if(document.getElementById('ntV4LabsStyle'))return;const s=document.createElement('style');s.id='ntV4LabsStyle';s.textContent='.ntv4-labcard{background:#fff;border:1px solid #d8e6e8;border-radius:14px;padding:16px;margin-top:12px}.ntv4-labgrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ntv4-labgrid .full{grid-column:1/-1}.ntv4-labrow{display:grid;grid-template-columns:1.4fr .7fr .7fr .8fr;gap:10px;border-bottom:1px solid #e5eeee;padding:10px 0}.ntv4-labrow:last-child{border-bottom:0}.ntv4-chip{display:inline-flex;gap:6px;align-items:center;background:#edf5f6;border:1px solid #d8e6e8;border-radius:999px;padding:6px 9px;margin:4px}.ntv4-result-abn{color:#983f3f;font-weight:800}.ntv4-catbtn{width:100%;text-align:left;border:1px solid #d8e6e8;background:#fff;border-radius:10px;padding:10px;margin:5px 0;cursor:pointer}@media(max-width:700px){.ntv4-labgrid,.ntv4-labrow{grid-template-columns:1fr}.ntv4-labgrid .full{grid-column:auto}}';(document.head||document.documentElement).appendChild(s)}
async function client(){if(sb)return sb;if(typeof window.NT_loadSupabase!=='function')throw new Error('Supabase no disponible');const lib=await window.NT_loadSupabase(),cfg=window.NURSETRACK_SUPABASE||{};sb=lib.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
async function getCtx(){await client();const s=await sb.auth.getSession(),u=s?.data?.session?.user;if(!u)throw new Error('Sesión no disponible');let company=null;let r=await sb.from('nursetrack_company_users').select('company_id').eq('user_id',u.id).eq('active',true).limit(1);if(r.data?.[0])company=r.data[0].company_id;if(!company){let m=await sb.from('nursetrack_account_memberships').select('company_id').eq('user_id',u.id).eq('status','active').limit(1);company=m.data?.[0]?.company_id||null}if(!company)throw new Error('No hay compañía activa');ctx={user:u,company};return ctx}
function mrn(){return (document.getElementById('patientMrn')?.textContent||'').replace(/^(MRN|Expediente)\s*:?-?\s*/i,'').trim()}
async function getPatient(){const c=await getCtx(),m=mrn();if(!m)throw new Error('Abre un paciente primero');const r=await sb.from('nursetrack_patients_v2').select('*').eq('company_id',c.company).ilike('mrn',m).is('deleted_at',null).limit(1);if(r.error)throw r.error;if(!r.data?.[0])throw new Error('Paciente no localizado');patient=r.data[0];return patient}
function head(p){return `<div class="ntv4-labcard"><strong>${esc(p.first_name)} ${esc(p.last_name)}</strong> · Expediente ${esc(p.mrn||'')}</div>`}
function newKey(){if(!orderKey)orderKey='v4-lab-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9);return orderKey}
async function openLabs(){try{selected=[];orderKey=null;const c=await getCtx(),p=await getPatient();const [o,r]=await Promise.all([sb.from('nursetrack_lab_orders').select('*').eq('company_id',c.company).eq('patient_id',p.id).order('created_at',{ascending:false}).limit(50),sb.from('nursetrack_labs').select('*').eq('company_id',c.company).eq('patient_id',p.id).order('result_date',{ascending:false}).limit(100)]);if(o.error)throw o.error;if(r.error)throw r.error;setArea(`${head(p)}<div class="ntv4-labcard"><h3>Nueva orden de laboratorio</h3><div style="display:flex;gap:8px"><input id="ntv4LabSearch" placeholder="Buscar prueba en el catálogo"><button class="btn secondary" id="ntv4LabSearchBtn">Buscar</button></div><div id="ntv4LabCatalog"></div><div id="ntv4SelectedLabs" style="margin:10px 0"></div><div class="ntv4-labgrid"><div><label>Prioridad</label><select id="ntv4LabPriority"><option value="routine">Rutina</option><option value="urgent">Urgente</option><option value="stat">STAT</option></select></div><div><label>Profesional que ordena</label><input id="ntv4LabProfessional"></div><div class="full"><label>Diagnósticos (separados por coma)</label><input id="ntv4LabDx" placeholder="B20, Z00.00"></div><div class="full"><label>Razón clínica</label><textarea id="ntv4LabReason"></textarea></div><div class="full"><label>Instrucciones</label><textarea id="ntv4LabInstructions"></textarea></div><div class="full"><label><input id="ntv4LabConfirm" type="checkbox" style="width:auto"> Confirmo profesionalmente esta orden</label></div></div><button class="btn" id="ntv4LabSave" style="margin-top:12px">Guardar orden</button><div id="ntv4LabStatus" class="status"></div></div><div class="ntv4-labcard"><h3>Órdenes</h3>${o.data?.length?o.data.map(x=>`<div class="ntv4-labrow"><div><strong>${esc((x.tests||[]).map(t=>t.test_name||t.name||t).join(', '))}</strong><div>${esc(x.clinical_reason||'')}</div></div><div>${esc(x.order_date||'')}</div><div>${esc(x.priority||'')}</div><div>${esc(x.status||'')}</div></div>`).join(''):'<div>No hay órdenes para este paciente.</div>'}</div><div class="ntv4-labcard"><h3>Resultados</h3>${r.data?.length?r.data.map(x=>`<div class="ntv4-labrow"><div><strong>${esc(x.lab_type||'')}</strong><div>${esc(x.notes||'')}</div></div><div class="${x.abnormal?'ntv4-result-abn':''}">${esc(x.result_value??x.numeric_value??'')} ${esc(x.unit||'')}</div><div>${esc(x.result_date||'')}</div><div>${esc(x.review_status||'')}</div></div>`).join(''):'<div>No hay resultados para este paciente.</div>'}</div>`);document.getElementById('ntv4LabSearchBtn')?.addEventListener('click',searchCatalog);document.getElementById('ntv4LabSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchCatalog()}});document.getElementById('ntv4LabSave')?.addEventListener('click',saveOrder)}catch(e){setArea(`<div class="ntv4-labcard" style="color:#9b3d3d">${esc(e.message||e)}</div>`)}}
async function searchCatalog(){const c=await getCtx(),q=document.getElementById('ntv4LabSearch')?.value.trim(),out=document.getElementById('ntv4LabCatalog');if(!out)return;if(!q){out.innerHTML='<div>Escribe el nombre de una prueba.</div>';return}out.innerHTML='Buscando…';let r=await sb.from('nursetrack_lab_catalog').select('id,test_name,category,specimen,cpt_hcpcs_codes,diagnosis_suggestions,validation_status').eq('active',true).ilike('test_name',`%${q}%`).or(`company_id.is.null,company_id.eq.${c.company}`).limit(30);if(r.error){out.innerHTML=`<div style="color:#9b3d3d">${esc(r.error.message)}</div>`;return}out.innerHTML=r.data?.length?r.data.map(x=>`<button class="ntv4-catbtn" data-lab-id="${esc(x.id)}"><strong>${esc(x.test_name)}</strong><div>${esc(x.category||'')} · ${esc(x.specimen||'')}</div></button>`).join(''):'<div>No se encontraron pruebas.</div>';out.querySelectorAll('[data-lab-id]').forEach(b=>b.addEventListener('click',()=>{const x=r.data.find(y=>y.id===b.dataset.labId);if(x&&!selected.some(y=>y.id===x.id)){selected.push(x);renderSelected()}}))}
function renderSelected(){const out=document.getElementById('ntv4SelectedLabs');if(!out)return;out.innerHTML=selected.length?selected.map(x=>`<span class="ntv4-chip">${esc(x.test_name)} <button type="button" data-remove-lab="${esc(x.id)}" style="border:0;background:transparent;cursor:pointer">×</button></span>`).join(''):'<span>No hay pruebas seleccionadas.</span>';out.querySelectorAll('[data-remove-lab]').forEach(b=>b.addEventListener('click',()=>{selected=selected.filter(x=>x.id!==b.dataset.removeLab);renderSelected()}))}
async function saveOrder(){if(busy)return;busy=true;const st=document.getElementById('ntv4LabStatus');if(st)st.textContent='Guardando…';try{const c=await getCtx(),p=patient||await getPatient();if(!selected.length)throw new Error('Selecciona al menos una prueba');if(!document.getElementById('ntv4LabConfirm')?.checked)throw new Error('Confirma profesionalmente la orden');const key=newKey();const ex=await sb.from('nursetrack_lab_orders').select('id').eq('company_id',c.company).eq('client_order_key',key).limit(1);if(ex.data?.[0]){if(st)st.textContent='La orden ya estaba guardada.';return}const v=await sb.from('nursetrack_visits').select('id').eq('company_id',c.company).eq('patient_id',p.id).is('deleted_at',null).order('visit_date',{ascending:false}).limit(1);const row={company_id:c.company,patient_id:p.id,visit_id:v.data?.[0]?.id||null,status:'ordered',tests:selected.map(x=>({id:x.id,test_name:x.test_name,category:x.category,specimen:x.specimen,cpt_hcpcs_codes:x.cpt_hcpcs_codes})),diagnosis_codes:(document.getElementById('ntv4LabDx')?.value||'').split(',').map(x=>x.trim()).filter(Boolean),clinical_reason:document.getElementById('ntv4LabReason')?.value.trim()||null,professional_confirmed:true,created_by:c.user.id,order_date:new Date().toISOString().slice(0,10),priority:document.getElementById('ntv4LabPriority')?.value||'routine',instructions:document.getElementById('ntv4LabInstructions')?.value.trim()||null,ordering_professional:document.getElementById('ntv4LabProfessional')?.value.trim()||null,client_order_key:key,last_modified_by:c.user.id};const r=await sb.from('nursetrack_lab_orders').insert(row).select('id').single();if(r.error)throw r.error;if(st){st.textContent='Orden guardada.';st.style.color='#216b48'}setTimeout(openLabs,500)}catch(e){if(st){st.textContent=e.message||String(e);st.style.color='#9b3d3d'}}finally{busy=false}}
function intercept(e){const b=e.target.closest?.('.patient-action[data-action="labs"]');if(b){e.preventDefault();e.stopImmediatePropagation();openLabs()}}
function boot(){styles();document.addEventListener('click',intercept,true);window.NT_V4_LABS={open:openLabs,version:'1.0.0'}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
