(function(){
'use strict';
if(window.__NT_V4_LOGISTICS__) return;
window.__NT_V4_LOGISTICS__=true;

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let sb=null,ctx=null,pending=null;

const PATIENT_OPS={tasks:['Tareas','Seguimiento clínico y llamadas'],reminders:['Recordatorios','SMS y cola de recordatorios']};
const GLOBAL_OPS={assignments:['Asignaciones','Pacientes por usuario'],inventory:['Inventario','Control operativo'],catalogs:['Localidades / Departamentos','Catálogos operativos'],capacity:['Capacidad / Memoria','Uso real del sistema'],appearance:['Apariencia / Portadas','Logo, colores, textos editables y portadas']};

function style(){if($('ntV4LogStyle'))return;const s=document.createElement('style');s.id='ntV4LogStyle';s.textContent='.ntv4-logcard{background:#fff;border:1px solid #d8e6e8;border-radius:16px;padding:18px;margin-top:14px}.ntv4-loghead{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.ntv4-logbadge{padding:6px 10px;border-radius:999px;background:#edf5f6;border:1px solid #d8e6e8;font-size:12px}.ntv4-loggrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.ntv4-logbtn{border:1px solid #d8e6e8;background:#fff;border-radius:13px;padding:13px;text-align:left;min-height:82px}.ntv4-logbtn:hover{background:#f7fbfb;border-color:#9dc1c8}.ntv4-logbtn strong{display:block}.ntv4-logbtn small{display:block;color:#6f858b;margin-top:5px}.ntv4-logsearch{display:grid;grid-template-columns:1fr auto;gap:8px}.ntv4-logresults{display:grid;gap:7px;margin-top:10px}.ntv4-logpatient{width:100%;border:1px solid #d8e6e8;background:#fff;border-radius:11px;padding:11px;text-align:left}.ntv4-logpatient:hover{background:#f7fbfb}.ntv4-logerror{background:#fff4f4;border:1px solid #e5b5b5;color:#8b3131;border-radius:12px;padding:12px;margin-top:12px}@media(max-width:760px){.ntv4-loggrid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.ntv4-loggrid,.ntv4-logsearch{grid-template-columns:1fr}}';(document.head||document.documentElement).appendChild(s)}
async function client(){if(sb)return sb;if(typeof window.NT_loadSupabase!=='function')throw new Error('Supabase no disponible');const lib=await window.NT_loadSupabase(),cfg=window.NURSETRACK_SUPABASE||{};if(!cfg.url||!cfg.publishableKey)throw new Error('Configuración cloud incompleta');sb=lib.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
async function context(){if(ctx)return ctx;await client();const ses=await sb.auth.getSession(),u=ses?.data?.session?.user;if(!u)throw new Error('Sesión no disponible');let r=await sb.from('nursetrack_company_users').select('company_id').eq('user_id',u.id).eq('active',true).limit(1),company=r.data?.[0]?.company_id||null;if(!company){const m=await sb.from('nursetrack_account_memberships').select('company_id').eq('user_id',u.id).eq('status','active').limit(1);company=m.data?.[0]?.company_id||null}if(!company)throw new Error('No hay compañía activa');const p=await sb.from('nursetrack_profiles').select('role').eq('user_id',u.id).maybeSingle();ctx={user:u,company,isSuper:['superadmin','superadministrator'].includes(String(p.data?.role||'').toLowerCase())};return ctx}
function shell(title='Logística'){['homePanel','modulesPanel','placeholderPanel'].forEach(id=>$(id)?.classList.add('hidden'));$('patientPanel')?.classList.remove('hidden');if($('patientName'))$('patientName').textContent=title;if($('patientMrn'))$('patientMrn').textContent='';if($('patientDemographics'))$('patientDemographics').innerHTML='';const a=document.querySelector('#patientPanel .actions');if(a)a.style.display='none';if($('newVisitBtn'))$('newVisitBtn').style.display='none';if($('pageTitle'))$('pageTitle').textContent=title;const out=$('patientActionArea');if(out)out.innerHTML='';return out}
function card(key,x,type){return `<button class="ntv4-logbtn" data-log-${type}="${key}"><strong>${esc(x[0])}</strong><small>${esc(x[1])}</small></button>`}
async function waitApi(getter,label,ms=5000){const start=Date.now();while(Date.now()-start<ms){const api=getter();if(api&&typeof api.open==='function')return api;await new Promise(r=>setTimeout(r,100))}throw new Error(`${label} no terminó de cargar. Actualiza NurseTrack One e inténtalo nuevamente.`)}
function renderHub(out){out.innerHTML=`<div class="ntv4-logcard"><div class="ntv4-loghead"><div><h3>🧭 Logística operacional</h3><div>Un solo acceso a funciones operacionales</div></div><div id="ntv4LogBadge" class="ntv4-logbadge">Verificando acceso…</div></div><div class="notice">Accesos operacionales y configuración visual. Los módulos clínicos permanecen en sus áreas principales para evitar duplicados.</div></div><div class="ntv4-logcard"><h3>Seguimiento</h3><div class="ntv4-loggrid">${Object.entries(PATIENT_OPS).map(([k,x])=>card(k,x,'patient')).join('')}</div></div><div class="ntv4-logcard"><h3>Operación y configuración</h3><div class="ntv4-loggrid">${Object.entries(GLOBAL_OPS).map(([k,x])=>card(k,x,'global')).join('')}</div><div id="ntv4LogStatus" class="status"></div></div>`;out.querySelectorAll('[data-log-patient]').forEach(b=>b.onclick=()=>choosePatient(b.dataset.logPatient));out.querySelectorAll('[data-log-global]').forEach(b=>b.onclick=()=>openGlobal(b.dataset.logGlobal))}
async function verifyHub(){const badge=$('ntv4LogBadge');try{const c=await context();if(badge)badge.textContent=c.isSuper?'Súper Administrador · acceso total':'Acceso según permisos'}catch(e){if(badge){badge.textContent=e.message||String(e);badge.style.color='#933'}}}
async function open(){style();const out=shell('Logística');if(!out)return;renderHub(out);verifyHub()}
async function openGlobal(key){const st=$('ntv4LogStatus');if(st){st.textContent='Abriendo…';st.style.color=''}try{if(key==='appearance'){window.location.assign('appearance.html?v=20260909-appearance-text-1');return}const specs={assignments:[()=>window.NT_V4_ASSIGNMENTS,'Asignaciones'],inventory:[()=>window.NT_V4_INVENTORY,'Inventario'],catalogs:[()=>window.NT_V4_ADMIN_CATALOGS,'Localidades / Departamentos'],capacity:[()=>window.NT_V4_CAPACITY,'Capacidad / Memoria']},spec=specs[key];if(!spec)throw new Error('Tarjeta no disponible');const api=await waitApi(spec[0],spec[1]);await Promise.resolve(api.open())}catch(e){if(st){st.textContent=e.message||String(e);st.style.color='#933'}}}
async function choosePatient(key){pending=key;const meta=PATIENT_OPS[key],out=shell('Logística · '+(meta?.[0]||''));if(!out)return;out.innerHTML=`<div class="ntv4-logcard"><button class="btn light" id="ntv4LogBack">← Logística</button><h3>${esc(meta?.[0]||'')}</h3><p>Busca el paciente para abrir esta función.</p><div class="ntv4-logsearch"><input id="ntv4LogPatientSearch" placeholder="Nombre, expediente, teléfono o DOB YYYY-MM-DD"><button class="btn" id="ntv4LogPatientGo">Buscar</button></div><div id="ntv4LogPatientStatus" class="status"></div><div id="ntv4LogPatientResults" class="ntv4-logresults"></div></div>`;$('ntv4LogBack').onclick=open;$('ntv4LogPatientGo').onclick=runPatientSearch;$('ntv4LogPatientSearch').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();runPatientSearch()}};setTimeout(()=>$('ntv4LogPatientSearch')?.focus(),0)}
async function runPatientSearch(){const q=$('ntv4LogPatientSearch')?.value.trim(),st=$('ntv4LogPatientStatus'),out=$('ntv4LogPatientResults');if(!q){st.textContent='Escribe un criterio de búsqueda.';return}try{const c=await context();st.textContent='Buscando…';let r=sb.from('nursetrack_patients_v2').select('id,mrn,first_name,middle_name,last_name,date_of_birth,phone').eq('company_id',c.company).is('deleted_at',null).limit(25);if(/^\d{4}-\d{2}-\d{2}$/.test(q))r=r.eq('date_of_birth',q);else{const s=q.replace(/[,%()]/g,' ').replace(/\s+/g,' ').trim();r=r.or(`mrn.ilike.%${s}%,first_name.ilike.%${s}%,last_name.ilike.%${s}%,phone.ilike.%${s}%`)}const x=await r.order('last_name');if(x.error)throw x.error;st.textContent=x.data?.length?`${x.data.length} resultado(s)`:'Sin resultados';out.innerHTML=(x.data||[]).map(p=>`<button class="ntv4-logpatient" data-pid="${p.id}"><strong>${esc([p.first_name,p.middle_name,p.last_name].filter(Boolean).join(' '))}</strong><div>Expediente ${esc(p.mrn||'—')} · DOB ${esc(p.date_of_birth||'—')} · ${esc(p.phone||'')}</div></button>`).join('');out.querySelectorAll('[data-pid]').forEach(b=>b.onclick=()=>{const p=x.data.find(v=>v.id===b.dataset.pid);if(p)launchPatientOp(pending,p)})}catch(e){st.textContent=e.message||String(e);st.style.color='#933'}}
function setPatientContext(p){if($('patientName'))$('patientName').textContent=[p.first_name,p.middle_name,p.last_name].filter(Boolean).join(' ');if($('patientMrn'))$('patientMrn').textContent='Expediente '+(p.mrn||'');if($('patientDemographics'))$('patientDemographics').innerHTML='';if($('patientActionArea'))$('patientActionArea').innerHTML='<div class="notice">Cargando módulo…</div>'}
async function launchPatientOp(key,p){setPatientContext(p);try{const specs={tasks:[()=>window.NT_V4_TASKS,'Tareas'],reminders:[()=>window.NT_V4_REMINDERS,'Recordatorios']},spec=specs[key];if(!spec)throw new Error('Tarjeta no disponible');const api=await waitApi(spec[0],spec[1]);await Promise.resolve(api.open())}catch(e){const out=$('patientActionArea');if(out)out.innerHTML=`<div class="ntv4-logerror">${esc(e.message||e)}</div>`}}
function renameNav(){const b=document.querySelector('.nav button[data-view="modules"]');if(b)b.textContent='Logística'}
function intercept(e){const b=e.target.closest?.('.nav button[data-view="modules"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();open()}
function init(){style();renameNav();document.addEventListener('click',intercept,true);window.NT_V4_LOGISTICS={open,version:'2.2.0-appearance-text'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();