(function(){
'use strict';
if(window.__NT_V4_MAINTENANCE__) return;
window.__NT_V4_MAINTENANCE__=true;
const $=id=>document.getElementById(id);
let sb=null,roleChecked=false,isSuper=false,opening=false;
function style(){if($('ntV4MaintenanceStyle'))return;const s=document.createElement('style');s.id='ntV4MaintenanceStyle';s.textContent=`.ntm-card{background:#fff;border:1px solid #d8e6e8;border-radius:16px;padding:16px;margin-top:14px}.ntm-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ntm-tool{border:1px solid #dce9ed;border-radius:14px;padding:15px;background:#fbfdfe;text-align:left}.ntm-tool h4{margin:0 0 6px;color:#173e61}.ntm-tool p{margin:0;color:#6d838f;font-size:13px;line-height:1.4}.ntm-tool button,.ntm-tool a.btn{margin-top:10px}.ntm-tool a.btn{display:inline-block;text-decoration:none}.ntm-status{margin-top:12px;font-size:13px}.ntm-admin-card{margin:14px 0 0;border:1px solid #bfe0e6;border-radius:14px;padding:14px;background:#f4fbfd}.ntm-admin-card strong{display:block;color:#174866;font-size:16px}.ntm-admin-card small{display:block;color:#6c838d;margin-top:4px}.ntm-admin-card button{margin-top:10px}.ntm-version{display:inline-block;padding:4px 8px;border-radius:999px;background:#e7f5f8;color:#0b7081;font-weight:800;font-size:12px}.ntm-busy{opacity:.72;pointer-events:none}@media(max-width:700px){.ntm-grid{grid-template-columns:1fr}}`;(document.head||document.documentElement).appendChild(s)}
async function client(){if(sb)return sb;if(typeof window.NT_loadSupabase!=='function')throw new Error('Supabase no disponible');const lib=await window.NT_loadSupabase(),cfg=window.NURSETRACK_SUPABASE||{};sb=lib.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
async function checkRole(){if(roleChecked)return isSuper;try{await client();const s=await sb.auth.getSession(),u=s?.data?.session?.user;if(!u){roleChecked=true;isSuper=false;return false}const r=await sb.from('nursetrack_profiles').select('role').eq('user_id',u.id).maybeSingle();if(r.error)throw r.error;const role=String(r.data?.role||'').toLowerCase();isSuper=['superadmin','superadministrator'].includes(role);roleChecked=true;return isSuper}catch(_){return false}}
function shell(){['homePanel','modulesPanel','placeholderPanel'].forEach(id=>$(id)?.classList.add('hidden'));$('patientPanel')?.classList.remove('hidden');if($('patientName'))$('patientName').textContent='Mantenimiento del sistema';if($('patientMrn'))$('patientMrn').textContent='';if($('patientDemographics'))$('patientDemographics').innerHTML='';const a=document.querySelector('#patientPanel .actions');if(a)a.style.display='none';if($('newVisitBtn'))$('newVisitBtn').style.display='none';if($('pageTitle'))$('pageTitle').textContent='Mantenimiento del sistema';const out=$('patientActionArea');if(out)out.innerHTML='';return out}
function status(text,ok=true){const el=$('ntmStatus');if(!el)return;el.textContent=text||'';el.style.color=ok?'#216b48':'#933'}
async function clearCache(){try{status('Limpiando caché…');if('caches' in window){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)))}status('Caché limpiado. Recargando NurseTrack One…');const u=new URL(location.href);u.searchParams.set('refresh',Date.now());setTimeout(()=>location.replace(u.toString()),450)}catch(e){status(e.message||String(e),false)}}
function render(out){out.innerHTML=`<div class="ntm-card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><div><h3 style="margin:0">🛠️ Mantenimiento del sistema</h3><p style="margin:5px 0 0;color:#6b8390">Herramientas administrativas de NurseTrack One.</p></div><span class="ntm-version">NurseTrack One · v4</span></div><div class="ntm-grid" style="margin-top:14px"><div class="ntm-tool"><h4>🛡️ Estado / Backups</h4><p>Salud del sistema y respaldos preservados.</p><button class="btn" id="ntmSystem" type="button">Abrir</button></div><div class="ntm-tool"><h4>💾 Capacidad / Memoria</h4><p>Uso real de base de datos y archivos.</p><button class="btn" id="ntmCapacity" type="button">Abrir</button></div><div class="ntm-tool"><h4>🧾 Auditoría</h4><p>Eventos del sistema y actividad administrativa en modo lectura.</p><button class="btn" id="ntmAudit" type="button">Abrir</button></div><div class="ntm-tool"><h4>🔄 Limpiar caché / Actualizar</h4><p>Elimina caché local del navegador y vuelve a cargar la versión más reciente.</p><button class="btn secondary" id="ntmCache" type="button">Limpiar y actualizar</button></div><div class="ntm-tool" id="ntmAppearanceCard"><h4>🎨 Apariencia / Portadas</h4><p>Configuración visual y portadas del sistema.</p><a class="btn light" id="ntmAppearance" href="appearance.html?v=20260909-appearance-enter-1">Abrir Apariencia / Portadas</a></div><div class="ntm-tool"><h4>⚙️ Administración</h4><p>Volver a usuarios, permisos y control del Súper Administrador.</p><button class="btn light" id="ntmAdmin" type="button">Volver</button></div></div><div id="ntmStatus" class="ntm-status"></div></div>`;
$('ntmSystem').onclick=()=>window.NT_V4_SYSTEM?.open();$('ntmCapacity').onclick=()=>window.NT_V4_CAPACITY?.open();$('ntmAudit').onclick=()=>window.NT_V4_AUDIT?.open();$('ntmCache').onclick=clearCache;$('ntmAdmin').onclick=()=>window.NT_V4_ADMIN?.open();const ap=$('ntmAppearance');if(ap)ap.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.repeat){e.preventDefault();e.stopImmediatePropagation();location.assign(ap.href)}},true)}
async function open(){if(opening)return;opening=true;const source=$('ntmModuleCard')||$('ntmAdminOpen');source?.classList.add('ntm-busy');try{style();const allowed=await checkRole();const out=shell();if(!out)return;if(!allowed){out.innerHTML='<div class="ntm-card" style="color:#933">Acceso restringido al Súper Administrador.</div>';return}render(out)}catch(e){const out=$('patientActionArea');if(out)out.innerHTML='<div class="ntm-card" style="color:#933">No se pudo abrir Mantenimiento: '+String(e?.message||e)+'</div>'}finally{setTimeout(()=>{opening=false;source?.classList.remove('ntm-busy')},350)}}
function bindSafeActivation(el){if(!el||el.dataset.ntmSafe==='1')return;el.dataset.ntmSafe='1';el.addEventListener('click',e=>{e.preventDefault();open()},false);el.addEventListener('keydown',e=>{if(e.repeat)return;if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopImmediatePropagation();open()}},true)}
async function injectAdminCard(){if(!await checkRole())return;const body=$('patientActionArea');if(!body||$('ntmAdminEntry'))return;const h=[...body.querySelectorAll('h3')].find(x=>/súper administrador/i.test(x.textContent||''));if(!h)return;const card=document.createElement('div');card.id='ntmAdminEntry';card.className='ntm-admin-card';card.innerHTML='<strong>🛠️ Mantenimiento del sistema</strong><small>Backups, capacidad, auditoría, caché y actualización.</small><button class="btn secondary" id="ntmAdminOpen" type="button">Abrir mantenimiento</button>';const host=h.closest('.ntv4-bacard')||body;host.appendChild(card);bindSafeActivation($('ntmAdminOpen'))}
async function addModuleCard(){if(!await checkRole())return;const grid=document.querySelector('#modulesPanel .module-grid');if(!grid)return;let b=$('ntmModuleCard');if(!b){b=document.createElement('button');b.type='button';b.id='ntmModuleCard';b.className='module';b.innerHTML='<strong>Mantenimiento</strong><small>Herramientas exclusivas del Súper Administrador</small>';grid.appendChild(b)}bindSafeActivation(b)}
function init(){style();window.NT_V4_MAINTENANCE={open,version:'1.3.0'};let tries=0;const timer=setInterval(()=>{addModuleCard();injectAdminCard();if(++tries>=60)clearInterval(timer)},1000);addModuleCard();injectAdminCard()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();