(function(){
'use strict';
if(window.__NT_V4_MAINTENANCE__) return;
window.__NT_V4_MAINTENANCE__=true;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let sb=null,roleChecked=false,isSuper=false;
function style(){if($('ntV4MaintenanceStyle'))return;const s=document.createElement('style');s.id='ntV4MaintenanceStyle';s.textContent=`.ntm-card{background:#fff;border:1px solid #d8e6e8;border-radius:16px;padding:16px;margin-top:14px}.ntm-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ntm-tool{border:1px solid #dce9ed;border-radius:14px;padding:15px;background:#fbfdfe;text-align:left}.ntm-tool h4{margin:0 0 6px;color:#173e61}.ntm-tool p{margin:0;color:#6d838f;font-size:13px;line-height:1.4}.ntm-tool button{margin-top:10px}.ntm-status{margin-top:12px;font-size:13px}.ntm-admin-card{margin:14px 0 0;border:1px solid #bfe0e6;border-radius:14px;padding:14px;background:#f4fbfd}.ntm-admin-card strong{display:block;color:#174866;font-size:16px}.ntm-admin-card small{display:block;color:#6c838d;margin-top:4px}.ntm-admin-card button{margin-top:10px}.ntm-version{display:inline-block;padding:4px 8px;border-radius:999px;background:#e7f5f8;color:#0b7081;font-weight:800;font-size:12px}@media(max-width:700px){.ntm-grid{grid-template-columns:1fr}}`;(document.head||document.documentElement).appendChild(s)}
async function client(){if(sb)return sb;if(typeof window.NT_loadSupabase!=='function')throw new Error('Supabase no disponible');const lib=await window.NT_loadSupabase(),cfg=window.NURSETRACK_SUPABASE||{};sb=lib.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
async function checkRole(){if(roleChecked)return isSuper;roleChecked=true;try{await client();const s=await sb.auth.getSession(),u=s?.data?.session?.user;if(!u)return false;const r=await sb.from('nursetrack_profiles').select('role').eq('user_id',u.id).maybeSingle();const role=String(r.data?.role||'').toLowerCase();isSuper=['superadmin','superadministrator'].includes(role);return isSuper}catch(_){return false}}
function shell(){['homePanel','modulesPanel','placeholderPanel'].forEach(id=>$(id)?.classList.add('hidden'));$('patientPanel')?.classList.remove('hidden');if($('patientName'))$('patientName').textContent='Mantenimiento del sistema';if($('patientMrn'))$('patientMrn').textContent='';if($('patientDemographics'))$('patientDemographics').innerHTML='';const a=document.querySelector('#patientPanel .actions');if(a)a.style.display='none';if($('newVisitBtn'))$('newVisitBtn').style.display='none';if($('pageTitle'))$('pageTitle').textContent='Mantenimiento del sistema';const out=$('patientActionArea');if(out)out.innerHTML='';return out}
function status(text,ok=true){const el=$('ntmStatus');if(!el)return;el.textContent=text||'';el.style.color=ok?'#216b48':'#933'}
async function clearCache(){try{status('Limpiando caché…');if('caches' in window){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)))}status('Caché limpiado. Recargando NurseTrack One…');const u=new URL(location.href);u.searchParams.set('refresh',Date.now());setTimeout(()=>location.replace(u.toString()),450)}catch(e){status(e.message||String(e),false)}}
async function ensureAppearance(){if(window.NT_V4_APPEARANCE?.open)return window.NT_V4_APPEARANCE;status('Cargando Apariencia / Portadas…');await new Promise((resolve,reject)=>{const old=document.querySelector('script[data-nt-appearance-reload="1"]');if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',()=>reject(new Error('No se pudo cargar Apariencia / Portadas.')),{once:true});return}const s=document.createElement('script');s.dataset.ntAppearanceReload='1';s.src='appearance-settings.js?v=20260909-v4-appearance-2&t='+Date.now();s.async=false;s.onload=resolve;s.onerror=()=>reject(new Error('No se pudo cargar Apariencia / Portadas.'));(document.head||document.documentElement).appendChild(s)});if(!window.NT_V4_APPEARANCE?.open)throw new Error('Apariencia / Portadas no quedó disponible.');return window.NT_V4_APPEARANCE}
async function openAppearance(){try{const mod=await ensureAppearance();await mod.open()}catch(e){status(e.message||String(e),false)}}
async function open(){style();const allowed=await checkRole();const out=shell();if(!out)return;if(!allowed){out.innerHTML='<div class="ntm-card" style="color:#933">Acceso restringido al Súper Administrador.</div>';return}out.innerHTML=`<div class="ntm-card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><div><h3 style="margin:0">🛠️ Mantenimiento del sistema</h3><p style="margin:5px 0 0;color:#6b8390">Herramientas administrativas de NurseTrack One.</p></div><span class="ntm-version">NurseTrack One · v4</span></div><div class="ntm-grid" style="margin-top:14px"><div class="ntm-tool"><h4>🛡️ Estado / Backups</h4><p>Salud del sistema y respaldos preservados.</p><button class="btn" id="ntmSystem">Abrir</button></div><div class="ntm-tool"><h4>💾 Capacidad / Memoria</h4><p>Uso real de base de datos y archivos.</p><button class="btn" id="ntmCapacity">Abrir</button></div><div class="ntm-tool"><h4>🧾 Auditoría</h4><p>Eventos del sistema y actividad administrativa en modo lectura.</p><button class="btn" id="ntmAudit">Abrir</button></div><div class="ntm-tool"><h4>🔄 Limpiar caché / Actualizar</h4><p>Elimina caché local del navegador y vuelve a cargar la versión más reciente.</p><button class="btn secondary" id="ntmCache">Limpiar y actualizar</button></div><div class="ntm-tool"><h4>🎨 Apariencia / Portadas</h4><p>Configuración visual y portadas del sistema.</p><button class="btn light" id="ntmAppearance">Abrir</button></div><div class="ntm-tool"><h4>⚙️ Administración</h4><p>Volver a usuarios, permisos y control del Súper Administrador.</p><button class="btn light" id="ntmAdmin">Volver</button></div></div><div id="ntmStatus" class="ntm-status"></div></div>`;
$('ntmSystem').onclick=()=>window.NT_V4_SYSTEM?.open();$('ntmCapacity').onclick=()=>window.NT_V4_CAPACITY?.open();$('ntmAudit').onclick=()=>window.NT_V4_AUDIT?.open();$('ntmCache').onclick=clearCache;$('ntmAppearance').onclick=openAppearance;$('ntmAdmin').onclick=()=>window.NT_V4_ADMIN?.open();}
async function injectAdminCard(){if(!await checkRole())return;const body=$('patientActionArea');if(!body||$('ntmAdminEntry'))return;const h=[...body.querySelectorAll('h3')].find(x=>/súper administrador/i.test(x.textContent||''));if(!h)return;const card=document.createElement('div');card.id='ntmAdminEntry';card.className='ntm-admin-card';card.innerHTML='<strong>🛠️ Mantenimiento del sistema</strong><small>Backups, capacidad, auditoría, caché y actualización.</small><button class="btn secondary" id="ntmAdminOpen">Abrir mantenimiento</button>';const host=h.closest('.ntv4-bacard')||body;host.appendChild(card);$('ntmAdminOpen').onclick=open;}
async function addModuleCard(){if(!await checkRole())return;const grid=document.querySelector('#modulesPanel .module-grid');if(!grid||$('ntmModuleCard'))return;const b=document.createElement('button');b.id='ntmModuleCard';b.className='module';b.innerHTML='<strong>Mantenimiento</strong><small>Herramientas exclusivas del Súper Administrador</small>';b.onclick=open;grid.appendChild(b)}
function init(){style();let n=0;const run=()=>{injectAdminCard();addModuleCard();if(++n>80)clearInterval(t)};run();const t=setInterval(run,300);new MutationObserver(()=>{injectAdminCard();addModuleCard()}).observe(document.body,{childList:true,subtree:true});window.NT_V4_MAINTENANCE={open,openAppearance,version:'1.1.0'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();