(function(){
'use strict';
if(window.__NT_V4_NAVIGATION__) return;
window.__NT_V4_NAVIGATION__=true;
const $=id=>document.getElementById(id);
function hide(id){$(id)?.classList.add('hidden')}
function show(id){$(id)?.classList.remove('hidden')}
function globalShell(title){hide('homePanel');hide('modulesPanel');hide('placeholderPanel');show('patientPanel');const n=$('patientName'),m=$('patientMrn'),d=$('patientDemographics'),a=document.querySelector('#patientPanel .actions'),nv=$('newVisitBtn');if(n)n.textContent=title||'NurseTrack';if(m)m.textContent='';if(d)d.innerHTML='';if(a)a.style.display='none';if(nv)nv.style.display='none';const pa=$('patientActionArea');if(pa)pa.innerHTML='';const pt=$('pageTitle');if(pt)pt.textContent=title||'NurseTrack'}
function restorePatientChrome(){const a=document.querySelector('#patientPanel .actions'),nv=$('newVisitBtn');if(a)a.style.display='flex';if(nv)nv.style.display='inline-block'}
function needPatient(label){const s=$('moduleStatus');if(s){s.textContent=`${label}: abre primero el expediente de un paciente desde Inicio.`;s.style.color='#7a4c00';s.style.background='#fff8e8'}const search=$('patientSearch');if(search){setTimeout(()=>search.focus(),0)}}
function wrapApi(root,key,title){const obj=window[root];if(!obj||obj.__ntv4Wrapped||typeof obj[key]!=='function')return false;const original=obj[key].bind(obj);obj[key]=function(){globalShell(title);return original.apply(null,arguments)};obj.__ntv4Wrapped=true;return true}
function wire(){wrapApi('NT_V4_REPORTS','open','Reportes');wrapApi('NT_V4_MEMBERSHIP','open','Membresía');wrapApi('NT_V4_ADMIN','open','Súper Administrador');document.querySelectorAll('#modulesPanel .module').forEach(b=>{const t=(b.querySelector('strong')?.textContent||'').trim().toLowerCase();if(t==='reportes'&&window.NT_V4_REPORTS)b.onclick=()=>window.NT_V4_REPORTS.open();else if(t==='membresía'&&window.NT_V4_MEMBERSHIP)b.onclick=()=>window.NT_V4_MEMBERSHIP.open();else if(t==='administración'&&window.NT_V4_ADMIN)b.onclick=()=>window.NT_V4_ADMIN.open();else if(['enfermería','trabajo social','medicina','nutrición','salud mental / psiquiatría','uso de sustancias / toxicología','vacunas / tratamientos','laboratorios','documentos','citas','facturación'].includes(t))b.onclick=()=>needPatient(b.querySelector('strong')?.textContent||'Módulo')});const settings=document.querySelector('.nav button[data-view="settings"]');if(settings&&!settings.dataset.ntv4NavGlobal){settings.dataset.ntv4NavGlobal='1';settings.addEventListener('click',()=>setTimeout(()=>{if(window.NT_V4_ADMIN)window.NT_V4_ADMIN.open()},20))}const back=$('backPatientBtn');if(back&&!back.dataset.ntv4GlobalBack){back.dataset.ntv4GlobalBack='1';back.addEventListener('click',()=>{restorePatientChrome();const pt=$('pageTitle');if(pt)pt.textContent='Inicio'},true)}}
let tries=0;const timer=setInterval(()=>{wire();if(++tries>80)clearInterval(timer)},250);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();