(function(){
'use strict';
if(window.__NT_V4_NURSING_FAST__)return;window.__NT_V4_NURSING_FAST__=true;
const $=id=>document.getElementById(id);
const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const TYPES=['Evaluación inicial','Seguimiento','Reevaluación','Readmisión'];
const FIND=[['Alerta','Paciente llega alerta'],['Orientado x4','orientado(a) en persona, lugar, tiempo y situación'],['Cooperador','cooperador(a) durante la evaluación'],['Comunicativo','comunicativo(a) y responde adecuadamente'],['Condición estable','en condición general estable'],['Sin distrés agudo','sin signos aparentes de distrés agudo'],['Deambula solo','deambula sin asistencia'],['Respiración sin esfuerzo','respiración espontánea, regular y sin esfuerzo aparente'],['Piel tibia y seca','piel tibia y seca al tacto'],['Niega dolor','niega dolor al momento de la evaluación'],['Prevención de caídas','se mantienen medidas de prevención de caídas'],['Alergias revisadas','alergias revisadas según expediente']];
const EDU=['adherencia a medicamentos','signos y síntomas de alarma','nutrición e hidratación','hipertensión','IMC y peso saludable','prevención de caídas','vacunas','seguimiento de citas','salud sexual y prevención'];
const DISC=[['Educación comprendida','Educación comprendida'],['Sale estable','Paciente sale estable'],['Ambulante','Sale ambulante'],['Acompañado','Sale acompañado(a)'],['Seguimiento','Se orienta sobre seguimiento/cita próxima'],['Alarmas','Se orienta sobre signos/síntomas de alarma y cuándo buscar atención']];
let visitKey=null,sb=null,ctx=null;
function css(){if($('ntFastStyle'))return;const s=document.createElement('style');s.id='ntFastStyle';s.textContent='.ntf{background:#fff;border:1px solid #d8e6e8;border-radius:16px;padding:16px;margin-top:12px}.ntf h3{margin:0 0 8px}.ntf-tabs,.ntf-checks{display:grid;gap:8px}.ntf-tabs{grid-template-columns:repeat(4,1fr);margin:12px 0}.ntf-checks{grid-template-columns:repeat(2,1fr)}.ntf-tab,.ntf-btn{border:1px solid #cfe0e4;border-radius:10px;padding:9px 11px;font-weight:800;background:#edf5f6;color:#244d61}.ntf-tab.on,.ntf-btn.main{background:#0b8fa3;color:#fff}.ntf-box{border:1px solid #e0ecef;border-radius:11px;padding:10px;background:#fbfdfe;margin-top:10px}.ntf-c{display:flex;gap:7px;align-items:flex-start;padding:7px;border:1px solid #e2ecef;border-radius:8px;background:#fff;font-size:13px}.ntf-c input{width:auto}.ntf textarea,.ntf input{width:100%;padding:9px;border:1px solid #cbdde3;border-radius:9px}.ntf textarea{min-height:90px}.ntf-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.ntf-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.ntf-note{font-size:12px;color:#657b83}.ntf-status{min-height:18px;margin-top:8px;font-size:13px}@media(max-width:700px){.ntf-tabs,.ntf-grid,.ntf-checks{grid-template-columns:1fr 1fr}}@media(max-width:480px){.ntf-tabs,.ntf-grid,.ntf-checks{grid-template-columns:1fr}}';document.head.appendChild(s)}
function mrn(){return String($('patientMrn')?.textContent||'').replace(/^(MRN|Expediente)\s*:?-?\s*/i,'').trim()}
function patientName(){return $('patientName')?.textContent?.trim()||'Paciente'}
function checked(name){return [...document.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value)}
function val(id){return $(id)?.value?.trim?.()||''}
function bmi(){let w=+val('nfWeight'),h=+val('nfHeight');return w>0&&h>0?(703*w/h/h).toFixed(1):''}
function bmiClass(n){n=+n;return !n?'':n<18.5?'Bajo peso':n<25?'Normal':n<30?'Sobrepeso':'Obesidad'}
function narrative(){const type=document.querySelector('.ntf-tab.on')?.dataset.type||TYPES[0],p=[`${type} de Enfermería a ${patientName()}.`],v=[];if(val('nfBp'))v.push('PA '+val('nfBp')+' mmHg');if(val('nfPulse'))v.push('pulso '+val('nfPulse')+' lpm');if(val('nfResp'))v.push('respiración '+val('nfResp')+' rpm');if(val('nfTemp'))v.push('temperatura '+val('nfTemp')+' °F');if(val('nfSpo2'))v.push('SpO₂ '+val('nfSpo2')+'%');if(val('nfWeight'))v.push('peso '+val('nfWeight')+' lb');if(val('nfHeight'))v.push('estatura '+val('nfHeight')+' in');const b=bmi();if(b)v.push('IMC '+b+' ('+bmiClass(b)+')');if(v.length)p.push('Signos vitales: '+v.join(', ')+'.');const f=checked('nfFind');if(f.length)p.push('Hallazgos de Enfermería: '+f.join('. ')+'.');const e=checked('nfEdu');if(e.length)p.push('Se brinda educación sobre '+e.join(', ')+'.');const d=checked('nfDisc');if(d.length)p.push('Alta de Enfermería: '+d.join('; ')+'.');return p.join(' ')}
function update(){if($('nfBmi'))$('nfBmi').value=bmi()?bmi()+' · '+bmiClass(bmi()):'';const n=$('nfNarrative');if(n&&!n.dataset.manual)n.value=narrative()}
function CH(name,a){return a.map(x=>`<label class="ntf-c"><input type="checkbox" name="${name}" value="${E(x[1]||x)}"><span>${E(x[0]||x)}</span></label>`).join('')}
function render(type){css();const out=$('patientActionArea');if(!out)return;const today=new Date().toISOString().slice(0,10);out.innerHTML=`<div class="ntf"><h3>🩺 Enfermería — Plantilla interactiva</h3><div class="ntf-note">${E(patientName())} · Expediente ${E(mrn())} · Abre inmediatamente; la nube se usa solo al guardar.</div><div class="ntf-tabs">${TYPES.map(t=>`<button type="button" class="ntf-tab ${t===type?'on':''}" data-type="${E(t)}">${E(t)}</button>`).join('')}</div><div class="ntf-grid"><div><label>Fecha</label><input id="nfDate" type="date" value="${today}"></div><div><label>PA</label><input id="nfBp" placeholder="120/80"></div><div><label>Pulso</label><input id="nfPulse"></div><div><label>Respiración</label><input id="nfResp"></div><div><label>Temperatura °F</label><input id="nfTemp"></div><div><label>SpO₂ %</label><input id="nfSpo2"></div><div><label>Peso lb</label><input id="nfWeight"></div><div><label>Estatura in</label><input id="nfHeight"></div></div><div class="ntf-box"><label>IMC automático</label><input id="nfBmi" readonly></div><div class="ntf-box"><strong>Hallazgos de Enfermería</strong><div class="ntf-checks">${CH('nfFind',FIND)}</div></div><div class="ntf-box"><strong>Educación</strong><div class="ntf-checks">${CH('nfEdu',EDU)}</div></div><div class="ntf-box"><strong>Alta de Enfermería</strong><div class="ntf-checks">${CH('nfDisc',DISC)}</div></div><div class="ntf-box"><label>Narrativa automática editable</label><textarea id="nfNarrative"></textarea><button type="button" class="ntf-btn" id="nfRegen">✨ Generar nuevamente</button></div><div id="nfStatus" class="ntf-status"></div><div class="ntf-actions"><button class="ntf-btn" id="nfSave">Guardar abierto</button><button class="ntf-btn main" id="nfClose">Guardar y cerrar</button></div></div>`;
document.querySelectorAll('.ntf-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.ntf-tab').forEach(x=>x.classList.toggle('on',x===b));update()});
document.querySelectorAll('.ntf input').forEach(x=>{if(x.id!=='nfNarrative')x.addEventListener('input',update);x.addEventListener('change',update)});document.querySelectorAll('.ntf input[type=checkbox]').forEach(x=>x.addEventListener('change',update));$('nfNarrative').addEventListener('input',()=>{$('nfNarrative').dataset.manual='1'});$('nfRegen').onclick=()=>{delete $('nfNarrative').dataset.manual;update()};$('nfSave').onclick=()=>save('open');$('nfClose').onclick=()=>save('closed');update()}
async function getCtx(){if(ctx&&sb)return ctx;const lib=await NT_loadSupabase(),c=window.NURSETRACK_SUPABASE||{};sb=lib.createClient(c.url,c.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});const u=(await sb.auth.getSession()).data?.session?.user;if(!u)throw Error('Sesión no disponible.');let r=await sb.from('nursetrack_company_users').select('company_id').eq('user_id',u.id).eq('active',true).limit(1),company=r.data?.[0]?.company_id;if(!company){r=await sb.from('nursetrack_account_memberships').select('company_id').eq('user_id',u.id).eq('status','active').limit(1);company=r.data?.[0]?.company_id}if(!company)throw Error('No hay compañía activa.');return ctx={user:u,company}}
async function save(state){const st=$('nfStatus');st.textContent='Guardando en la nube…';try{const c=await getCtx();if(!visitKey)visitKey='v4-'+mrn()+'-'+(crypto.randomUUID?crypto.randomUUID():Date.now());const names=patientName().split(/\s+/),payload={company_id:c.company,patient:{mrn:mrn(),firstName:names[0]||'',lastName:names.slice(1).join(' ')||'',preferredLanguage:'es',status:'active'},visit:{id:visitKey,visitDate:val('nfDate'),type:document.querySelector('.ntf-tab.on')?.dataset.type||TYPES[0],status:state,bp:val('nfBp'),pulse:val('nfPulse'),resp:val('nfResp'),temp:val('nfTemp'),spo2:val('nfSpo2'),weight:val('nfWeight'),height:val('nfHeight'),nursingNarrative:val('nfNarrative'),source:'v4-beta-fast'}};const r=await sb.rpc('nursetrack_sync_nursing_visit_payload',{p_payload:payload});if(r.error)throw r.error;st.textContent=state==='closed'?'Visita guardada y cerrada.':'Visita guardada.';if(state==='closed')visitKey=null}catch(e){st.textContent='No se pudo guardar: '+String(e?.message||e)}}
function open(type){visitKey=null;render(TYPES.includes(type)?type:TYPES[0])}
window.NT_V4_NURSING_FAST={open,version:'1.0.0'};
})();