(function(){
'use strict';
if(window.__NT_V4_PATIENT_TOOLS__) return;window.__NT_V4_PATIENT_TOOLS__=true;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let sb=null,ctx=null,patient=null,busy=false;
const QUESTIONS=[
 'Poco interés o placer en hacer cosas',
 'Sentirse decaído/a, deprimido/a o sin esperanza',
 'Dificultad para dormir, permanecer dormido/a o dormir demasiado',
 'Sentirse cansado/a o con poca energía',
 'Poco apetito o comer en exceso',
 'Sentirse mal consigo mismo/a o sentir que ha fallado',
 'Dificultad para concentrarse',
 'Moverse o hablar tan despacio que otros lo notan, o estar demasiado inquieto/a',
 'Pensamientos de que estaría mejor muerto/a o de hacerse daño'
];
const FREQ=['Nada','Varios días','Más de la mitad de los días','Casi todos los días'];
function area(){return document.getElementById('patientActionArea')}
function setArea(h){const a=area();if(a)a.innerHTML=h}
function addStyles(){if(document.getElementById('ntV4PatientToolsStyle'))return;const s=document.createElement('style');s.id='ntV4PatientToolsStyle';s.textContent='.ntv4-toolcard{background:#fff;border:1px solid #d8e6e8;border-radius:14px;padding:16px;margin-top:12px}.ntv4-q{display:grid;grid-template-columns:1fr 210px;gap:12px;align-items:center;border-bottom:1px solid #e5eeee;padding:10px 0}.ntv4-q:last-child{border-bottom:0}.ntv4-appt{display:grid;grid-template-columns:1fr .8fr .8fr .7fr;gap:10px;padding:10px 0;border-bottom:1px solid #e5eeee}.ntv4-appt:last-child{border-bottom:0}.ntv4-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ntv4-form .full{grid-column:1/-1}.ntv4-score{font-size:28px;font-weight:900}.ntv4-alert{background:#fff2f2;border:1px solid #e8bcbc;color:#853434;border-radius:12px;padding:12px;margin-top:10px}@media(max-width:700px){.ntv4-q,.ntv4-appt,.ntv4-form{grid-template-columns:1fr}.ntv4-form .full{grid-column:auto}}';(document.head||document.documentElement).appendChild(s)}
async function client(){if(sb)return sb;if(typeof window.NT_loadSupabase!=='function')throw new Error('Supabase no disponible');const lib=await window.NT_loadSupabase(),cfg=window.NURSETRACK_SUPABASE||{};sb=lib.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
async function getCtx(){await client();const s=await sb.auth.getSession(),u=s?.data?.session?.user;if(!u)throw new Error('Sesión no disponible');let company=null;let r=await sb.from('nursetrack_company_users').select('company_id').eq('user_id',u.id).eq('active',true).limit(1);if(r.data?.[0])company=r.data[0].company_id;if(!company){let m=await sb.from('nursetrack_account_memberships').select('company_id').eq('user_id',u.id).eq('status','active').limit(1);company=m.data?.[0]?.company_id||null}if(!company)throw new Error('No hay compañía activa');ctx={user:u,company};return ctx}
function mrn(){return (document.getElementById('patientMrn')?.textContent||'').replace(/^(MRN|Expediente)\s*:?-?\s*/i,'').trim()}
async function getPatient(){const c=await getCtx(),m=mrn();if(!m)throw new Error('Abre un paciente primero');const r=await sb.from('nursetrack_patients_v2').select('*').eq('company_id',c.company).ilike('mrn',m).is('deleted_at',null).limit(1);if(r.error)throw r.error;if(!r.data?.[0])throw new Error('Paciente activo no localizado');patient=r.data[0];return patient}
function head(p){return `<div class="ntv4-toolcard"><strong>${esc(p.first_name)} ${esc(p.last_name)}</strong> · Expediente ${esc(p.mrn||'')}</div>`}

async function openPHQ9(){try{const p=await getPatient();const c=ctx;const h=await sb.from('nursetrack_phq9').select('*').eq('company_id',c.company).eq('patient_id',p.id).order('screening_date',{ascending:false}).limit(8);if(h.error)throw h.error;setArea(`${head(p)}<div class="ntv4-toolcard"><h3>PHQ‑9</h3><div class="ntv4-muted">Evaluación nueva</div>${QUESTIONS.map((q,i)=>`<div class="ntv4-q"><div><strong>${i+1}.</strong> ${esc(q)}</div><select data-phq="q${i+1}">${FREQ.map((x,n)=>`<option value="${n}">${n} · ${esc(x)}</option>`).join('')}</select></div>`).join('')}<div style="margin-top:14px">Puntuación: <span id="ntv4PhqScore" class="ntv4-score">0</span></div><div id="ntv4PhqAlert"></div><label>Acción / referido</label><textarea id="ntv4PhqAction" placeholder="Acción tomada, referido o seguimiento"></textarea><label>Notas</label><textarea id="ntv4PhqNotes"></textarea><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button class="btn" id="ntv4SavePhq">Guardar PHQ‑9</button><button class="btn light" id="ntv4PrintPhq">Imprimir</button></div><div id="ntv4PhqStatus" class="status"></div></div><div class="ntv4-toolcard"><h3>Historial PHQ‑9</h3>${h.data?.length?h.data.map(x=>`<div class="ntv4-appt"><div>${esc(x.screening_date)}</div><div>Puntuación ${esc(x.total_score)}</div><div>${x.suicidal_ideation?'⚠ Ideación reportada':'Sin ideación reportada'}</div><div>${esc((x.created_at||'').slice(0,10))}</div></div>`).join(''):'<div class="ntv4-muted">No hay evaluaciones previas.</div>'}</div>`);area()?.querySelectorAll('[data-phq]').forEach(s=>s.addEventListener('change',score));document.getElementById('ntv4SavePhq')?.addEventListener('click',savePHQ9);document.getElementById('ntv4PrintPhq')?.addEventListener('click',printPHQ9);score()}catch(e){setArea(`<div class="ntv4-toolcard" style="color:#9b3d3d">${esc(e.message||e)}</div>`)}}
function score(){let total=0,q9=0;area()?.querySelectorAll('[data-phq]').forEach((s,i)=>{const v=Number(s.value)||0;total+=v;if(i===8)q9=v});const sc=document.getElementById('ntv4PhqScore');if(sc)sc.textContent=String(total);const a=document.getElementById('ntv4PhqAlert');if(a)a.innerHTML=q9>0?'<div class="ntv4-alert"><strong>Alerta clínica:</strong> la pregunta 9 tiene una respuesta mayor de cero. Requiere evaluación clínica y acción documentada.</div>':'';return{total,q9}}
async function savePHQ9(){if(busy)return;busy=true;const st=document.getElementById('ntv4PhqStatus');if(st)st.textContent='Guardando…';try{const c=await getCtx(),p=patient||await getPatient(),s=score(),vals={};area()?.querySelectorAll('[data-phq]').forEach(el=>vals[el.dataset.phq]=Number(el.value)||0);const row={company_id:c.company,patient_id:p.id,screening_date:new Date().toISOString().slice(0,10),...vals,total_score:s.total,suicidal_ideation:s.q9>0,action_taken:document.getElementById('ntv4PhqAction')?.value.trim()||null,notes:document.getElementById('ntv4PhqNotes')?.value.trim()||null,recorded_by:c.user.id};const r=await sb.from('nursetrack_phq9').insert(row).select('id').single();if(r.error)throw r.error;if(st){st.textContent='PHQ‑9 guardado.';st.style.color='#216b48'}setTimeout(openPHQ9,500)}catch(e){if(st){st.textContent=e.message||String(e);st.style.color='#9b3d3d'}}finally{busy=false}}
function printPHQ9(){const p=patient,s=score();if(!p)return;const vals=[...area().querySelectorAll('[data-phq]')].map(x=>Number(x.value)||0);const w=window.open('','_blank','noopener,noreferrer');if(!w)return;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>PHQ-9</title><style>body{font-family:Arial;margin:32px;color:#17343c}h1{font-size:22px}.row{padding:8px 0;border-bottom:1px solid #ddd}.score{font-size:24px;font-weight:bold;margin-top:16px}</style></head><body><h1>PHQ‑9</h1><div>${esc(p.first_name)} ${esc(p.last_name)} · Expediente ${esc(p.mrn||'')}</div>${QUESTIONS.map((q,i)=>`<div class="row">${i+1}. ${esc(q)} — <strong>${vals[i]} (${esc(FREQ[vals[i]])})</strong></div>`).join('')}<div class="score">Total: ${s.total}</div><p><strong>Acción:</strong> ${esc(document.getElementById('ntv4PhqAction')?.value||'')}</p><p><strong>Notas:</strong> ${esc(document.getElementById('ntv4PhqNotes')?.value||'')}</p></body></html>`);w.document.close();setTimeout(()=>w.print(),120)}

async function openAppointments(){try{const c=await getCtx(),p=await getPatient();const r=await sb.from('nursetrack_appointments').select('*').eq('company_id',c.company).eq('patient_id',p.id).order('appointment_at',{ascending:false}).limit(50);if(r.error)throw r.error;setArea(`${head(p)}<div class="ntv4-toolcard"><h3>Nueva cita</h3><div class="ntv4-form"><div><label>Fecha y hora</label><input id="ntv4ApptAt" type="datetime-local"></div><div><label>Tipo de visita</label><input id="ntv4ApptType" placeholder="Seguimiento"></div><div><label>Proveedor</label><input id="ntv4ApptProvider"></div><div><label>Localidad</label><input id="ntv4ApptLocation"></div><div><label><input id="ntv4ApptSms" type="checkbox" style="width:auto"> Recordatorio SMS</label></div><div><label><input id="ntv4ApptEmail" type="checkbox" style="width:auto"> Recordatorio email</label></div><div class="full"><label>Notas</label><textarea id="ntv4ApptNotes"></textarea></div></div><button class="btn" id="ntv4SaveAppt" style="margin-top:12px">Guardar cita</button><div id="ntv4ApptStatus" class="status"></div></div><div class="ntv4-toolcard"><h3>Citas del paciente</h3>${r.data?.length?r.data.map(x=>`<div class="ntv4-appt"><div><strong>${esc(new Date(x.appointment_at).toLocaleString())}</strong><div class="ntv4-muted">${esc(x.visit_type||'')}</div></div><div>${esc(x.provider_name||'')}</div><div>${esc(x.location_name||'')}</div><div>${esc(x.status||'')}</div></div>`).join(''):'<div class="ntv4-muted">No hay citas registradas.</div>'}</div>`);document.getElementById('ntv4SaveAppt')?.addEventListener('click',saveAppointment)}catch(e){setArea(`<div class="ntv4-toolcard" style="color:#9b3d3d">${esc(e.message||e)}</div>`)}}
async function saveAppointment(){if(busy)return;busy=true;const st=document.getElementById('ntv4ApptStatus');if(st)st.textContent='Guardando…';try{const c=await getCtx(),p=patient||await getPatient(),raw=document.getElementById('ntv4ApptAt')?.value;if(!raw)throw new Error('Selecciona fecha y hora');const row={company_id:c.company,patient_id:p.id,appointment_at:new Date(raw).toISOString(),visit_type:document.getElementById('ntv4ApptType')?.value.trim()||null,provider_name:document.getElementById('ntv4ApptProvider')?.value.trim()||null,location_name:document.getElementById('ntv4ApptLocation')?.value.trim()||null,status:'scheduled',reminder_sms:!!document.getElementById('ntv4ApptSms')?.checked,reminder_email:!!document.getElementById('ntv4ApptEmail')?.checked,reminder_status:'pending',notes:document.getElementById('ntv4ApptNotes')?.value.trim()||null,created_by:c.user.id};const r=await sb.from('nursetrack_appointments').insert(row).select('id').single();if(r.error)throw r.error;if(st){st.textContent='Cita guardada.';st.style.color='#216b48'}setTimeout(openAppointments,500)}catch(e){if(st){st.textContent=e.message||String(e);st.style.color='#9b3d3d'}}finally{busy=false}}

function intercept(e){const ph=e.target.closest?.('.patient-action[data-action="phq9"]'),ap=e.target.closest?.('.patient-action[data-action="appointments"]');if(ph){e.preventDefault();e.stopImmediatePropagation();openPHQ9()}if(ap){e.preventDefault();e.stopImmediatePropagation();openAppointments()}}
function boot(){addStyles();document.addEventListener('click',intercept,true);window.NT_V4_PATIENT_TOOLS={openPHQ9,openAppointments,version:'1.0.0'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
