(function(){
'use strict';
if(window.__NT_V4_PATIENT_EDITOR__)return;window.__NT_V4_PATIENT_EDITOR__=true;
const $=id=>document.getElementById(id),E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let sb=null,ctx=null,patient=null,busy=false;
function css(){if($('ntPatientEditorStyle'))return;const s=document.createElement('style');s.id='ntPatientEditorStyle';s.textContent=`.ntpe{margin-top:14px;background:#fff;border:1px solid #d8e6e8;border-radius:16px;padding:16px}.ntpe h3{margin:0 0 4px;color:#173e61}.ntpe-note{font-size:12px;color:#6f858b;margin-bottom:12px}.ntpe-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.ntpe-grid .wide{grid-column:span 2}.ntpe label{font-weight:800;color:#234a62}.ntpe input,.ntpe select{width:100%;padding:10px;border:1px solid #cbdde3;border-radius:9px;background:#fff}.ntpe input[readonly]{background:#f2f6f7;color:#667}.ntpe-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.ntpe-status{min-height:20px;margin-top:9px;font-size:13px}@media(max-width:700px){.ntpe-grid{grid-template-columns:1fr}.ntpe-grid .wide{grid-column:auto}}`;document.head.appendChild(s)}
async function client(){if(sb)return sb;if(typeof window.NT_loadSupabase!=='function')throw Error('Supabase no disponible');const lib=await NT_loadSupabase(),c=window.NURSETRACK_SUPABASE||{};if(!c.url||!c.publishableKey)throw Error('Configuración de nube no disponible');return sb=lib.createClient(c.url,c.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}})}
async function context(){await client();const ses=await sb.auth.getSession(),u=ses?.data?.session?.user;if(!u)throw Error('Sesión no disponible');let r=await sb.from('nursetrack_company_users').select('company_id').eq('user_id',u.id).eq('active',true).limit(1),company=r.data?.[0]?.company_id||null;if(!company){r=await sb.from('nursetrack_account_memberships').select('company_id').eq('user_id',u.id).eq('status','active').limit(1);company=r.data?.[0]?.company_id||null}if(!company)throw Error('No hay compañía activa');return ctx={user:u,company}}
function currentMrn(){return String($('patientMrn')?.textContent||'').replace(/^(MRN|Expediente)\s*:?-?\s*/i,'').trim()}
async function getPatient(){const c=await context(),m=currentMrn();if(!m)throw Error('Abre un paciente primero');const r=await sb.from('nursetrack_patients_v2').select('*').eq('company_id',c.company).ilike('mrn',m).is('deleted_at',null).limit(1);if(r.error)throw r.error;if(!r.data?.[0])throw Error('Paciente activo no localizado');return patient=r.data[0]}
function v(id){return $(id)?.value?.trim?.()||''}
function sameAddress(){if($('ntpeSame')?.checked){$('ntpePostal').value=$('ntpeResidential').value;$('ntpePostal').disabled=true}else $('ntpePostal').disabled=false}
async function open(){css();const a=$('patientActionArea');if(!a)return;try{const p=await getPatient();a.innerHTML=`<div class="ntpe"><h3>✏️ Editar expediente</h3><div class="ntpe-note">Actualiza el mismo expediente del paciente. El MRN queda bloqueado para evitar duplicados o cambios de identidad accidentales.</div><div class="ntpe-grid"><div><label>Expediente / MRN</label><input id="ntpeMrn" value="${E(p.mrn||'')}" readonly></div><div><label>Nombre *</label><input id="ntpeFirst" value="${E(p.first_name||'')}"></div><div><label>Segundo nombre</label><input id="ntpeMiddle" value="${E(p.middle_name||'')}"></div><div><label>Apellido *</label><input id="ntpeLast" value="${E(p.last_name||'')}"></div><div><label>Fecha de nacimiento</label><input id="ntpeDob" type="date" value="${E((p.date_of_birth||'').slice(0,10))}"></div><div><label>Sexo</label><select id="ntpeSex"><option value="">—</option>${['Femenino','Masculino','Otro','Prefiere no indicar'].map(x=>`<option ${String(p.sex||'')===x?'selected':''}>${x}</option>`).join('')}</select></div><div><label>Teléfono</label><input id="ntpePhone" inputmode="tel" value="${E(p.phone||'')}"></div><div><label>Email</label><input id="ntpeEmail" type="email" value="${E(p.email||'')}"></div><div><label>Idioma</label><select id="ntpeLang"><option value="es" ${String(p.preferred_language||'es')==='es'?'selected':''}>Español</option><option value="en" ${String(p.preferred_language||'')==='en'?'selected':''}>English</option></select></div><div><label>Ciudad</label><input id="ntpeCity" value="${E(p.city||'')}"></div><div class="wide"><label>Dirección residencial</label><input id="ntpeResidential" value="${E(p.residential_address||'')}"></div><div class="wide"><label>Dirección postal</label><input id="ntpePostal" value="${E(p.postal_address||'')}"></div><div><label><input id="ntpeSame" type="checkbox" style="width:auto" ${p.postal_same_as_residential?'checked':''}> Postal igual a residencial</label></div><div><label>Educación</label><input id="ntpeEducation" value="${E(p.education_level||'')}"></div></div><div class="ntpe-actions"><button class="btn" id="ntpeSave" type="button">Guardar cambios</button><button class="btn light" id="ntpeCancel" type="button">Cancelar</button></div><div id="ntpeStatus" class="ntpe-status"></div></div>`;$('ntpeSame').onchange=sameAddress;$('ntpeResidential').oninput=()=>{if($('ntpeSame').checked)$('ntpePostal').value=$('ntpeResidential').value};sameAddress();$('ntpeSave').onclick=save;$('ntpeCancel').onclick=()=>{a.innerHTML=''};}catch(e){a.innerHTML=`<div class="ntpe" style="color:#933">${E(e.message||e)}</div>`}}
async function save(){if(busy||!patient)return;busy=true;const st=$('ntpeStatus');try{if(!v('ntpeFirst')||!v('ntpeLast'))throw Error('Nombre y apellido son requeridos.');if(st){st.textContent='Guardando cambios…';st.style.color=''}const c=ctx||await context(),changes={first_name:v('ntpeFirst'),middle_name:v('ntpeMiddle')||null,last_name:v('ntpeLast'),date_of_birth:v('ntpeDob')||null,phone:v('ntpePhone')||null,email:v('ntpeEmail')||null,preferred_language:v('ntpeLang')||'es',sex:v('ntpeSex')||null,city:v('ntpeCity')||null,residential_address:v('ntpeResidential')||null,postal_address:($('ntpeSame')?.checked?v('ntpeResidential'):v('ntpePostal'))||null,postal_same_as_residential:!!$('ntpeSame')?.checked,education_level:v('ntpeEducation')||null,updated_at:new Date().toISOString()};const r=await sb.from('nursetrack_patients_v2').update(changes).eq('id',patient.id).eq('company_id',c.company).is('deleted_at',null).select('*').single();if(r.error)throw r.error;patient=r.data;if(st){st.textContent='Expediente actualizado correctamente.';st.style.color='#216b48'}const name=[patient.first_name,patient.middle_name,patient.last_name].filter(Boolean).join(' ');if($('patientName'))$('patientName').textContent=name;try{const active={id:patient.id,mrn:patient.mrn,name,company_id:c.company,updated_at:new Date().toISOString()};sessionStorage.setItem('nursetrack_active_patient',JSON.stringify(active));window.NT_ACTIVE_PATIENT=active;window.dispatchEvent(new CustomEvent('nursetrack:patient-selected',{detail:active}))}catch(_){}setTimeout(refreshCurrent,450)}catch(e){if(st){st.textContent='No se pudo guardar: '+(e.message||e);st.style.color='#933'}}finally{busy=false}}
function refreshCurrent(){const m=patient?.mrn||currentMrn(),q=$('patientSearch');$('patientActionArea').innerHTML='';$('patientPanel')?.classList.add('hidden');$('homePanel')?.classList.remove('hidden');if(q)q.value=m;$('searchBtn')?.click();let n=0,t=setInterval(()=>{const rows=[...document.querySelectorAll('#patientResults .patient-row')];const row=rows.find(x=>x.textContent.includes(m))||rows[0];if(row){clearInterval(t);row.click()}else if(++n>25)clearInterval(t)},120)}
function addButton(){const panel=$('patientPanel');if(!panel||panel.classList.contains('hidden')||$('ntEditPatientBtn'))return;const head=panel.querySelector('.patient-head');if(!head)return;const newVisit=$('newVisitBtn'),b=document.createElement('button');b.id='ntEditPatientBtn';b.type='button';b.className='btn light';b.textContent='✏️ Editar expediente';b.onclick=open;if(newVisit?.parentNode===head){const wrap=document.createElement('div');wrap.style.cssText='display:flex;gap:8px;flex-wrap:wrap';head.insertBefore(wrap,newVisit);wrap.appendChild(b);wrap.appendChild(newVisit)}else head.appendChild(b)}
const obs=new MutationObserver(addButton);function boot(){css();addButton();const p=$('patientPanel');if(p)obs.observe(p,{attributes:true,subtree:true,childList:true,attributeFilter:['class']});window.NT_V4_PATIENT_EDITOR={open,version:'1.0.0'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();