(function(){
'use strict';
if(window.__NT_V4_SMART_NURSING__) return;
window.__NT_V4_SMART_NURSING__=true;

const KEYS=['nursing_initial','nursing_followup','nursing_reevaluation','nursing_readmission'];
const META={
  nursing_initial:{label:'Evaluación inicial',visitType:'Evaluación inicial'},
  nursing_followup:{label:'Seguimiento',visitType:'Seguimiento'},
  nursing_reevaluation:{label:'Reevaluación',visitType:'Reevaluación'},
  nursing_readmission:{label:'Readmisión',visitType:'Readmisión'}
};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
let sb=null,ctx=null,patient=null,templates={},activeKey='nursing_initial',visitId=null,busy=false;

function styles(){
 if($('ntSmartNursingStyle')) return;
 const st=document.createElement('style');st.id='ntSmartNursingStyle';st.textContent=`
 .ntn-wrap{margin-top:14px}.ntn-card{background:#fff;border:1px solid #d8e6e8;border-radius:18px;padding:17px;box-shadow:0 5px 18px rgba(25,67,88,.05)}
 .ntn-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;flex-wrap:wrap}.ntn-head h3{margin:0;color:#173e61}.ntn-muted{color:#6d838f;font-size:13px}
 .ntn-tabs{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:15px 0}.ntn-tab{border:1px solid #cfe2e8;background:#f7fbfd;color:#315a70;border-radius:12px;padding:10px;font-weight:800}.ntn-tab.active{background:#0b8fa3;color:#fff;border-color:#0b8fa3}
 .ntn-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.ntn-field{background:#fbfdfe;border:1px solid #e0ecef;border-radius:12px;padding:11px}.ntn-field.wide{grid-column:span 2}.ntn-field.full{grid-column:1/-1}.ntn-field label{display:block;font-weight:800;color:#234a62;margin-bottom:6px}.ntn-field small{display:block;color:#71868d;margin:0 0 7px;line-height:1.35}.ntn-field input,.ntn-field select,.ntn-field textarea{width:100%;border:1px solid #cbdde3;border-radius:10px;padding:10px;background:#fff}.ntn-field textarea{min-height:92px;resize:vertical}
 .ntn-checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.ntn-check{display:flex;align-items:flex-start;gap:8px;padding:8px;border:1px solid #e2ecef;border-radius:9px;background:#fff;font-size:13px}.ntn-check input{width:auto;margin-top:2px}
 .ntn-section{margin-top:12px;border-top:1px solid #e4edef;padding-top:12px}.ntn-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.ntn-btn{border:0;border-radius:11px;padding:10px 14px;font-weight:800;cursor:pointer}.ntn-btn.primary{background:#0b8fa3;color:#fff}.ntn-btn.secondary{background:#1e5fa8;color:#fff}.ntn-btn.light{background:#edf5f6;color:#244d61;border:1px solid #d3e3e7}.ntn-status{min-height:20px;margin-top:10px;font-size:13px}.ntn-ok{color:#216b48}.ntn-err{color:#993b3b}.ntn-alert{padding:10px 12px;border:1px solid #efd7a6;background:#fff8e9;color:#72541d;border-radius:10px;margin-top:8px;font-size:13px}
 @media(max-width:900px){.ntn-tabs{grid-template-columns:1fr 1fr}.ntn-grid{grid-template-columns:1fr 1fr}.ntn-field.full{grid-column:1/-1}}
 @media(max-width:560px){.ntn-tabs,.ntn-grid,.ntn-checks{grid-template-columns:1fr}.ntn-field.wide,.ntn-field.full{grid-column:auto}}
 `;document.head.appendChild(st);
}
async function client(){if(sb)return sb;if(typeof NT_loadSupabase!=='function')throw new Error('Supabase no disponible.');const lib=await NT_loadSupabase(),cfg=window.NURSETRACK_SUPABASE||{};sb=lib.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
async function context(){if(ctx)return ctx;await client();const s=await sb.auth.getSession(),u=s?.data?.session?.user;if(!u)throw new Error('Sesión no disponible.');let company=null;let r=await sb.from('nursetrack_company_users').select('company_id').eq('user_id',u.id).eq('active',true).limit(1);company=r.data?.[0]?.company_id||null;if(!company){let m=await sb.from('nursetrack_account_memberships').select('company_id').eq('user_id',u.id).eq('status','active').limit(1);company=m.data?.[0]?.company_id||null}if(!company)throw new Error('No hay compañía activa.');ctx={user:u,company};return ctx}
function mrn(){return String($('patientMrn')?.textContent||'').replace(/^(MRN|Expediente)\s*:?-?\s*/i,'').trim()}
async function resolvePatient(){const c=await context(),m=mrn();if(!m)throw new Error('Selecciona un paciente primero.');const r=await sb.from('nursetrack_patients_v2').select('*').eq('company_id',c.company).ilike('mrn',m).is('deleted_at',null).limit(1);if(r.error)throw r.error;if(!r.data?.[0])throw new Error('No pude identificar el paciente activo.');patient=r.data[0];return patient}
async function loadTemplates(){const c=await context();const r=await sb.from('nursetrack_templates').select('id,company_id,template_key,template_name,schema_json,status,current_version').in('template_key',KEYS).eq('language','es').eq('status','published').is('deleted_at',null).or(`company_id.is.null,company_id.eq.${c.company}`);if(r.error)throw r.error;templates={};(r.data||[]).forEach(t=>{const old=templates[t.template_key];if(!old||(!old.company_id&&t.company_id))templates[t.template_key]=t});const missing=KEYS.filter(k=>!templates[k]);if(missing.length)throw new Error('Faltan plantillas de Enfermería publicadas: '+missing.join(', '));return templates}
function schema(k=activeKey){return templates[k]?.schema_json||{}}
function help(field){return esc(schema()[field]||'')}
function fullName(){return [patient?.first_name,patient?.middle_name,patient?.last_name].filter(Boolean).join(' ')}
function calcBMI(lb,inch){const w=Number(lb),h=Number(inch);if(!(w>0&&h>0))return'';return (703*w/(h*h)).toFixed(1)}
function bmiClass(v){const n=Number(v);if(!n)return'';if(n<18.5)return'Bajo peso';if(n<25)return'Normal';if(n<30)return'Sobrepeso';return'Obesidad'}
function checked(name){return [...document.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value)}
function val(id){return $(id)?.value?.trim?.()||''}
function educationSentence(){const a=checked('ntnEdu');if(!a.length)return val('ntnEducation');return `Se brinda educación sobre ${a.join(', ')}. ${val('ntnEducation')}`.trim()}
function dischargeSentence(){const p=[];if($('ntnUnderstood')?.checked)p.push('educación comprendida');if($('ntnStable')?.checked)p.push('paciente sale estable');const extra=val('ntnDischarge');if(extra)p.push(extra);return p.length?p.join('; ').replace(/^./,c=>c.toUpperCase())+'.':''}
function narrative(){const bmi=calcBMI(val('ntnWeight'),val('ntnHeight')),parts=[];parts.push(`${META[activeKey].visitType} de Enfermería a ${fullName()||'paciente'}.`);const vit=[];if(val('ntnBp'))vit.push('PA '+val('ntnBp')+' mmHg');if(val('ntnPulse'))vit.push('pulso '+val('ntnPulse')+' lpm');if(val('ntnResp'))vit.push('respiración '+val('ntnResp')+' rpm');if(val('ntnTemp'))vit.push('temperatura '+val('ntnTemp')+' °F');if(val('ntnSpo2'))vit.push('SpO₂ '+val('ntnSpo2')+'%');if(val('ntnWeight'))vit.push('peso '+val('ntnWeight')+' lb');if(val('ntnHeight'))vit.push('estatura '+val('ntnHeight')+' in');if(bmi)vit.push('IMC '+bmi+' ('+bmiClass(bmi)+')');if(vit.length)parts.push('Signos vitales: '+vit.join(', ')+'.');if(val('ntnAssessment'))parts.push('Evaluación/Hallazgos: '+val('ntnAssessment'));const edu=educationSentence();if(edu)parts.push(edu);if(val('ntnIntervention'))parts.push('Intervenciones: '+val('ntnIntervention'));if(val('ntnPlan'))parts.push('Plan de cuidado: '+val('ntnPlan'));if($('ntnPhqEnable')?.checked&&val('ntnPhq')){const score=Number(val('ntnPhq'));parts.push('PHQ-9: '+score+'.'+(score>=5?' Se indica seguimiento/referencia a Salud Mental según protocolo.':''))}const d=dischargeSentence();if(d)parts.push('Alta de Enfermería: '+d);return parts.join(' ')}
function updateNarrative(){const ta=$('ntnNarrative');if(ta&&!ta.dataset.edited)ta.value=narrative();const bmi=calcBMI(val('ntnWeight'),val('ntnHeight'));if($('ntnBmi'))$('ntnBmi').value=bmi?`${bmi} · ${bmiClass(bmi)}`:'';const phq=$('ntnPhqAlert');if(phq){const n=Number(val('ntnPhq'));phq.style.display=$('ntnPhqEnable')?.checked&&n>=5?'block':'none'}}
function render(){styles();const out=$('patientActionArea');if(!out)return;const s=schema();const today=new Date().toISOString().slice(0,10);out.innerHTML=`<div class="ntn-wrap"><div class="ntn-card"><div class="ntn-head"><div><h3>🩺 Enfermería — Plantilla moderna e inteligente</h3><div class="ntn-muted">${esc(fullName())} · Expediente ${esc(patient?.mrn||'—')}</div></div><div class="ntn-muted">Plantillas publicadas · v${esc(templates[activeKey]?.current_version||1)}</div></div>
<div class="ntn-tabs">${KEYS.map(k=>`<button type="button" class="ntn-tab ${k===activeKey?'active':''}" data-ntn-tab="${k}">${esc(META[k].label)}</button>`).join('')}</div>
<div class="ntn-grid">
<div class="ntn-field"><label>Fecha</label><input id="ntnDate" type="date" value="${today}"></div>
<div class="ntn-field"><label>Presión arterial</label><input id="ntnBp" placeholder="120/80"></div>
<div class="ntn-field"><label>Pulso</label><input id="ntnPulse" inputmode="numeric"></div>
<div class="ntn-field"><label>Respiración</label><input id="ntnResp" inputmode="numeric"></div>
<div class="ntn-field"><label>Temperatura °F</label><input id="ntnTemp" inputmode="decimal"></div>
<div class="ntn-field"><label>SpO₂ %</label><input id="ntnSpo2" inputmode="numeric"></div>
<div class="ntn-field"><label>Peso lb</label><input id="ntnWeight" inputmode="decimal"></div>
<div class="ntn-field"><label>Estatura in</label><input id="ntnHeight" inputmode="decimal"></div>
<div class="ntn-field wide"><label>IMC automático</label><input id="ntnBmi" readonly placeholder="Se calcula con peso y estatura"></div>
<div class="ntn-field full"><label>${activeKey==='nursing_reevaluation'?'Reevaluación':'Evaluación / Hallazgos'}</label><small>${help(activeKey==='nursing_reevaluation'?'reassessment':(s.findings?'findings':'assessment'))}</small><textarea id="ntnAssessment" placeholder="Documente hallazgos clínicos relevantes..."></textarea></div>
<div class="ntn-field full"><label>Educación</label><small>${help('education')}</small><div class="ntn-checks">${['adherencia a medicamentos','signos y síntomas de alarma','nutrición e hidratación','hipertensión','IMC y peso saludable','prevención de caídas','vacunas','seguimiento de citas','salud sexual y prevención'].map(x=>`<label class="ntn-check"><input type="checkbox" name="ntnEdu" value="${esc(x)}"><span>${esc(x)}</span></label>`).join('')}</div><textarea id="ntnEducation" style="margin-top:8px" placeholder="Otra educación o detalle adicional..."></textarea></div>
<div class="ntn-field full"><label>Intervenciones de Enfermería</label><small>${help('intervention')||'Intervenciones realizadas y coordinación.'}</small><textarea id="ntnIntervention" placeholder="Intervenciones, coordinación, referidos..."></textarea></div>
<div class="ntn-field full"><label>Plan de cuidado / Próxima visita</label><small>${help('plan')}</small><textarea id="ntnPlan" placeholder="Plan, seguimiento, referidos y próxima visita..."></textarea></div>
<div class="ntn-field full"><label class="ntn-check"><input id="ntnPhqEnable" type="checkbox"><span>Activar PHQ-9 cuando corresponda</span></label><small>${help('phq9')||'PHQ-9 opcional.'}</small><input id="ntnPhq" type="number" min="0" max="27" placeholder="Puntuación 0–27" disabled><div id="ntnPhqAlert" class="ntn-alert" style="display:none">PHQ-9 ≥ 5: documentar seguimiento/referencia a Salud Mental según protocolo.</div></div>
<div class="ntn-field full"><label>Alta de Enfermería</label><small>${help('discharge_note')}</small><div class="ntn-checks"><label class="ntn-check"><input id="ntnUnderstood" type="checkbox" checked><span>Educación comprendida</span></label><label class="ntn-check"><input id="ntnStable" type="checkbox" checked><span>Paciente sale estable</span></label></div><textarea id="ntnDischarge" style="margin-top:8px" placeholder="Detalle adicional de alta si aplica..."></textarea></div>
<div class="ntn-field full"><label>Narrativa automática editable</label><textarea id="ntnNarrative" style="min-height:150px"></textarea><div class="ntn-actions"><button type="button" class="ntn-btn light" id="ntnRegenerate">✨ Generar nuevamente</button></div></div>
</div><div id="ntnStatus" class="ntn-status"></div><div class="ntn-actions"><button type="button" class="ntn-btn secondary" id="ntnSave">Guardar abierto</button><button type="button" class="ntn-btn primary" id="ntnClose">Guardar y cerrar</button><button type="button" class="ntn-btn light" id="ntnPrint">Imprimir</button><button type="button" class="ntn-btn light" id="ntnCancel">Cancelar</button></div></div></div>`;
 bind();updateNarrative();
}
function bind(){document.querySelectorAll('[data-ntn-tab]').forEach(b=>b.onclick=()=>{activeKey=b.dataset.ntnTab;visitId=null;render()});['ntnBp','ntnPulse','ntnResp','ntnTemp','ntnSpo2','ntnWeight','ntnHeight','ntnAssessment','ntnEducation','ntnIntervention','ntnPlan','ntnPhq','ntnDischarge'].forEach(id=>$(id)?.addEventListener('input',updateNarrative));document.querySelectorAll('input[name="ntnEdu"],#ntnUnderstood,#ntnStable').forEach(el=>el.addEventListener('change',updateNarrative));$('ntnPhqEnable').onchange=()=>{$('ntnPhq').disabled=!$('ntnPhqEnable').checked;if(!$('ntnPhqEnable').checked)$('ntnPhq').value='';updateNarrative()};$('ntnNarrative').oninput=()=>{$('ntnNarrative').dataset.edited='1'};$('ntnRegenerate').onclick=()=>{delete $('ntnNarrative').dataset.edited;updateNarrative()};$('ntnSave').onclick=()=>save('open');$('ntnClose').onclick=()=>save('closed');$('ntnPrint').onclick=printForm;$('ntnCancel').onclick=()=>document.getElementById('backPatientBtn')?.click()}
function status(t,type=''){const el=$('ntnStatus');if(!el)return;el.textContent=t||'';el.className='ntn-status '+(type==='ok'?'ntn-ok':type==='err'?'ntn-err':'')}
function makeVisitId(){if(!visitId)visitId='v4-smart-'+patient.id+'-'+(crypto.randomUUID?crypto.randomUUID():Date.now());return visitId}
async function save(state){if(busy)return;busy=true;try{status('Guardando en la nube…');const c=await context();const payload={company_id:c.company,patient:{mrn:patient.mrn||'',firstName:patient.first_name||'',lastName:patient.last_name||'',dob:patient.date_of_birth||'',phone:patient.phone||'',email:patient.email||'',preferredLanguage:patient.preferred_language||'es',status:patient.status||'active'},visit:{id:makeVisitId(),visitDate:val('ntnDate'),type:META[activeKey].visitType,status,bp:val('ntnBp'),pulse:val('ntnPulse'),resp:val('ntnResp'),temp:val('ntnTemp'),spo2:val('ntnSpo2'),weight:val('ntnWeight'),height:val('ntnHeight'),bmi:calcBMI(val('ntnWeight'),val('ntnHeight')),assessment:val('ntnAssessment'),education:educationSentence(),education_topics:checked('ntnEdu'),intervention:val('ntnIntervention'),plan:val('ntnPlan'),phq9_enabled:!!$('ntnPhqEnable')?.checked,phq9_score:val('ntnPhq'),discharge_note:dischargeSentence(),nursingNarrative:val('ntnNarrative')||narrative(),template_key:activeKey,template_id:templates[activeKey]?.id,template_version:templates[activeKey]?.current_version||1,source:'v4-beta-smart-nursing'}};const r=await sb.rpc('nursetrack_sync_nursing_visit_payload',{p_payload:payload});if(r.error)throw r.error;status(state==='closed'?'Visita guardada y cerrada.':'Visita guardada. Puedes continuar editando.','ok');if(state==='closed'){visitId=null;setTimeout(()=>document.getElementById('backPatientBtn')?.click(),450)}}catch(e){status('No se pudo guardar: '+(e.message||String(e)),'err')}finally{busy=false}}
function printForm(){const w=window.open('','_blank','noopener,noreferrer');if(!w)return status('El navegador bloqueó la ventana de impresión.','err');const title=META[activeKey].label;const html=`<!doctype html><html><head><meta charset="utf-8"><title>Enfermería - ${esc(title)}</title><style>body{font-family:Arial,sans-serif;color:#17343c;margin:28px}h1{font-size:20px;margin:0}h2{font-size:16px;border-bottom:1px solid #ccdfe3;padding-bottom:6px;margin-top:20px}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:2px solid #0b8fa3;padding-bottom:12px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.box{border:1px solid #d6e4e7;border-radius:8px;padding:9px}.full{grid-column:1/-1}.label{font-size:11px;color:#6d838f}.value{white-space:pre-wrap;margin-top:3px}@media print{body{margin:.45in}}</style></head><body><div class="head"><div><h1>NurseTrack One</h1><div>Enfermería · ${esc(title)}</div></div><div>${esc(fullName())}<br>Expediente ${esc(patient.mrn||'')}</div></div><h2>Signos vitales</h2><div class="grid">${[['PA',val('ntnBp')],['Pulso',val('ntnPulse')],['Respiración',val('ntnResp')],['Temperatura °F',val('ntnTemp')],['SpO₂ %',val('ntnSpo2')],['Peso lb',val('ntnWeight')],['Estatura in',val('ntnHeight')],['IMC',$('ntnBmi')?.value||'']].map(x=>`<div class="box"><div class="label">${esc(x[0])}</div><div class="value">${esc(x[1])}</div></div>`).join('')}</div><h2>Evaluación / Hallazgos</h2><div class="box"><div class="value">${esc(val('ntnAssessment'))}</div></div><h2>Educación</h2><div class="box"><div class="value">${esc(educationSentence())}</div></div><h2>Intervenciones</h2><div class="box"><div class="value">${esc(val('ntnIntervention'))}</div></div><h2>Plan de cuidado</h2><div class="box"><div class="value">${esc(val('ntnPlan'))}</div></div>${$('ntnPhqEnable')?.checked?`<h2>PHQ-9</h2><div class="box"><div class="value">${esc(val('ntnPhq'))}</div></div>`:''}<h2>Alta de Enfermería</h2><div class="box"><div class="value">${esc(dischargeSentence())}</div></div><h2>Narrativa</h2><div class="box"><div class="value">${esc(val('ntnNarrative'))}</div></div><script>window.onload=()=>{window.print()}<\/script></body></html>`;w.document.open();w.document.write(html);w.document.close()}
async function open(){if(busy)return;busy=true;try{styles();status('');await context();await resolvePatient();await loadTemplates();activeKey='nursing_initial';visitId=null;render()}catch(e){const out=$('patientActionArea');if(out)out.innerHTML=`<div class="ntn-card ntn-err">${esc(e.message||String(e))}</div>`}finally{busy=false}}
function target(e){const t=e.target?.closest?.('.patient-action[data-action="nursing"],#newVisitBtn');return t||null}
document.addEventListener('click',e=>{if(!target(e))return;e.preventDefault();e.stopImmediatePropagation();open()},true);
window.NT_V4_SMART_NURSING={open,version:'1.0.0'};
})();
