(function(){
'use strict';
if(window.__NT_V4_STORAGE__)return;window.__NT_V4_STORAGE__=true;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));let sb=null,ctx=null,patient=null,busy=false;
function style(){if($('ntV4StorageStyle'))return;const s=document.createElement('style');s.id='ntV4StorageStyle';s.textContent='.ntv4-store{background:#fff;border:1px solid #d8e6e8;border-radius:14px;padding:16px;margin-top:12px}.ntv4-storegrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ntv4-storegrid .full{grid-column:1/-1}.ntv4-storetable{width:100%;border-collapse:collapse}.ntv4-storetable th,.ntv4-storetable td{padding:8px;border-bottom:1px solid #e5eeee;text-align:left;font-size:12px}.ntv4-storeactions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}@media(max-width:700px){.ntv4-storegrid{grid-template-columns:1fr}.ntv4-storegrid .full{grid-column:auto}.ntv4-storetable{display:block;overflow:auto}}';(document.head||document.documentElement).appendChild(s)}
async function client(){if(sb)return sb;if(typeof window.NT_loadSupabase!=='function')throw new Error('Supabase no disponible');const lib=await window.NT_loadSupabase(),cfg=window.NURSETRACK_SUPABASE||{};sb=lib.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
async function context(){await client();const ses=await sb.auth.getSession(),u=ses?.data?.session?.user;if(!u)throw new Error('Sesión no disponible');let company=null;const cu=await sb.from('nursetrack_company_users').select('company_id').eq('user_id',u.id).eq('active',true).limit(1);if(cu.data?.[0])company=cu.data[0].company_id;if(!company)throw new Error('No hay compañía activa');ctx={user:u,company};return ctx}
function globalShell(title){['homePanel','modulesPanel','placeholderPanel'].forEach(id=>$(id)?.classList.add('hidden'));$('patientPanel')?.classList.remove('hidden');if($('patientName'))$('patientName').textContent=title;if($('patientMrn'))$('patientMrn').textContent='';if($('patientDemographics'))$('patientDemographics').innerHTML='';const a=document.querySelector('#patientPanel .actions');if(a)a.style.display='none';if($('newVisitBtn'))$('newVisitBtn').style.display='none';if($('pageTitle'))$('pageTitle').textContent=title;if($('patientActionArea'))$('patientActionArea').innerHTML=''}
function area(){return $('patientActionArea')}
function cleanName(name){return String(name||'archivo').normalize('NFKD').replace(/[^a-zA-Z0-9._-]+/g,'_').replace(/^_+|_+$/g,'').slice(-120)||'archivo'}
function uid(){return (crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2))}
function ext(name){const p=String(name||'').toLowerCase().split('.');return p.length>1?p.pop():''}
async function signed(bucket,path){const r=await sb.storage.from(bucket).createSignedUrl(path,120);if(r.error)throw r.error;window.open(r.data.signedUrl,'_blank','noopener,noreferrer')}
async function uploadWithMeta(bucket,path,file,table,row){const up=await sb.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type||undefined,cacheControl:'3600'});if(up.error)throw up.error;const ins=await sb.from(table).insert({...row,storage_path:path});if(ins.error){await sb.storage.from(bucket).remove([path]);throw ins.error}return path}
async function openPersonal(){try{style();const c=await context(),[docs,files,xls]=await Promise.all([sb.from('nursetrack_personal_documents').select('id,title,category').eq('user_id',c.user.id).order('updated_at',{ascending:false}),sb.from('nursetrack_personal_document_files').select('*').eq('user_id',c.user.id).order('created_at',{ascending:false}),sb.from('nursetrack_excel_documents').select('*').eq('company_id',c.company).eq('created_by',c.user.id).order('updated_at',{ascending:false})]);if(docs.error)throw docs.error;if(files.error)throw files.error;if(xls.error)throw xls.error;globalShell('Mis archivos');area().innerHTML=`<div class="ntv4-store"><h3>📎 Adjuntar archivo a Mis documentos</h3><div class="ntv4-storegrid"><div><label>Documento</label><select id="ntv4StoreDoc">${(docs.data||[]).map(d=>`<option value="${d.id}">${esc(d.title||'Documento')}</option>`).join('')}</select></div><div><label>Archivo (máx. 25 MB)</label><input id="ntv4StorePersonalFile" type="file"></div></div><div class="ntv4-storeactions"><button class="btn" id="ntv4StorePersonalUpload">Subir archivo</button></div><div id="ntv4StorePersonalStatus" class="status"></div>${!(docs.data||[]).length?'<div class="notice">Crea primero un documento de texto en “Mis documentos” para adjuntar archivos.</div>':''}</div><div class="ntv4-store"><h3>📊 Subir Excel/CSV</h3><div class="ntv4-storegrid"><div class="full"><label>Archivo .xlsx, .xls, .xlsm o .csv (máx. 25 MB)</label><input id="ntv4StoreExcelFile" type="file" accept=".xlsx,.xls,.xlsm,.csv"></div></div><div class="ntv4-storeactions"><button class="btn secondary" id="ntv4StoreExcelUpload">Subir Excel</button></div><div id="ntv4StoreExcelStatus" class="status"></div></div><div class="ntv4-store"><h3>Archivos personales</h3>${personalTable(files.data||[])}</div><div class="ntv4-store"><h3>Excel registrados</h3>${excelTable(xls.data||[])}</div>`;$('ntv4StorePersonalUpload').disabled=!(docs.data||[]).length;$('ntv4StorePersonalUpload').onclick=uploadPersonal;$('ntv4StoreExcelUpload').onclick=uploadExcel;wireOpen()}catch(e){globalShell('Mis archivos');area().innerHTML=`<div class="ntv4-store" style="color:#933">${esc(e.message||e)}</div>`}}
function personalTable(a){if(!a.length)return '<div>Sin archivos adjuntos.</div>';return `<table class="ntv4-storetable"><tr><th>Archivo</th><th>Tipo</th><th>Tamaño</th><th></th></tr>${a.map(x=>`<tr><td>${esc(x.file_name||'')}</td><td>${esc(x.mime_type||'')}</td><td>${Math.round(Number(x.size_bytes||0)/1024)} KB</td><td><button class="btn light" data-open-store="personal" data-path="${esc(x.storage_path)}">Abrir</button></td></tr>`).join('')}</table>`}
function excelTable(a){if(!a.length)return '<div>Sin Excel.</div>';return `<table class="ntv4-storetable"><tr><th>Archivo</th><th>Ext.</th><th>Tamaño</th><th></th></tr>${a.map(x=>`<tr><td>${esc(x.original_name||'')}</td><td>${esc(x.file_ext||'')}</td><td>${Math.round(Number(x.size_bytes||0)/1024)} KB</td><td><button class="btn light" data-open-store="excel" data-path="${esc(x.storage_path)}">Abrir</button></td></tr>`).join('')}</table>`}
function wireOpen(){document.querySelectorAll('[data-open-store]').forEach(b=>b.onclick=()=>signed(b.dataset.openStore==='excel'?'nursetrack-excel-documents':'nursetrack-personal-docs',b.dataset.path))}
async function uploadPersonal(){if(busy)return;busy=true;const st=$('ntv4StorePersonalStatus');try{const c=ctx||await context(),f=$('ntv4StorePersonalFile').files?.[0],doc=$('ntv4StoreDoc').value;if(!doc)throw new Error('Selecciona un documento.');if(!f)throw new Error('Selecciona un archivo.');if(f.size>25*1024*1024)throw new Error('El archivo excede 25 MB.');const path=`${c.user.id}/${uid()}_${cleanName(f.name)}`;await uploadWithMeta('nursetrack-personal-docs',path,f,'nursetrack_personal_document_files',{user_id:c.user.id,document_id:doc,file_name:f.name,mime_type:f.type||null,size_bytes:f.size});st.textContent='Archivo subido.';st.style.color='#216b48';setTimeout(openPersonal,350)}catch(e){st.textContent=e.message||String(e);st.style.color='#933'}finally{busy=false}}
async function uploadExcel(){if(busy)return;busy=true;const st=$('ntv4StoreExcelStatus');try{const c=ctx||await context(),f=$('ntv4StoreExcelFile').files?.[0];if(!f)throw new Error('Selecciona un Excel/CSV.');const e=ext(f.name);if(!['xlsx','xls','xlsm','csv'].includes(e))throw new Error('Formato no permitido.');if(f.size>25*1024*1024)throw new Error('El archivo excede 25 MB.');const path=`${c.company}/${c.user.id}/${uid()}_${cleanName(f.name)}`;await uploadWithMeta('nursetrack-excel-documents',path,f,'nursetrack_excel_documents',{company_id:c.company,original_name:f.name,file_ext:e,mime_type:f.type||null,size_bytes:f.size,sheet_names:[],created_by:c.user.id,updated_by:c.user.id});st.textContent='Excel registrado.';st.style.color='#216b48';setTimeout(openPersonal,350)}catch(e){st.textContent=e.message||String(e);st.style.color='#933'}finally{busy=false}}
function mrn(){return ($('patientMrn')?.textContent||'').replace(/^(MRN|Expediente)\s*:?-?\s*/i,'').trim()}
async function getPatient(){const c=await context(),m=mrn();if(!m)throw new Error('Abre un paciente primero');const r=await sb.from('nursetrack_patients_v2').select('*').eq('company_id',c.company).ilike('mrn',m).is('deleted_at',null).limit(1);if(r.error)throw r.error;if(!r.data?.[0])throw new Error('Paciente no localizado');patient=r.data[0];return patient}
async function openPatient(){try{style();const p=await getPatient(),c=ctx||await context(),r=await sb.from('nursetrack_patient_documents').select('*').eq('company_id',c.company).eq('patient_id',p.id).order('created_at',{ascending:false});if(r.error)throw r.error;area().innerHTML=`<div class="ntv4-store"><h3>📂 Archivos del paciente</h3><div>${esc([p.first_name,p.last_name].filter(Boolean).join(' '))} · ${esc(p.mrn||'')}</div><div class="ntv4-storegrid"><div><label>Categoría</label><input id="ntv4PatientFileCategory" value="Otro"></div><div><label>Archivo (PDF/JPG/PNG/HEIC/HEIF, máx. 10 MB)</label><input id="ntv4PatientFile" type="file" accept="application/pdf,image/jpeg,image/png,image/heic,image/heif"></div></div><div class="ntv4-storeactions"><button class="btn" id="ntv4PatientFileUpload">Subir al expediente</button></div><div id="ntv4PatientFileStatus" class="status"></div></div><div class="ntv4-store">${patientTable(r.data||[])}</div>`;$('ntv4PatientFileUpload').onclick=uploadPatient;document.querySelectorAll('[data-patient-store]').forEach(b=>b.onclick=()=>signed('nursetrack-patient-documents',b.dataset.patientStore))}catch(e){area().innerHTML=`<div class="ntv4-store" style="color:#933">${esc(e.message||e)}</div>`}}
function patientTable(a){if(!a.length)return '<div>Sin archivos del paciente.</div>';return `<table class="ntv4-storetable"><tr><th>Fecha</th><th>Categoría</th><th>Archivo</th><th>Tamaño</th><th></th></tr>${a.map(x=>`<tr><td>${esc(String(x.created_at||'').replace('T',' ').slice(0,16))}</td><td>${esc(x.category||'')}</td><td>${esc(x.file_name||'')}</td><td>${Math.round(Number(x.size_bytes||0)/1024)} KB</td><td><button class="btn light" data-patient-store="${esc(x.storage_path)}">Abrir</button></td></tr>`).join('')}</table>`}
async function uploadPatient(){if(busy)return;busy=true;const st=$('ntv4PatientFileStatus');try{const c=ctx||await context(),p=patient||await getPatient(),f=$('ntv4PatientFile').files?.[0],cat=$('ntv4PatientFileCategory').value.trim()||'Otro';if(!f)throw new Error('Selecciona un archivo.');const allowed=['application/pdf','image/jpeg','image/png','image/heic','image/heif'];if(!allowed.includes(f.type))throw new Error('Formato no permitido para expediente.');if(f.size>10*1024*1024)throw new Error('El archivo excede 10 MB.');const path=`${c.company}/${p.id}/${uid()}_${cleanName(f.name)}`;await uploadWithMeta('nursetrack-patient-documents',path,f,'nursetrack_patient_documents',{company_id:c.company,patient_id:p.id,category:cat,file_name:f.name,mime_type:f.type||null,size_bytes:f.size,uploaded_by:c.user.id});st.textContent='Archivo añadido al expediente.';st.style.color='#216b48';setTimeout(openPatient,350)}catch(e){st.textContent=e.message||String(e);st.style.color='#933'}finally{busy=false}}
window.NT_V4_STORAGE={openPersonal,openPatient};
})();