(function(){
'use strict';
if(window.__NT_V4_TEMPLATES_EDITOR__) return;
window.__NT_V4_TEMPLATES_EDITOR__=true;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const $=id=>document.getElementById(id);let sb=null,ctx=null,profile=null,busy=false;
function addStyles(){if($('ntV4TplStyle'))return;const s=document.createElement('style');s.id='ntV4TplStyle';s.textContent='.ntv4-tplcard{background:#fff;border:1px solid #d8e6e8;border-radius:14px;padding:16px;margin-top:12px}.ntv4-tplgrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ntv4-tplgrid .full{grid-column:1/-1}.ntv4-tplactions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.ntv4-tpltable{width:100%;border-collapse:collapse}.ntv4-tpltable th,.ntv4-tpltable td{padding:8px;border-bottom:1px solid #e5eeee;text-align:left;font-size:12px;vertical-align:top}.ntv4-json{font-family:ui-monospace,Consolas,monospace;min-height:230px}.ntv4-tplbadge{display:inline-block;border:1px solid #d8e6e8;border-radius:999px;padding:3px 7px;background:#f8fbfb;font-size:11px}@media(max-width:720px){.ntv4-tplgrid{grid-template-columns:1fr}.ntv4-tplgrid .full{grid-column:auto}.ntv4-tpltable{display:block;overflow:auto}}';(document.head||document.documentElement).appendChild(s)}
async function client(){if(sb)return sb;if(typeof window.NT_loadSupabase!=='function')throw new Error('Supabase no disponible');const lib=await window.NT_loadSupabase(),cfg=window.NURSETRACK_SUPABASE||{};sb=lib.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
async function getCtx(){await client();const ses=await sb.auth.getSession(),u=ses?.data?.session?.user;if(!u)throw new Error('Sesión no disponible');let company=null;const cu=await sb.from('nursetrack_company_users').select('company_id').eq('user_id',u.id).eq('active',true).limit(1);if(cu.data?.[0])company=cu.data[0].company_id;if(!company){const m=await sb.from('nursetrack_account_memberships').select('company_id').eq('user_id',u.id).eq('status','active').limit(1);company=m.data?.[0]?.company_id||null}if(!company)throw new Error('No hay compañía activa');const p=await sb.from('nursetrack_profiles').select('role,full_name').eq('user_id',u.id).maybeSingle();profile=p.data||{};ctx={user:u,company};return ctx}
function globalShell(){['homePanel','modulesPanel','placeholderPanel'].forEach(id=>$(id)?.classList.add('hidden'));$('patientPanel')?.classList.remove('hidden');if($('patientName'))$('patientName').textContent='Biblioteca de Plantillas';if($('patientMrn'))$('patientMrn').textContent='';if($('patientDemographics'))$('patientDemographics').innerHTML='';const a=document.querySelector('#patientPanel .actions');if(a)a.style.display='none';if($('newVisitBtn'))$('newVisitBtn').style.display='none';if($('pageTitle'))$('pageTitle').textContent='Plantillas';if($('patientActionArea'))$('patientActionArea').innerHTML=''}
function out(html){globalShell();$('patientActionArea').innerHTML=html}
function isSuper(){return ['superadmin','superadministrator'].includes(String(profile?.role||'').toLowerCase())}
function pretty(v){try{return JSON.stringify(v??{},null,2)}catch{return '{}'}}
function parseJson(id){const raw=$(id).value.trim()||'{}';try{const v=JSON.parse(raw);if(v===null||Array.isArray(v)||typeof v!=='object')throw new Error();return v}catch{throw new Error(`${id.includes('Style')?'Estilo':'Esquema'} JSON inválido.`)}}
function keyFromName(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'').slice(0,80)}
async function templates(){const c=ctx||await getCtx();const r=await sb.from('nursetrack_templates').select('id,company_id,template_key,template_name,document_type,language,status,current_version,updated_at').is('deleted_at',null).or(`company_id.is.null,company_id.eq.${c.company}`).order('document_type').order('template_name');if(r.error)throw r.error;return r.data||[]}
async function openList(){try{addStyles();await getCtx();const list=await templates();out(`<div class="ntv4-tplcard"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><div><h3>📄 Biblioteca de Plantillas</h3><div>${list.length} plantillas visibles</div></div>${isSuper()?'<button class="btn" id="ntv4TplNew">+ Nueva plantilla</button>':''}</div>${list.length?`<table class="ntv4-tpltable"><thead><tr><th>Plantilla</th><th>Tipo</th><th>Idioma</th><th>Estado</th><th>Versión</th><th>Ámbito</th><th></th></tr></thead><tbody>${list.map(t=>`<tr><td><strong>${esc(t.template_name)}</strong><div>${esc(t.template_key)}</div></td><td>${esc(t.document_type)}</td><td>${esc(t.language)}</td><td><span class="ntv4-tplbadge">${esc(t.status)}</span></td><td>${esc(t.current_version??0)}</td><td>${t.company_id?'Compañía':'Global'}</td><td><button class="btn light" data-tpl-open="${t.id}">Abrir</button></td></tr>`).join('')}</tbody></table>`:'<div>No hay plantillas.</div>'}<div class="notice">No se crean copias automáticas. La misma plantilla mantiene historial por versiones.</div></div>`);$('ntv4TplNew')&&($('ntv4TplNew').onclick=openNew);document.querySelectorAll('[data-tpl-open]').forEach(b=>b.onclick=()=>openTemplate(b.dataset.tplOpen))}catch(e){out(`<div class="ntv4-tplcard" style="color:#933">${esc(e.message||e)}</div>`)}}
async function openTemplate(id){try{addStyles();await getCtx();const [r,v]=await Promise.all([sb.from('nursetrack_templates').select('*').eq('id',id).is('deleted_at',null).single(),sb.from('nursetrack_template_versions').select('version_number,change_note,created_at').eq('template_id',id).order('version_number',{ascending:false}).limit(20)]);if(r.error)throw r.error;if(v.error)throw v.error;const t=r.data,editable=isSuper();out(`<div class="ntv4-tplcard"><button class="btn light" id="ntv4TplBack">← Biblioteca</button><h3>${esc(t.template_name)}</h3><div class="ntv4-tplgrid"><div><label>Nombre</label><input id="ntv4TplName" value="${esc(t.template_name)}" ${editable?'':'disabled'}></div><div><label>Clave</label><input value="${esc(t.template_key)}" disabled></div><div><label>Tipo de documento</label><input id="ntv4TplType" value="${esc(t.document_type)}" ${editable?'':'disabled'}></div><div><label>Idioma</label><input id="ntv4TplLang" value="${esc(t.language)}" ${editable?'':'disabled'}></div><div class="full"><label>Esquema JSON</label><textarea id="ntv4TplSchema" class="ntv4-json" ${editable?'':'disabled'}>${esc(pretty(t.schema_json))}</textarea></div><div class="full"><label>Estilo JSON</label><textarea id="ntv4TplStyleJson" class="ntv4-json" ${editable?'':'disabled'}>${esc(pretty(t.style_json))}</textarea></div></div>${editable?`<div class="ntv4-tplactions"><button class="btn" id="ntv4TplSave">Guardar borrador</button><button class="btn secondary" id="ntv4TplPublish">Publicar nueva versión</button></div>`:''}<div id="ntv4TplStatus" class="status"></div></div><div class="ntv4-tplcard"><h3>Versiones</h3>${v.data?.length?`<table class="ntv4-tpltable">${v.data.map(x=>`<tr><td>v${esc(x.version_number)}</td><td>${esc(x.change_note||'')}</td><td>${esc(String(x.created_at||'').replace('T',' ').slice(0,16))}</td></tr>`).join('')}</table>`:'<div>Aún no hay versiones publicadas.</div>'}</div>`);$('ntv4TplBack').onclick=openList;if(editable){$('ntv4TplSave').onclick=()=>saveTemplate(t.id);$('ntv4TplPublish').onclick=()=>publishTemplate(t.id)}}catch(e){out(`<div class="ntv4-tplcard" style="color:#933">${esc(e.message||e)}</div>`)}}
async function saveTemplate(id){if(busy)return;busy=true;const st=$('ntv4TplStatus');try{const schema=parseJson('ntv4TplSchema'),style=parseJson('ntv4TplStyleJson'),name=$('ntv4TplName').value.trim(),type=$('ntv4TplType').value.trim(),lang=$('ntv4TplLang').value.trim();if(!name||!type||!lang)throw new Error('Nombre, tipo e idioma son requeridos.');const r=await sb.from('nursetrack_templates').update({template_name:name,document_type:type,language:lang,schema_json:schema,style_json:style,status:'draft',updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;st.textContent='Borrador guardado. No se creó ninguna plantilla duplicada.';st.style.color='#216b48'}catch(e){st.textContent=e.message||String(e);st.style.color='#933'}finally{busy=false}}
async function publishTemplate(id){if(busy)return;busy=true;const st=$('ntv4TplStatus');try{await saveTemplate(id);const note=prompt('Nota de cambio para esta versión:')||'Actualización desde NurseTrack v4';const r=await sb.rpc('nursetrack_publish_template',{p_template_id:id,p_change_note:note});if(r.error)throw r.error;st.textContent=`Plantilla publicada como versión ${r.data?.[0]?.version_number||'nueva'}.`;st.style.color='#216b48';setTimeout(()=>openTemplate(id),450)}catch(e){st.textContent=e.message||String(e);st.style.color='#933'}finally{busy=false}}
function openNew(){out(`<div class="ntv4-tplcard"><button class="btn light" id="ntv4TplBack">← Biblioteca</button><h3>Nueva plantilla</h3><div class="ntv4-tplgrid"><div><label>Nombre *</label><input id="ntv4NewName"></div><div><label>Clave</label><input id="ntv4NewKey" placeholder="Se genera desde el nombre"></div><div><label>Tipo *</label><input id="ntv4NewType" placeholder="nursing, social_work, medical..."></div><div><label>Idioma</label><input id="ntv4NewLang" value="es"></div><div class="full"><label>Esquema JSON</label><textarea id="ntv4NewSchema" class="ntv4-json">{}</textarea></div><div class="full"><label>Estilo JSON</label><textarea id="ntv4NewStyle" class="ntv4-json">{}</textarea></div></div><div class="ntv4-tplactions"><button class="btn" id="ntv4NewSave">Crear borrador</button></div><div id="ntv4NewStatus" class="status"></div></div>`);$('ntv4TplBack').onclick=openList;$('ntv4NewName').oninput=()=>{if(!$('ntv4NewKey').dataset.manual)$('ntv4NewKey').value=keyFromName($('ntv4NewName').value)};$('ntv4NewKey').oninput=()=>{$('ntv4NewKey').dataset.manual='1'};$('ntv4NewSave').onclick=createTemplate}
async function createTemplate(){if(busy)return;busy=true;const st=$('ntv4NewStatus');try{const c=ctx||await getCtx(),name=$('ntv4NewName').value.trim(),key=keyFromName($('ntv4NewKey').value||name),type=$('ntv4NewType').value.trim(),lang=$('ntv4NewLang').value.trim()||'es',schema=JSON.parse($('ntv4NewSchema').value||'{}'),style=JSON.parse($('ntv4NewStyle').value||'{}');if(!name||!key||!type)throw new Error('Nombre, clave y tipo son requeridos.');if(Array.isArray(schema)||schema===null||typeof schema!=='object')throw new Error('Esquema JSON inválido.');const ex=await sb.from('nursetrack_templates').select('id').eq('company_id',c.company).eq('template_key',key).eq('language',lang).is('deleted_at',null).limit(1);if(ex.error)throw ex.error;if(ex.data?.length)throw new Error('Ya existe una plantilla con esa clave e idioma en esta compañía.');const r=await sb.from('nursetrack_templates').insert({company_id:c.company,template_key:key,template_name:name,document_type:type,language:lang,status:'draft',current_version:0,schema_json:schema,style_json:style,created_by:c.user.id}).select('id').single();if(r.error)throw r.error;st.textContent='Borrador creado.';st.style.color='#216b48';setTimeout(()=>openTemplate(r.data.id),400)}catch(e){st.textContent=e.message||String(e);st.style.color='#933'}finally{busy=false}}
function hook(){document.querySelectorAll('#modulesPanel .module').forEach(b=>{const t=(b.querySelector('strong')?.textContent||'').toLowerCase();if(t==='plantillas')b.onclick=openList})}
function init(){addStyles();hook();new MutationObserver(hook).observe(document.body,{childList:true,subtree:true});window.NT_V4_TEMPLATES={open:openList}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();